### ISSUE TITLE
Some new features!

### ISSUE THREAD

**Issue by mastercho** [gobysec/Goby#1]
Its says have an option for scanning RDP vulnerabilities but i don't see to check for weak passwords like administrator:123456
But overall i like the idea and i think Goby can be new Infection Monkey :)

You just need to add things which Monkey have, and again good job. Will be good to add also export of report

**Comment by LubyRuffy** [comment]
> Its says have an option for scanning RDP vulnerabilities but i don't see to check for weak passwords like administrator:123456
> But overall i like the idea and i think Goby can be new Infection Monkey :)
> 
> You just need to add things which Monkey have, and again good job. Will be good to add also export of report

thanks， RDP brute force is not stable now, so removed temporary.
