### ISSUE TITLE
1.7.192在win10下与kali2020下启动问题

### ISSUE THREAD

**Issue by c0o1sy1z3** [gobysec/Goby#101]
win10版是别人转发的压缩包，开启后跳#error query报错，扫描单一ip特定端口跳报错提示，之前只有安装winpcap，于是按照官网提示安装ncap0.9989，启动后不再跳#error query报错，但是出现如下问题
警告
2020/09/13 10：01：07 Grab version：grab__version_1.7.1.1
Up
2020/09/13 10：01：07 Support 269 protocols，454 ports panic：no network adapter name：{xxxxxxxxxx}，use listAdapters mode to show all goroutine 1
[running]：main.checklfaceExists（）
/opt/gopath/src/git.gobies.org/goby/goby/cmd/goby-cmd/main.go：90
+0x1f5 main.main（）
/opt/gopath/src/git.gobies.org/goby/goby/cmd/goby-
cmd/main.go：224 +0x1287

可能存在以下原因：
●8361端口被占用，导致无法启动服务。
●Npcap被其它程序占用，导致无法识别网卡。关掉占用程序或重新安装Npcap。

其中提示的网卡与wireshark中所使用的一致，并且可正常使用。而本地8361端口并未被占用。
关掉这个错误提示后就进入重启服务状态，无法修改任何设置，安装最新版ncap0.9997，问题依然存在，软件路径无中文。

Kali2020版直接官网下载，启动后同样跳#error query报错，安装完
警告
2020/09/13 09：56：01 Grab version：grab__version__1.7.1.1 2020/09/...更多
可能存在以下原因：
●8361端口被占用，导致无法启动服务。
●Npcap被其它程序占用，导致无法识别网卡。关掉占用程序或重新安装Npcap。
●网络抖动。关闭该弹窗后，不影响扫描进程。
●服务中断。关闭该弹窗后，会自动重启服务。

libgconf2*安装结果如下
xxx:~/goby-linux$ sudo apt-get install libgconf2*
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libgconf2-4' for glob 'libgconf2*'
Note, selecting 'libgconf2.0-cil' for glob 'libgconf2*'
Note, selecting 'libgconf2-dev' for glob 'libgconf2*'
Note, selecting 'libgconf2-doc' for glob 'libgconf2*'
libgconf2-dev is already the newest version (3.2.6-6).
libgconf2-doc is already the newest version (3.2.6-6).
0 upgraded, 0 newly installed, 0 to remove and 337 not upgraded.

端口8361同样未被占用
Kali里面这个错误在ncap模式下不能扫描，在socket模式下可以扫描，但是无法尝试利用漏洞，会跳#error query错误。

个人觉得出错之后不给修改配置而直接自动重新连接服务器比较反人类，ncap不能用至少给改成socket试试吧，希望开发大佬考虑一下这个处理方式，Goby是个好软件，支持一大波。

**Comment by gobysec** [comment]
1）更新npcap到0.9995以上版本。
2）自动连接服务器已在1.7.194版本优化。
