### ISSUE TITLE
扫描至70%，再无进度更新

### ISSUE THREAD

**Issue by runningCsnail** [gobysec/Goby#102]
70%是扫描什么呢？为什么试了3个IP，进度都只更新到70%，再十多分钟内无进度更新。

**Comment by gobysec** [comment]
> 70%是扫描什么呢？为什么试了3个IP，进度都只更新到70%，再十多分钟内无进度更新。

data/logs  看下日志具体啥情况

**Comment by gobysec** [comment]
最新版1.8.221已解决。
