### ISSUE TITLE
任务停止后还会继续扫描

### ISSUE THREAD

**Issue by Betsy0** [gobysec/Goby#107]
今天中午11点多得时候开启了个a扫描任务，大概13点多的时候手动停止了，然后开启另一个b扫描，但是15点半的时候a的厂商找上门了说还在扫，关机重启后才停掉

**Comment by gobysec** [comment]
> 今天中午11点多得时候开启了个a扫描任务，大概13点多的时候手动停止了，然后开启另一个b扫描，但是15点半的时候a的厂商找上门了说还在扫，关机重启后才停掉

是启用了远程服务器吗？C/S模式下的话，客户端的暂停是无法对服务端生效的。后续我们改进，感谢反馈。

**Comment by Betsy0** [comment]
本机的------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Goby&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月24日(星期四) 晚上6:04
收件人:&nbsp;&quot;gobysec/Goby&quot;<Goby@noreply.github.com&gt;;
抄送:&nbsp;&quot;Betsy0&quot;<849310853@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gobysec/Goby] 任务停止后还会继续扫描 (#107)
