### ISSUE TITLE
端口识别问题不少

### ISSUE THREAD

**Issue by samshuai** [gobysec/Goby#111]
删掉默认的端口设置改为1-65535
直接识别率很低，用默认的稍微好点
然后就是连群晖都识别不出来，只识别到nginx资产。

**Comment by gobysec** [comment]
> 删掉默认的端口设置改为1-65535
> 直接识别率很低，用默认的稍微好点
> 然后就是连群晖都识别不出来，只识别到nginx资产。

![image](https://user-images.githubusercontent.com/50955360/95956170-80612000-0e30-11eb-9e29-056160bc096a.png)
取消随机扫描IP试试。

**Comment by samshuai** [comment]
@gobysec 使用这个方式后，确实识别率提高不少
