### ISSUE TITLE
Mac提示请先安装谷歌浏览器

### ISSUE THREAD

**Issue by paradiseduo** [gobysec/Goby#113]
![image](https://user-images.githubusercontent.com/14846965/97953943-0394e680-1ddd-11eb-8ab4-182be4fa7ee1.png)
但是我已经安装了
![image](https://user-images.githubusercontent.com/14846965/97953963-1a3b3d80-1ddd-11eb-8d5b-a4f04400b234.png)
![image](https://user-images.githubusercontent.com/14846965/97953973-1f988800-1ddd-11eb-868e-39e10d7907fb.png)
而且设置里面也没有选择安装路径的地方

**Comment by gobysec** [comment]
可以提供安装路径吗

**Comment by paradiseduo** [comment]
> 可以提供安装路径吗

Mac上的App还有其他安装路径吗？
都在
`/Applications/`
下面
