### ISSUE TITLE
PPPoE扫描问题

### ISSUE THREAD

**Issue by burpheart** [gobysec/Goby#114]
使用PPPoE连接网络时无法识别网卡 手动绑定出口网卡也不能启动扫描

**Comment by gobysec** [comment]
> 使用PPPoE连接网络时无法识别网卡 手动绑定出口网卡也不能启动扫描

升级npcap到0.9995以上（最新）版本试试。若还是无法识别网卡，则说明npcap自身还不支持，goby暂时也无法解决。
