### ISSUE TITLE
hadoop、apche flink未授权命令执行 -----两个漏洞：已经检测出资产，但是其漏洞列表没有显示相关漏洞

### ISSUE THREAD

**Issue by M2ayill** [gobysec/Goby#119]
![image](https://user-images.githubusercontent.com/22850233/98538916-7105b300-22c6-11eb-8cde-7b58f985c4c7.png)
![image](https://user-images.githubusercontent.com/22850233/98538947-7cf17500-22c6-11eb-87a3-615f5ea7d51c.png)

**Comment by M2ayill** [comment]
Apache flink

![image](https://user-images.githubusercontent.com/22850233/98543432-761a3080-22cd-11eb-92d3-ca71d8df50e2.png)
![image](https://user-images.githubusercontent.com/22850233/98543478-83371f80-22cd-11eb-9181-6e2de94698bd.png)

**Comment by gobysec** [comment]
你好，其它工具或手动有检测到漏洞吗？

**Comment by gobysec** [comment]
已修复
