### ISSUE TITLE
domain太多，会显示ip格式错误。

### ISSUE THREAD

**Issue by useafter** [gobysec/Goby#12]
![1](https://user-images.githubusercontent.com/8403123/65851817-d3337b00-e386-11e9-98b4-9293309e77ad.png)

**Comment by BalanceKuang** [comment]
1.3.44 beta版本

**Comment by gobysec** [comment]
可能是某个域名格式不对，这个问题我们已经做了优化，可以看到是哪个IP/域名的格式不对，根据提示进行修改即可。
