### ISSUE TITLE
Elasticsearch未授权漏洞利用插件下载后出现bug

### ISSUE THREAD

**Issue by zaneSSS** [gobysec/Goby#121]
Elasticsearch未授权漏洞利用插件下载后，扩展程序无法加载，扫描页面不显示进度。

**Comment by gobysec** [comment]
> Elasticsearch未授权漏洞利用插件下载后，扩展程序无法加载，扫描页面不显示进度。

漏洞是否有扫描出来？

**Comment by zaneSSS** [comment]
还没开始扫描漏洞，只是安装了插件，然后重启，就出现插件加载不出来（把这个插件删了就能正常加载），扫描时，左下角的历史记录显示扫描已完成，但是下方的按钮一直是0%






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gobysec/Goby"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月17日(星期二) 上午10:27
收件人:&nbsp;"gobysec/Goby"<Goby@noreply.github.com&gt;;
抄送:&nbsp;"Zane"<1191582297@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gobysec/Goby] Elasticsearch未授权漏洞利用插件下载后出现bug (#121)





  
Elasticsearch未授权漏洞利用插件下载后，扩展程序无法加载，扫描页面不显示进度。
  
漏洞是否有扫描出来？

**Comment by gobysec** [comment]
> 还没开始扫描漏洞，只是安装了插件，然后重启，就出现插件加载不出来（把这个插件删了就能正常加载），扫描时，左下角的历史记录显示扫描已完成，但是下方的按钮一直是0%
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gobysec/Goby" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月17日(星期二) 上午10:27 收件人:&nbsp;"gobysec/Goby"<Goby@noreply.github.com&gt;; 抄送:&nbsp;"Zane"<1191582297@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [gobysec/Goby] Elasticsearch未授权漏洞利用插件下载后出现bug (#121) Elasticsearch未授权漏洞利用插件下载后，扩展程序无法加载，扫描页面不显示进度。 漏洞是否有扫描出来？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

1. 插件加载不出来是指哪个位置？扩展程序还是漏洞验证？2. 如果是漏洞验证，你未扫描漏洞，如何进行漏洞验证？3. 该插件的使用教程：https://mp.weixin.qq.com/s/XZA37Cen9PexyPxuuEx1CQ
