### ISSUE TITLE
增加如下服务暴力破解

### ISSUE THREAD

**Issue by hcjcn** [gobysec/Goby#122]
"ftp"
    "mysql":
    "mssql":
    "telnet":
    "postgresql":
    "redis"
    "mongodb":
    "memcached"
    "elasticsearch"
    "hadoop":
    "rabbitmq"

**Comment by starnightcyber** [comment]
应该是有一部分了
![image](https://user-images.githubusercontent.com/19260696/100065080-4f7ffc00-2e6e-11eb-98eb-387f5885d233.png)
