### ISSUE TITLE
新建扫描任务时，若是输入域名，提示解析域名出错

### ISSUE THREAD

**Issue by menghao56392** [gobysec/Goby#13]
在新建扫描任务时，输入github.com格式提示dns lookup failed of target，貌似域名解析失败

**Comment by menghao56392** [comment]
![image](https://user-images.githubusercontent.com/46192576/65853007-a41f0880-e38a-11e9-9485-39216a3ed173.png)

**Comment by gobysec** [comment]
这个问题我们已经解决了，请下载最新版。如若复现，请重新提个iusse。
