### ISSUE TITLE
深信服等vpn无法扫描问题

### ISSUE THREAD

**Issue by gobysec** [gobysec/Goby#148]
深信服等vpn无法扫描问题

**Comment by gobysec** [comment]
> 深信服等vpn无法扫描问题

1.wireshark抓包可以发现VPN网卡，但Goby无法识别网卡。

经分析，npcap本身bug导致无法识别vpn的ipv4地址。解决方案是升级npcap到0.9995以上版本。

2.wireshark抓包没有发现vpn网卡，Goby也无法识别网卡。

这种问题亦来自npcap本身，Goby暂时不做处理。

**Comment by Aixic-Love** [comment]
macos如何解决呢？ @gobysec
