### ISSUE TITLE
V1.3.44beta 资产IP矩阵图显示不准确

### ISSUE THREAD

**Issue by juju3316** [gobysec/Goby#15]
![image](https://user-images.githubusercontent.com/35027394/65863658-23b8d180-e3a3-11e9-83e1-0e5379efb9af.png)
识别出来资产后，其中IP矩阵图不存在的主机显示围存活主机。一个C段的地址全部存在。扫描一个不存在的C网段，矩阵图同样显示全部主机存活。我的运行环境市WIN 10专业版64位系统。

**Comment by gobysec** [comment]
如何确定C网段为不存在网段呢？

**Comment by juju3316** [comment]
问题已经解决，谢谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Goby"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月28日(星期二) 晚上6:09
收件人:&nbsp;"gobysec/Goby"<Goby@noreply.github.com&gt;;
抄送:&nbsp;"知鱼之乐"<331633365@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gobysec/Goby] V1.3.44beta 资产IP矩阵图显示不准确 (#15)





 
Reopened #15.

**Comment by RanrayD** [comment]
是的，我也遇到了同样的问题，我现在使用的是1.8.230版本；
在对内网的一个网段172.17.20.0/24进行资产识别扫描的时候，发现会显示255个存活IP；
实际上只有40个，其余的我查看结果的时候，发现了扫描结果中，均显示了25和110端口的开放，导致所有该网段内的IP地址都存活，请问有什么好的方法可以解决呢（除了在扫描之前，删除端口范围中的25和110）；
非常感谢
