### ISSUE TITLE
存在Memcached未授权漏洞但无法扫描出来的问题

### ISSUE THREAD

**Issue by sv3nbeast** [gobysec/Goby#157]
Memcached未授权访问漏洞
目标机器的12000，12001存在此漏洞，使用goby设置扫描此漏洞，重复多次未扫描出来
![image](https://user-images.githubusercontent.com/55974091/101719157-b7c11580-3add-11eb-9771-9bb9d8d85b8a.png)
![image](https://user-images.githubusercontent.com/55974091/101719178-c3acd780-3add-11eb-9ee0-3133130a3b0c.png)
![image](https://user-images.githubusercontent.com/55974091/101719194-cc051280-3add-11eb-9d6c-26a9931e8d08.png)

猜测：端口不是默认Memcached的端口所以导致无法扫描出来？

顺便请问是否其他漏洞也会存在此类现象？

感谢提供的goby工具

**Comment by gobysec** [comment]
感谢反馈，属于协议未识别导致的资产未识别。后面安排上。
