### ISSUE TITLE
mac无法启动最新内测版

### ISSUE THREAD

**Issue by swjor** [gobysec/Goby#159]
mac下打开启动goby，一直卡在Analyzing the current environment，已设置网卡权限

**Comment by swjor** [comment]
mac系统版本是 catalina 10.15.7

**Comment by swjor** [comment]
goby版本是内测版1.8.230修复版

**Comment by swjor** [comment]
放在应用程序目录下使用root启动报错：LSOpenURLsWithRole() failed for the application /Applications/Goby.app with error -10810

**Comment by gobysec** [comment]
> mac下打开启动goby，一直卡在Analyzing the current environment，已设置网卡权限
可能是没有下载完全，也可能是解压时忽略了空文件夹，重新下载解压试试
