### ISSUE TITLE
Asset界面的2个小建议

### ISSUE THREAD

**Issue by bit4woo** [gobysec/Goby#174]
![image](https://user-images.githubusercontent.com/8793481/105838026-7d1e2880-600a-11eb-8182-fe40fd43789d.png)

在资产界面：
1、建议有复制ip:port的功能，便于某些情况下进行复测等操作。
2、建议通过组件（Component）筛选后有返回菜单，可以返回到之前的页面。

**Comment by gobysec** [comment]
已知建议，排期优化中，感谢您对Goby的支持与反馈~
