### ISSUE TITLE
New Scan界面的文本域是否能做的长一些，或者能拉拽增长

### ISSUE THREAD

**Issue by serchaofan** [gobysec/Goby#175]
版本：v1.8.230beta windows10
需求：是否能将New Scan中 IP/Domain 以及Port的文本域拉长或者变为可拉拽变长的形式（有增大范围）。目前虽然可以拖滚动条，但是看起来还是不太方便

![Snipaste_2021-01-27_10-07-11](https://user-images.githubusercontent.com/32541818/105932934-9ebdf500-6088-11eb-992b-e4091472e228.png)

**Comment by gobysec** [comment]
1.8.237已支持
