### ISSUE TITLE
是否能在自定义端口集合界面添加一个文本域，可以把自定义的目标端口添加进去

### ISSUE THREAD

**Issue by serchaofan** [gobysec/Goby#177]
版本：v1.8.230 beta  win10
需求：添加自定义端口集合时查不到指定端口，就添加不了
想问下，这个查找是基于什么集合？是否能添加一个文本域，可以把自定义的目标端口添加进去？
![image](https://user-images.githubusercontent.com/32541818/105942497-4c85cf80-609a-11eb-8ff4-09cfe30a5a1e.png)

**Comment by gobysec** [comment]
![image](https://user-images.githubusercontent.com/50955360/109475102-437c8980-7ab0-11eb-831c-32a9525610f0.png)
已解决您的需求，感谢您对Goby的支持与反馈~
