### ISSUE TITLE
关于导出问题

### ISSUE THREAD

**Issue by ROCKLEE-1998** [gobysec/Goby#178]
版本v1.8.230 beta
引擎 v1.24.262_beta
环境windows10 64
![14](https://user-images.githubusercontent.com/52626219/106581343-b7914380-657d-11eb-830a-4ba57bcdb22a.png)
导出的pdf中域名显示不完全
导出的excel表格中，也没有域名，只有其他信息，后续是否可以加上域名信息，pdf导出是否可以显示域名全部信息
一些特殊需要，需要直接复制goby中的信息，下版本是否可以直接支持在goby中复制文字图片等

**Comment by gobysec** [comment]
已知建议，排期优化，不定期更新进展，感谢您的支持与反馈~
