### ISSUE TITLE
请问Pcap、Socket二者扫描模式的差异是什么

### ISSUE THREAD

**Issue by cybfly** [gobysec/Goby#18]
同一个主机通过Socket能够识别到更多的信息
请问从官方角度可否提供比较详细的差异说明？
浏览了官网内容，未找到有相关的介绍
谢谢

**Comment by LubyRuffy** [comment]
- socket是通过调用系统协议栈实现完整的tcp连接的方式，优点是准确度高，缺点是速度慢；
- pcap是半连接的扫描方式，速度很快，但是在重试机制和网络稳定性方面不如系统协议栈；

如果IP数多协议多不建议用socket模式，但是如果目标机器没有安装pcap（如物联网设备）那就只能用socket模式。

默认是用pcap发包模式。
