### ISSUE TITLE
【建议】若遇扫描中断，自动重启服务，无需人工干预。

### ISSUE THREAD

**Issue by zhikai-yang** [gobysec/Goby#186]
![QQ截图20210308171543](https://user-images.githubusercontent.com/49137680/110300538-f0678100-8031-11eb-8418-0a5533f04355.png)
提示“服务中断。关闭该弹窗后，会自动重启服务”

【建议】
1、若遇扫描中断，自动重启服务，无需人工干预。实现无人值守扫描。
2、在扫描界面增加“通知/日志”模块，记录扫描过程的中断，提示用户。

**Comment by gobysec** [comment]
已知建议，排期优化，不定期更新进展，感谢您的支持与反馈~
