### ISSUE TITLE
扫描服务中断，错误日志如下

### ISSUE THREAD

**Issue by chalan630** [gobysec/Goby#191]
2021/03/13 15:56:22 Grab version:  grab_version_1.7.1.1
2021/03/13 15:56:22 Support 276  protocols, 695  ports
2021/03/13 15:56:22 <nil>
2021/03/13 15:56:22 Version: v1.24.262+beta
2021/03/13 15:56:22 API Server listen at  127.0.0.1:8361
2021/03/13 15:56:23 127.0.0.1:1412   GET   /api/v1/version  
2021/03/13 15:56:23 127.0.0.1:1413   GET   /api/v1/live  
2021/03/13 15:57:57 127.0.0.1:1441   POST   /api/v1/getStatisticsData  
2021/03/13 15:57:58 127.0.0.1:1442   POST   /api/v1/resumeScan  
2021/03/13 15:57:58 scan  21,22,23,25,53,U:53,80,81,110,111,123,U:123,135,U:137,139,U:161,389,443,445,465,500,515,U:520,U:523,548,623,636,873,902,1080,1099,1433,1521,U:1604,U:1645,U:1701,1883,U:1900,2049,2181,2375,2379,U:2425,3128,3306,3389,4730,U:5060,5222,U:5351,U:5353,5432,5555,5601,5672,U:5683,5900,5938,5984,6000,6379,7001,7077,8080,8081,8443,8545,8686,9000,9001,9042,9092,9100,9200,9418,9999,11211,27017,37777,50000,50070,61616 192.168.3.10
2021/03/13 15:57:58 127.0.0.1:1443   POST   /api/v1/getProgress  
2021/03/13 15:57:58 [DEBUG] device name is not match: \Device\NPF_{C1D6DDF0-F394-46B2-BBB2-5904EDEC5109} != \Device\NPF_{8537E02E-6E8F-4AB9-A296-C8444FBFE985}
2021/03/13 15:57:58 [DEBUG] device name is not match: \Device\NPF_{9A477AC6-494C-43AD-B575-136C53412840} != \Device\NPF_{8537E02E-6E8F-4AB9-A296-C8444FBFE985}
2021/03/13 15:57:58 [DEBUG] device name is not match: \Device\NPF_{3677F581-9AD1-4767-AAB0-2DD466EEC13D} != \Device\NPF_{8537E02E-6E8F-4AB9-A296-C8444FBFE985}
2021/03/13 15:57:58 [DEBUG] device name is not match: \Device\NPF_{5BBA2F56-8AE5-411D-881D-C537E0DC0187} != \Device\NPF_{8537E02E-6E8F-4AB9-A296-C8444FBFE985}
2021/03/13 15:57:58 [DEBUG] device name is not match: \Device\NPF_{968784B1-6464-499D-8D56-48B2CD24D419} != \Device\NPF_{8537E02E-6E8F-4AB9-A296-C8444FBFE985}
2021/03/13 15:57:58 [DEBUG] device name is not match: \Device\NPF_{48CE5D66-6D80-4755-8EAA-478B3D18B2D5} != \Device\NPF_{8537E02E-6E8F-4AB9-A296-C8444FBFE985}
2021/03/13 15:57:58 [DEBUG] device name is not match: \Device\NPF_{E0996099-09C1-46F5-BC81-8959AD5445F0} != \Device\NPF_{8537E02E-6E8F-4AB9-A296-C8444FBFE985}
2021/03/13 15:57:58 [DEBUG] getGatewayMac: \Device\NPF_{8537E02E-6E8F-4AB9-A296-C8444FBFE985} 192.168.3.10
2021/03/13 15:57:59 find router mac is  f8:8c:21:34:5a:9b
2021/03/13 15:57:59 [DEBUG] fetch mac address: \Device\NPF_{8537E02E-6E8F-4AB9-A296-C8444FBFE985} f8:8c:21:34:5a:9b
2021/03/13 15:57:59 select adapter of to send packets:  &{\Device\NPF_{8537E02E-6E8F-4AB9-A296-C8444FBFE985} 192.168.3.200 {192.168.3.200 ffffff00} ffffff00 40:f0:2f:7f:23:a9 Microsoft f8:8c:21:34:5a:9b}
Starting to read packets
2021/03/13 15:58:01 2021-03-13 15:58:01.2041452 +0800 CST m=+99.020163501
2021/03/13 15:58:01 GrabScannerStatistics: {0 0 0 1}
2021/03/13 15:58:01 AppScannerStatistics: {0 0 0 1}
2021/03/13 15:58:01 ScreenshotStatistics: {0 0 0 0}
2021/03/13 15:58:01 HoneypotCheckerStatistics: {0 0 0 0}
2021/03/13 15:58:01 CrawlerStatistics: {0 0 0 0}
2021/03/13 15:58:01 SendPacketCount: 82 82
2021/03/13 15:58:01 127.0.0.1:1444   POST   /api/v1/getProgress  
2021/03/13 15:58:01 127.0.0.1:1445   POST   /api/v1/getStatisticsData  
2021/03/13 15:58:03 [WARNING] ipv6 is not support now! [fe80::211:32ff:fe2c:a785%WLAN]
2021/03/13 15:58:04 127.0.0.1:1448   POST   /api/v1/getProgress  
2021/03/13 15:58:07 127.0.0.1:1449   POST   /api/v1/getProgress  
2021/03/13 15:58:08 BasicNetworkInfoScanner out...
panic: runtime error: index out of range [3] with length 0

goroutine 119 [running]:
encoding/binary.bigEndian.Uint32(...)
	encoding/binary/binary.go:112
git.gobies.org/goby/portscanner.ip2int(0x0, 0x0, 0x0, 0x0)
	git.gobies.org/goby/portscanner@v0.0.0-20200917072713-0005b126a8ca/portscanner_base.go:49 +0x58
git.gobies.org/goby/portscanner.IP2Int(0xc002d8a0ba, 0x8, 0x227f6fb)
	git.gobies.org/goby/portscanner@v0.0.0-20200917072713-0005b126a8ca/portscanner_base.go:53 +0x80
git.gobies.org/goby/portscanner.(*PortScanner).IsValidHost(0xc0009f8140, 0xc002d8a0ba, 0x8, 0xc0006fea80)
	git.gobies.org/goby/portscanner@v0.0.0-20200917072713-0005b126a8ca/portscanner_base.go:71 +0xf0
git.gobies.org/goby/goby.(*GobyScanner).StartBasicNetworkInfoScanner(0xc0001578c0, 0xc0011791d0)
	git.gobies.org/goby/goby/goby_basic_network_scanner.go:73 +0x22b
created by git.gobies.org/goby/goby.(*GobyScanner).Start
	git.gobies.org/goby/goby/goby.go:250 +0x380

**Comment by gobysec** [comment]
已知问题，我们分析下原因，感谢您的反馈。

**Comment by Y1ng0** [comment]
i also want to know
