### ISSUE TITLE
【官网功能建议】插件页面建议

### ISSUE THREAD

**Issue by djnodt** [gobysec/Goby#193]
https://www.gobies.org/extension.html
官网的插件页面可否显示插件详情：包括作者、插件说明等，方便确定插件的功能以及用法。
可以是点击进入详情页（比较推荐？），也可以是主页那种鼠标悬停显示的形式。

**Comment by gobysec** [comment]
已知建议，排期优化，不定期更新进展，感谢您的支持与反馈~
