### ISSUE TITLE
goby无法使用

### ISSUE THREAD

**Issue by suntaotao01** [gobysec/Goby#206]
我的系统是win10，安装goby-win-x64-1.8.221和goby-win-x64-1.8.230均出现错误告警![image](https://user-images.githubusercontent.com/81618153/112963146-a88fd180-9179-11eb-9334-9909bd5ca6d3.png)。服务器也连接不上，
![image](https://user-images.githubusercontent.com/81618153/112963492-045a5a80-917a-11eb-8922-f47eb321fd3a.png)。安装202版本提示被安全软件拦截，但是将goby加入白名单依然报错。求破。。。。
。

**Comment by gobysec** [comment]
为何不尝试下新版本呢？可能问题已被解决     获取内测版 关注公众号Gobysec回复 加群
