### ISSUE TITLE
Remote Server

### ISSUE THREAD

**Issue by 162phuonganh** [gobysec/Goby#207]
When I start the server by command. The API announce that "auth Error". I don't know why

![image](https://user-images.githubusercontent.com/65727359/113993463-b1ba2600-987e-11eb-87dd-a5c71b9dc7d0.png)

**Comment by gobysec** [comment]
已知问题，下个版本解决，不影响扫描，可正常使用。感谢您的反馈~

**Comment by gobysec** [comment]
This problem will be solved in the next version, it will not affect the scanning and can be used normally. Thanks for your feedback~
