### ISSUE TITLE
希望添加扫描完成的通知功能

### ISSUE THREAD

**Issue by yyanyi213** [gobysec/Goby#211]
有时候在扫描的时候的需要切屏做其他事情，希望添加扫描完成的通知功能，就更方便力。

**Comment by gobysec** [comment]
插件市场已有 邮件通知扫描任务完成 钉钉通知扫描漏洞
[![cg2R7q.png](https://z3.ax1x.com/2021/04/15/cg2R7q.png)](https://imgtu.com/i/cg2R7q)
[![cg2XAx.png](https://z3.ax1x.com/2021/04/15/cg2XAx.png)](https://imgtu.com/i/cg2XAx)
感谢您的支持与反馈~
