### ISSUE TITLE
Scan DB Issue

### ISSUE THREAD

**Issue by 162phuonganh** [gobysec/Goby#212]
I used parameter "-dsn"  for saving scan result in mysql db. Howevers, I received error "[ERROR] exec sql failed:  dial tcp: lookup test.sql: no such host"
![image](https://user-images.githubusercontent.com/65727359/114969613-ee030d00-9ea2-11eb-97a9-2faf72816a2d.png)

**Comment by gobysec** [comment]
Thank you for your support. The current version is limited and will be supported in the near future.
