### ISSUE TITLE
关于报告加载问题反馈

### ISSUE THREAD

**Issue by ibm-appscan** [gobysec/Goby#214]
当资产太大的时候，会遇到报告加载不出来的情况。
当前已扫描完毕，资产4300+ 端口18000+ 但报告和资产已经加载不出来了
更大的问题是报告加载不出来的时候也无法导出资产，导出来的文件是空的

**Comment by gobysec** [comment]
收到 不定期更新进展 感谢反馈~

**Comment by ibm-appscan** [comment]
> 收到 不定期更新进展 感谢反馈~

现在有没有办法能导出资产？

**Comment by gobysec** [comment]
对您的问题感到十分的抱歉，暂时没有好的方法，目前还在定位问题之中，但是您可以尝试用数据库软件打开下面的那几个数据库文件，或许会有一定用处
[image: image.png]

ibm-appscan ***@***.***> 于2021年4月20日周二 下午1:58写道：

**Comment by charis3306** [comment]
能不能不要用.sqlite3改成mysql或es
![image](https://github.com/gobysec/Goby/assets/84823804/912cda46-dfc4-4448-bf2a-736a973f8236)
