### ISSUE TITLE
建议插件部分按照内网和外网做个开关

### ISSUE THREAD

**Issue by Fat-bear** [gobysec/Goby#216]
扫内网的时候他还是会自动调用外网的一些查询插件，导致一直报错。
也没有一个一键开关，删了配置到时候要用还得再配置，很麻烦。

**Comment by gobysec** [comment]
感谢您的反馈，你指的是扫描不出网的内网情况吗？由于一些漏洞需要通过dnslog的方式进行判断，所以会请求godserver。
如果不是这种情况，还希望您能提供更详细的描述，或者截图方便我们复现
