### ISSUE TITLE
红队版goby扫描就报错&全端口扫描时会卡在60%

### ISSUE THREAD

**Issue by pwnr00t** [gobysec/Goby#218]
![图片](https://user-images.githubusercontent.com/40881054/116049737-342d4d00-a6a9-11eb-83b2-7d17bf8f21a5.png)

**Comment by gobysec** [comment]
1. 报错70%情况都是由于线程过高/目标过大，丢包率过高导致，关闭窗口会自动重新连接

**Comment by gobysec** [comment]
1. 报错70%情况都是由于线程过高/目标过大，丢包率过高导致，关闭窗口会自动重新连接
    若还弹窗 可以到目录 date/logs下日志 查看是否有 panic 字样，如有 ，可截图询问
2. 全端口扫描较慢，不建议全端口扫描。依旧可以到目录 date/logs下日志，查看有无时间日志在跑，如有贼为正常。
感谢您的支持与反馈
