### ISSUE TITLE
v1.8.168 beta 版本导出报告中有部分内容显示异常

### ISSUE THREAD

**Issue by kenyon-wong** [gobysec/Goby#219]
如题，在goby v1.8.168 beta 版本中，导出报告中，【网络结构】部分内容显示异常
![图片](https://user-images.githubusercontent.com/39546510/116203249-1249ce00-a76e-11eb-9d3c-35952c0f1c2c.png)

**Comment by gobysec** [comment]
Goby 在外网，可能网络抖动原因造成的显示不及时。感谢您的支持与反馈~
