### ISSUE TITLE
vpn连接情况下，网卡设置连续出错

### ISSUE THREAD

**Issue by sv3nbeast** [gobysec/Goby#22]

**Comment by cliekkas** [comment]
@sv3nbeast 表哥的操作系统是？是否有报错截图？

**Comment by sv3nbeast** [comment]
windows系统
目标 10.71.29.1，vpn连接才能ping通的段，设置网卡为无线网卡，我用的无线
![1](https://user-images.githubusercontent.com/55974091/68559961-ebb0ae00-0479-11ea-8c46-052d6cbbd965.png)
![2](https://user-images.githubusercontent.com/55974091/68560003-1dc21000-047a-11ea-9362-d70667eafd3e.png)
![3](https://user-images.githubusercontent.com/55974091/68560017-27e40e80-047a-11ea-829d-42b46a8fa2b6.png)

**Comment by sv3nbeast** [comment]
![4](https://user-images.githubusercontent.com/55974091/68560080-6a0d5000-047a-11ea-974b-d17d01625024.png)
![5](https://user-images.githubusercontent.com/55974091/68560092-785b6c00-047a-11ea-9fed-5247a1d375c5.png)

网卡换成vpn   ip的网卡同样是这样，不过偶尔可以用无线网卡扫描成功，所以只能用socks，不过感觉不是太准确

**Comment by gobysec** [comment]
后端引擎1.7.160版本修复。
