### ISSUE TITLE
漏洞验证异常

### ISSUE THREAD

**Issue by Baikeryoyo** [gobysec/Goby#221]
漏洞名称：DS_Store_found
问题出现情况：
批量扫描IP扫到该漏洞，单独扫IP扫不到漏洞的情况
我有专门指定IP，指定端口，指定漏洞建立了扫描，未扫到该漏洞
此漏洞经过手工验证，确定存在
经过多次扫描验证，确有此问题，暂不确定是否只有此漏洞出现该问题

**Comment by gobysec** [comment]
收到问题，我们后续会测试下，感谢您的支持与反馈~
