### ISSUE TITLE
已经扫描到了但是显示的时候存在漏报

### ISSUE THREAD

**Issue by lovelyjuice** [gobysec/Goby#222]
已经扫描到了该端口
![image](https://user-images.githubusercontent.com/20644461/116643264-36422500-a9a3-11eb-8506-6e74b6bbebab.png)

但是在web检测界面中并没有显示出来，不仅仅是title没有显示，甚至连端口都没有显示。即便目标web服务存在多次js重定向导致无法准确获取title，但至少把ip和端口列出来吧。web检测界面甚至连180.*.*.88这台服务器都看不到...
![image](https://user-images.githubusercontent.com/20644461/116643323-6689c380-a9a3-11eb-851a-75c28096c80b.png)

PS: 可以把扫描报告私发给你们

**Comment by gobysec** [comment]
感谢您的反馈，可以将报告发送到gobybot的微信号，或者发送到gobysec@gmail.com，方便我们排查。
