### ISSUE TITLE
goby bug 反馈

### ISSUE THREAD

**Issue by orleven** [gobysec/Goby#227]
20210507 官网最新版
远程模式下：
Linux：./goby-cmd-linux -apiauth admin:xxxx -mode api -bind 0.0.0.0:65000
Mac：添加服务器

1. 关闭后/或修改密码重启后， Mac 出现弹窗，类似连接error， 然后ui 卡死。
2. Linux的任务在扫描中，如果关闭Mac，重启。 扫描页，仍然是继续菜单。   任务无法关闭或停止，出现提示， alreadly has active scanner running.
3.  Linux的任务在扫描中，如果关闭Mac，重启。 点击扫描历史任务，其数据并不会实时同步给扫描页面的数据展示处。

**Comment by gobysec** [comment]
感谢您的反馈，如果没有理解错您的意思的话，第一条已经在v1.8.268 beta中修复了，现在在`连接错误`出现后提供了更改服务器的选项

![image](https://user-images.githubusercontent.com/50955360/117529813-6ecda880-b00c-11eb-96c4-a8608f00823f.png)

第二条，这个问题属于已知问题，正在考虑怎么提示用户，或者有更好的解决方案
第三条，通过查看历史任务可以发现，进度条是在增加的，日后可以做一些显示上的优化
