### ISSUE TITLE
完善建议：给输出的日志增加一个清空日志的按钮功能

### ISSUE THREAD

**Issue by Hatcat123** [gobysec/Goby#229]
使用场景，可能一次项目中多次使用goby。每次日志产生的太多，目前不能够清空日志。

**Comment by gobysec** [comment]
当前重启 Goby 会自动清空目录 date/logs 下日志，Beta1.8.268 版本 log 功能每重新开启扫描都会清空上一段日志。感谢您的支持与反馈~
