### ISSUE TITLE
error query

### ISSUE THREAD

**Issue by ufohacker** [gobysec/Goby#23]
windows版本，扫描完之后点击资产和漏洞提示 error query ，界面不显示数据。。

**Comment by cliekkas** [comment]
> windows版本，扫描完之后点击资产和漏洞提示 error query ，界面不显示数据。
测试版本，报错比较暴力，最新版本貌似稳定很多了

**Comment by gobysec** [comment]
这个问题已在最新版解决，请下载最新版体验，如若复现，请重新提单给我们。
