### ISSUE TITLE
扫描疑似卡死

### ISSUE THREAD

**Issue by CtrlAltDelet** [gobysec/Goby#232]
看了log发现扫描到69%之后一直显示这样
试了多次均是一样
2021/05/28 16:24:51 127.0.0.1:58229 POST /api/v1/getProgress

2021/05/28 16:24:54 127.0.0.1:58331 POST /api/v1/getProgress

2021/05/28 16:24:57 127.0.0.1:58432 POST /api/v1/getProgress

2021/05/28 16:25:00 127.0.0.1:58540 POST /api/v1/getProgress

2021/05/28 16:25:03 127.0.0.1:58651 POST /api/v1/getProgress

2021/05/28 16:25:06 127.0.0.1:58754 POST /api/v1/getProgress

2021/05/28 16:25:09 127.0.0.1:58863 POST /api/v1/getProgress

2021/05/28 16:25:12 127.0.0.1:58968 POST /api/v1/getProgress

2021/05/28 16:25:15 127.0.0.1:59073 POST /api/v1/getProgress

2021/05/28 16:25:18 127.0.0.1:59172 POST /api/v1/getProgress

2021/05/28 16:25:21 127.0.0.1:59276 POST /api/v1/getProgress

2021/05/28 16:25:24 127.0.0.1:59381 POST /api/v1/getProgress

2021/05/28 16:25:27 127.0.0.1:59482 POST /api/v1/getProgress

2021/05/28 16:25:30 127.0.0.1:59590 POST /api/v1/getProgress

......
18275 exp版本
windows20h2
线程80

**Comment by CtrlAltDelet** [comment]
![image](https://user-images.githubusercontent.com/38282439/119954671-d060b180-bfd1-11eb-90a5-83f21096e1de.png)
配置如图

**Comment by gobysec** [comment]
日志有时间在跑就是正常在扫哈，和目标大，线程低，网络问题都有关系。建议可以禁用漏洞，就会加快扫描，再二次检测漏洞

**Comment by CtrlAltDelet** [comment]
已经禁用漏洞了...
