### ISSUE TITLE
Ubuntu Goby扫描服务中断

### ISSUE THREAD

**Issue by runningCsnail** [gobysec/Goby#234]
Ubuntu Goby, 第一次使用时，服务中断，关闭弹窗后自动重启服务，依然中断。![图片](https://user-images.githubusercontent.com/39901127/120094365-87843680-c152-11eb-8191-371fc3525573.png)
![图片](https://user-images.githubusercontent.com/39901127/120094340-615e9680-c152-11eb-873d-f960c563b7ad.png)
![图片](https://user-images.githubusercontent.com/39901127/120094358-76d3c080-c152-11eb-8118-75b974d9e2a5.png)

![图片](https://user-images.githubusercontent.com/39901127/120094365-87843680-c152-11eb-8191-371fc3525573.png)
![图片](https://user-images.githubusercontent.com/39901127/120094383-97037f80-c152-11eb-8dcf-217f945da54c.png)

**Comment by gobysec** [comment]
这边看到您的报错是没有权限哈 请提升至root权限运行
