### ISSUE TITLE
web finder页面在资产过多情况下有卡顿情况

### ISSUE THREAD

**Issue by mrjesen** [gobysec/Goby#235]
1. 提供使用的版本及系统
Win10 x64  Goby内测版（截至5月30日最新版）
2. 提供需要应用的场景
web finder页面在资产过多情况下有卡顿情况
感觉现在是把所有数据都取出来一起渲染
3. 提供已考虑过的替代解决方案
分段取出数据后渲染

**Comment by gobysec** [comment]
收到，很详细了，我们尽快优化，感谢您的支持与反馈~
