### ISSUE TITLE
组件名称和具体端口无关联

### ISSUE THREAD

**Issue by ldcr002** [gobysec/Goby#237]
![image](https://user-images.githubusercontent.com/19703196/121121224-c2245800-c851-11eb-8073-414b41701f11.png)

问题：如图这种情况，根本看不出具体哪个端口运行的服务是Struts2组件。
建议：在具体端口的详细信息部分，关联该端口相关的组件

**Comment by gobysec** [comment]
收到反馈，排期优化，感谢您的支持
