### ISSUE TITLE
在使用API模式出现panic错误，错误如图

### ISSUE THREAD

**Issue by foxhack** [gobysec/Goby#24]
linux 环境 centos7，64位

![图片](https://user-images.githubusercontent.com/16910405/69945963-a0903500-1525-11ea-803c-ae8c93c36575.png)

**Comment by T4di5** [comment]
> linux 环境 centos7，64位
> 
> ![图片](https://user-images.githubusercontent.com/16910405/69945963-a0903500-1525-11ea-803c-ae8c93c36575.png)

老哥，你api模式咋用的啊？我找使用文档都没找到

**Comment by foxhack** [comment]
文档里面有描述，这个问题我已经知道，centos7下运行在pcap模式会有问题，socket的话就没有任何任务，我猜应该和libpcap有关系，centos8下运行两种模式都没有问题

文档描述如下
![图片](https://user-images.githubusercontent.com/16910405/71573185-88f49e00-2b1d-11ea-97cc-f6c9134f9d73.png)

**Comment by T4di5** [comment]
> 文档里面有描述，这个问题我已经知道，centos7下运行在pcap模式会有问题，socket的话就没有任何任务，我猜应该和libpcap有关系，centos8下运行两种模式都没有问题
> 
> 文档描述如下
> ![图片](https://user-images.githubusercontent.com/16910405/71573185-88f49e00-2b1d-11ea-97cc-f6c9134f9d73.png)

老铁，还是没证明白你api模式咋用的，绑定ip和port后http访问嘛？restful api 结构是啥啊？

**Comment by LubyRuffy** [comment]
> linux 环境 centos7，64位
> 
> ![图片](https://user-images.githubusercontent.com/16910405/69945963-a0903500-1525-11ea-803c-ae8c93c36575.png)

看错误提示是内存资源满了。
