### ISSUE TITLE
device name is not match

### ISSUE THREAD

**Issue by tempulccsec** [gobysec/Goby#244]
![11](https://user-images.githubusercontent.com/25562208/124349554-31f3eb80-dc22-11eb-8bee-67e8fb1a4cb5.JPG)

2021/07/03 16:56:56 Version: v1.31.301+beta

2021/07/03 16:56:56 API Server listen at 127.0.0.1:8361

2021/07/03 16:56:57 127.0.0.1:33733 GET /api/v1/version

2021/07/03 16:56:57 127.0.0.1:33734 GET /api/v1/live

2021/07/03 16:56:57 127.0.0.1:33735 GET /api/v1/getEnvi?

2021/07/03 16:56:57 127.0.0.1:33736 GET /api/v1/tasks

2021/07/03 16:57:00 [DEBUG] device name is not match: \Device\NPF_{DC99E80D-5B6D-4E89-8D25-B2BF689B534F} != \Device\NPF_{3C63ABBE-565D-484B-B2B9-6CC173A879E1}

2021/07/03 16:57:00 [DEBUG] device name is not match: \Device\NPF_{3CD0CB4D-300D-4CAD-ABAE-2E89373F858B} != \Device\NPF_{3C63ABBE-565D-484B-B2B9-6CC173A879E1}

2021/07/03 16:57:00 [DEBUG] device name is not match: \Device\NPF_{F0A7F541-6C96-4D8B-877F-6ACD7D892C0D} != \Device\NPF_{3C63ABBE-565D-484B-B2B9-6CC173A879E1}

2021/07/03 16:57:00 [DEBUG] device name is not match: \Device\NPF_{73C17892-1846-4698-93EA-095DC79BE7DB} != \Device\NPF_{3C63ABBE-565D-484B-B2B9-6CC173A879E1}

2021/07/03 16:57:00 [DEBUG] device name is not match: \Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA} != \Device\NPF_{3C63ABBE-565D-484B-B2B9-6CC173A879E1}

2021/07/03 16:57:00 [DEBUG] device name is not match: \Device\NPF_NdisWanIp != \Device\NPF_{3C63ABBE-565D-484B-B2B9-6CC173A879E1}

2021/07/03 16:57:00 [DEBUG] device name is not match: \Device\NPF_NdisWanBh != \Device\NPF_{3C63ABBE-565D-484B-B2B9-6CC173A879E1}

2021/07/03 16:57:00 [DEBUG] getGatewayMac: \Device\NPF_{3C63ABBE-565D-484B-B2B9-6CC173A879E1} 0.0.0.0

2021/07/03 16:57:01 find router mac is e4:95:6e:4c:53:d9

2021/07/03 16:57:23 [DEBUG] fetch mac address: \Device\NPF_{3C63ABBE-565D-484B-B2B9-6CC173A879E1} e4:95:6e:4c:53:d9

**Comment by gobysec** [comment]
提示此报错分为丢包率过高和后台崩溃，目前没有看到您日志里有报错，关掉弹窗就会自动重连，若是还有其他问题，您也可以联系微信号：gobyteam
