### ISSUE TITLE
CentOS Linux release 7.2.1511 (Core) 运行报错

### ISSUE THREAD

**Issue by wangyan-samuel** [gobysec/Goby#248]
./goby: /lib64/libdbus-1.so.3: no version information available (required by ./goby)
/data/goby-linux-x64-1.8.279/goby: /lib64/libdbus-1.so.3: no version information available (required by /data/goby-linux-x64-1.8.279/goby)

**Comment by gobysec** [comment]
没太清楚您的问题，可以详情带截图描述一下吗？

**Comment by wangyan-samuel** [comment]
您好，我下载了linux的版本   我的虚机是CentOS Linux release 7.4.1708 (Core)
解压后运行./goby  
[/data/goby-linux-x64-1.8.293]./goby
./goby: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
