### ISSUE TITLE
扫描记录汇总功能

### ISSUE THREAD

**Issue by a639612262010** [gobysec/Goby#250]
![da98a05197b9a9851b5f81b4a6a5110](https://user-images.githubusercontent.com/61104521/127082575-7ed4fb5c-3dc8-4a25-838c-ca404fca86f9.png)
![b504c387c56bbfd26eb75e27ded711a](https://user-images.githubusercontent.com/61104521/127082591-2cc00bb4-4a56-4531-9198-ff5acf10fb5d.png)
集团资产较多，需要分多个B段进行扫描，且需要多人协作进行扫描。需要增加一个扫描记录汇总功能，满足资产较多企业进行最终的资产梳理。
谢谢采纳，祝goby越来越强。

**Comment by gobysec** [comment]
已收到您的反馈，不定期更新进展，感谢您对Goby的支持~
