### ISSUE TITLE
没设置代理，但是报代理错误

### ISSUE THREAD

**Issue by superboy-zjc** [gobysec/Goby#255]
![image](https://user-images.githubusercontent.com/60600792/128288068-b203c249-a927-4a91-a98e-f5eae74680a0.png)

![image](https://user-images.githubusercontent.com/60600792/128288045-645c831c-4ea9-4832-a34f-f9abbdc8ea97.png)
 
请问如何解决呢

**Comment by gobysec** [comment]
您好，此报错请问是否影响正常使用呢？

**Comment by gobysec** [comment]
您好，此报错请问是否影响正常扫描使用呢？
其次，提示报错的此网络是否可以访问插件列表及Goby官网？
