### ISSUE TITLE
【建议】PHP/8.1.0-dev 展示完整版本

### ISSUE THREAD

**Issue by foolb** [gobysec/Goby#256]
1、kali 系统，goby v1.8.295 beta
2、goby 扫描出 php 8.1.0 dev 版本时资产里只会标识 php 8.1.0。如下图：
<img width="854" alt="image" src="https://user-images.githubusercontent.com/26821939/129205496-0856bca7-0429-4dc2-8c53-4c32c4310c54.png">
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/26821939/129205674-6dcd58ae-99a0-469e-96e7-bb43323b910f.png">

3、展示完整版本
PHP/8.1.0-dev

**Comment by gobysec** [comment]
收到，不定期更新进展，感谢您的反馈与支持~
