### ISSUE TITLE
Mac下为什么需要那么多权限？

### ISSUE THREAD

**Issue by samshuai** [gobysec/Goby#26]
通讯录，照片这些权限都要。

**Comment by cliekkas** [comment]
> 通讯录，照片这些权限都要。

不需要的，直接拒绝就好

**Comment by samshuai** [comment]
@cliekkas 拒绝了，最新版，在mac上还是不能运行，一直停留在环境检查那个界面上。

**Comment by gobysec** [comment]
> @cliekkas 拒绝了，最新版，在mac上还是不能运行，一直停留在环境检查那个界面上。
1. 是否把文件访问的权限也禁止掉了呢？2. 您是否有设置访问网卡权限（goby是基于网络扫描的，请预先赋予它访问网卡的权限）？3. 尝试把goby文件移动到除应用程序以外的目录。希望能帮到您。

**Comment by gobysec** [comment]
这个问题在最新版1.6.138已经解决了。后续不会在提示。
