### ISSUE TITLE
不断循环请求

### ISSUE THREAD

**Issue by akatsukiello** [gobysec/Goby#264]
- 版本：1.8.298
- 现象：目标已返回404，无限循环请求/druid/index.html不会停止，任务无法完成
- 数据包：

> GET /druid/index.html HTTP/1.1
Host: test.ceshi.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
Cookie: rememberMe=xxxxxxxxxxxxxxxxxxxxxx
Accept-Encoding: gzip

>HTTP/1.1 404 
Server: nginx
Date: Thu, 09 Sep 2021 00:37:59 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
hostname: basis-test

>{"timestamp":"2021-09-09T00:37:59.598+0000","status":404,"error":"Not Found","message":"No message available","path":"/druid/index.html"}

- 任务配置
<img width="390" alt="图片" src="https://user-images.githubusercontent.com/5812175/132604799-f3f2f369-a08b-44c0-9d0f-ad2edb98818d.png">

- 抓包结果
![图片](https://user-images.githubusercontent.com/5812175/132604509-50988113-edde-45e1-addb-1d478245c564.png)
![图片](https://user-images.githubusercontent.com/5812175/132604556-3ee123b7-685e-4240-b19d-e30411745044.png)

**Comment by xiaoheihei1107** [comment]
bug未复现成功，请添加gobybot微信(gobyteam)详细说明
