### ISSUE TITLE
有无支持Apple Silicon（ARM芯片的MAC）或者ARM版Linux的计划。

### ISSUE THREAD

**Issue by woOzZ2** [gobysec/Goby#269]
RT
转译的Goby扫起来有时候会一直扫什么都没有

**Comment by gobysec** [comment]
m1版本的mac可以直接用mac版本的goby，针对于未扫出来结果可能存在的情况：
1. 扫描进度未完成，进度条卡在某一处，可能是正在扫描漏洞，时间比较久；
2. 扫描进度卡在0%，未扫描出结果，可能是目标过大，且开启的爬虫或网站截图，导致性能降低；
3. 扫描进度完成，未扫出结果。
以上具体情况可以加我微信：gobyteam，发送日志具体分析

ARM版本的Linux需求已收到，不定期更新进展，感谢您的反馈与支持~
