### ISSUE TITLE
等保能否用这个工具

### ISSUE THREAD

**Issue by IceRainow** [gobysec/Goby#27]
https://www.mps.gov.cn/n2254314/n2254409/n2254443/n2254451/c4113558/content.html

能否向经公安部计算机管理监察部门批准的检测机构申请安全功能检测
等保要求必须用国产的安全工具

**Comment by gobysec** [comment]
> https://www.mps.gov.cn/n2254314/n2254409/n2254443/n2254451/c4113558/content.html
> 
> 能否向经公安部计算机管理监察部门批准的检测机构申请安全功能检测
> 等保要求必须用国产的安全工具

暂时没有考虑，后续若有会告知大家。
