### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by kingz40o** [gobysec/Goby#272]
mac 10.13.6
Beta (1.8.302) 
![image](https://user-images.githubusercontent.com/19370924/142171190-fbf4e984-264f-4e2c-aeec-0bf151058e8a.png)
![image](https://user-images.githubusercontent.com/19370924/142171255-79c4e487-6aad-40b2-bf82-657d823cf2a7.png)

**Comment by gobysec** [comment]
详细的日志信息可能您需要发送给我，微信：gobyteam
