### ISSUE TITLE
端口指纹扫描优化

### ISSUE THREAD

**Issue by r00tSe7en** [gobysec/Goby#274]
渗透过程中为了追求端口扫描速度，习惯使用naabu去扫描开放端口，然后他的扫描结果是这种格式的
ip:port
ip:port
ip:port
希望goby可以自动解析，去扫描指定地址的指定端口的指纹

如果还是用原来的方式让ip和端口去轮询的话，会发一些无用的包，感觉效率比较低

**Comment by gobysec** [comment]
已实现此功能，请升级至Beta1.9.325 感谢您的反馈与支持
