### ISSUE TITLE
一直重启

### ISSUE THREAD

**Issue by githack2016** [gobysec/Goby#276]
![截图_20211228132459](https://user-images.githubusercontent.com/19440170/147531473-587fb734-2e78-4899-a49f-b79f7e493fa1.png)

**Comment by gobysec** [comment]
这是我们在前端做的处理，证明您在一启动就是有某些原因没有设置正确，而不再是以往开始扫描后再提示
请您将全部日志发给微信：gobyteam  我们根据日志判断您是由什么原因导致，方便我们后续以引导性话语对您展示弹框。
