### ISSUE TITLE
log4j系列一个都扫不出来

### ISSUE THREAD

**Issue by githack2016** [gobysec/Goby#277]
红版更新了，log4j一个都扫不出。

**Comment by gobysec** [comment]
1.谷歌浏览器版本更新，因为爬虫需要用到headless chrome，Headless Chrome 是Chrome 浏览器的无界面形态，可以在不打开浏览器的前提下，使用所有Chrome 支持的特性运行你的程序。 相比于现代浏览器，Headless Chrome 更加方便测试web 应用，获得网站的截图，做爬虫抓取信息等
2.开启爬虫
3.设置goby提供的godserver.tk，因为该漏洞是通过jndi注入触发的，godserver上搭建了一个dnslog服务，DNSLOG是一种回显机制，常用于在某些漏洞无法回显但可以发起DNS请求的情况下，利用此方式外带数据，以解决某些漏洞由于无回显而难以检测的问题。
