### ISSUE TITLE
请问能否支持域名+端口的资产导出？

### ISSUE THREAD

**Issue by kesonn** [gobysec/Goby#28]
请问能否支持域名+端口的资产导出？目前只有IP+端口导出

**Comment by cliekkas** [comment]
> 请问能否支持域名+端口的资产导出？目前只有IP+端口导出

应该可以安排的

**Comment by gobysec** [comment]
> 请问能否支持域名+端口的资产导出？目前只有IP+端口导出

GOBY最新版v1.6.116已支持IP+端口+协议+应用的导出
https://gobies.org/updates.html
