### ISSUE TITLE
异常退出

### ISSUE THREAD

**Issue by Zther0** [gobysec/Goby#280]
1.开启两个不同版本的goby，关闭其中一个，另一个也会退出
2.开启两个不同版本的goby，一个执行扫描，另一个无法再执行扫描

两个版本具体如图
![image](https://user-images.githubusercontent.com/19760820/150751689-c02636b9-fbf9-482c-9e52-0683ccaf4f86.png)
![image](https://user-images.githubusercontent.com/19760820/150751813-514a156f-f7e4-4dfa-b7ce-2ef9debaad56.png)

**Comment by gobysec** [comment]
Goby只能开启一个并进行扫描
