### ISSUE TITLE
Information on main page not refresh in realtime

### ISSUE THREAD

**Issue by ghost** [gobysec/Goby#284]
All these data can be refreshed only if i will click on ip, or assets, or other elements, when i come back, data will be refreshed, but this is not correct, need to be refreshed on each 5 seconds, on example.
![image](https://user-images.githubusercontent.com/20506433/154670260-edb2e99b-30e0-4717-a308-4377a13bf77e.png)

**Comment by connected201** [comment]
upd. like on small range of IP, all working fine, for large amount of scanned ip, not working correctly!
