### ISSUE TITLE
关于适配苹果m1的疑惑

### ISSUE THREAD

**Issue by changly** [gobysec/Goby#285]
我看软件是采用electron来做的 为什么不提供一个可以适配苹果m1版本的呢？

**Comment by gobysec** [comment]
您好，Goby是支持m1芯片的，不知您为何会提出此疑问，可详情加微信聊：gobyteam

**Comment by gobysec** [comment]
此问题已修复，已在最新版本中发布，若紧急情况可联系微信：gobyteam协助您解决！感谢您的反馈与支持～
