### ISSUE TITLE
关于Goby指纹识别时反馈的 fid 参数，后期是否支持作为编写Exp时 GobyQuery 字段的元素？

### ISSUE THREAD

**Issue by yad1d1** [gobysec/Goby#288]
![image](https://user-images.githubusercontent.com/35857939/157022724-70b7c7c1-d9f3-45b8-8491-1fb5b8f1e72b.png)
目前发现 fid 参数还不支持加入GobyQuery，后期是否考虑支持？

**Comment by gobysec** [comment]
已收到您的反馈，后期可能考虑，不定期更新进展，感谢您的支持与喜爱~
