### ISSUE TITLE
关于开发版

### ISSUE THREAD

**Issue by adeljck** [gobysec/Goby#289]
请问开发版还会更新吗？我看最新版的开发版部分goby的api不支持

**Comment by yad1d1** [comment]
是指哪些api

**Comment by gobysec** [comment]
目前开发功能直接在插件市场下载debug插件即可，请问是否还有其他需求？

**Comment by adeljck** [comment]
> 目前开发功能直接在插件市场下载debug插件即可，请问是否还有其他需求？
没有疑问了，谢谢

**Comment by adeljck** [comment]
> 是指哪些api
高于1.6的都用不了qwq，不过现在这都不重要了，直接Debug插件就解决了
