### ISSUE TITLE
Goby1.4.76beta版存在一个问题，当本地物理机开启VMware虚拟机，虚拟机网络设置桥接模式时，本地物理机启动goby提示报错，无法识别网络，无法正常工作。

### ISSUE THREAD

**Issue by l1TTss** [gobysec/Goby#29]
Goby1.4.76beta版存在一个问题，当本地物理机开启VMware虚拟机，虚拟机网络设置桥接模式时，本地物理机启动goby提示报错，无法识别网络，无法正常工作。基于这个问题本人有以下看法：
Goby应该需要调用本地系统安装的npcap抓包组件，所以本人建议Goby开发人员可以跟开源的npcap开发人员沟通，是否是他们那边抓包组件npcap的问题，npcap开源项目组有一个中国人博士，建议可以反馈一起解决，goby和npcap都这么好的工具，你们都真的辛苦了，谢谢。
![goby在开启虚拟机网桥模式下报错](https://user-images.githubusercontent.com/60909700/74581900-1027a380-4ff0-11ea-8fc3-75206aceb497.png)

**Comment by cliekkas** [comment]
非常感谢反馈，我们尽快解决

**Comment by gobysec** [comment]
> Goby1.4.76beta版存在一个问题，当本地物理机开启VMware虚拟机，虚拟机网络设置桥接模式时，本地物理机启动goby提示报错，无法识别网络，无法正常工作。基于这个问题本人有以下看法：
> Goby应该需要调用本地系统安装的npcap抓包组件，所以本人建议Goby开发人员可以跟开源的npcap开发人员沟通，是否是他们那边抓包组件npcap的问题，npcap开源项目组有一个中国人博士，建议可以反馈一起解决，goby和npcap都这么好的工具，你们都真的辛苦了，谢谢。
> ![goby在开启虚拟机网桥模式下报错](https://user-images.githubusercontent.com/60909700/74581900-1027a380-4ff0-11ea-8fc3-75206aceb497.png)

表哥的VM是wins还是linux版本呢？

**Comment by l1TTss** [comment]
> > Goby1.4.76beta版存在一个问题，当本地物理机开启VMware虚拟机，虚拟机网络设置桥接模式时，本地物理机启动goby提示报错，无法识别网络，无法正常工作。基于这个问题本人有以下看法：
> > Goby应该需要调用本地系统安装的npcap抓包组件，所以本人建议Goby开发人员可以跟开源的npcap开发人员沟通，是否是他们那边抓包组件npcap的问题，npcap开源项目组有一个中国人博士，建议可以反馈一起解决，goby和npcap都这么好的工具，你们都真的辛苦了，谢谢。
> > ![goby在开启虚拟机网桥模式下报错](https://user-images.githubusercontent.com/60909700/74581900-1027a380-4ff0-11ea-8fc3-75206aceb497.png)
> 
> 表哥的VM是wins还是linux版本呢？

你好，不管VM是wins还是linux系统只要虚拟机开启了桥接网络的模式都会有这个问题的，我都测试过了的。

**Comment by gobysec** [comment]
方便把日志发过来看下吗？data/logs

l1TTss <notifications@github.com> 于2020年3月18日周三 下午6:16写道：

**Comment by l1TTss** [comment]
> 方便把日志发过来看下吗？data/logs l1TTss <notifications@github.com> 于2020年3月18日周三 下午6:16写道：
> […](#)

好的，到时我测试下，将日志发到这里。也希望你们开发人员可以自行测试，谢谢。

**Comment by gobysec** [comment]
> > 方便把日志发过来看下吗？data/logs l1TTss [notifications@github.com](mailto:notifications@github.com) 于2020年3月18日周三 下午6:16写道：
> > […](#)
> 
> 好的，到时我测试下，将日志发到这里。也希望你们开发人员可以自行测试，谢谢。

好的，辛苦你。因为我们在wins/linux、MacOS上都没有把它复现出来。我们推测可能是你这边没有用root权限运行Goby程序，所以想看下你的完整日志做判断。

**Comment by l1TTss** [comment]
> > > 方便把日志发过来看下吗？data/logs l1TTss [notifications@github.com](mailto:notifications@github.com) 于2020年3月18日周三 下午6:16写道：
> > > […](#)
> > 
> > 
> > 好的，到时我测试下，将日志发到这里。也希望你们开发人员可以自行测试，谢谢。
> 
> 好的，辛苦你。因为我们在wins/linux、MacOS上都没有把它复现出来。我们推测可能是你这边没有用root权限运行Goby程序，所以想看下你的完整日志做判断。

你好，我用的goby是Windows版本的，我确实没有通过管理员权限启动它的，我到时，用管理员权限启动试试看，谢谢了。

**Comment by gobysec** [comment]
> > > > 方便把日志发过来看下吗？data/logs l1TTss [notifications@github.com](mailto:notifications@github.com) 于2020年3月18日周三 下午6:16写道：
> > > > […](#)
> > > 
> > > 
> > > 好的，到时我测试下，将日志发到这里。也希望你们开发人员可以自行测试，谢谢。
> > 
> > 
> > 好的，辛苦你。因为我们在wins/linux、MacOS上都没有把它复现出来。我们推测可能是你这边没有用root权限运行Goby程序，所以想看下你的完整日志做判断。
> 
> 你好，我用的goby是Windows版本的，我确实没有通过管理员权限启动它的，我到时，用管理员权限启动试试看，谢谢了。

您客气了。如果root权限还是不行，您重新安装npcap试试。如果界面提示您去设置界面选择网卡，您就选择当前环境的网卡。

**Comment by l1TTss** [comment]
> > > > > 方便把日志发过来看下吗？data/logs l1TTss [notifications@github.com](mailto:notifications@github.com) 于2020年3月18日周三 下午6:16写道：
> > > > > […](#)
> > > > 
> > > > 
> > > > 好的，到时我测试下，将日志发到这里。也希望你们开发人员可以自行测试，谢谢。
> > > 
> > > 
> > > 好的，辛苦你。因为我们在wins/linux、MacOS上都没有把它复现出来。我们推测可能是你这边没有用root权限运行Goby程序，所以想看下你的完整日志做判断。
> > 
> > 
> > 你好，我用的goby是Windows版本的，我确实没有通过管理员权限启动它的，我到时，用管理员权限启动试试看，谢谢了。
> 
> 您客气了。如果root权限还是不行，您重新安装npcap试试。如果界面提示您去设置界面选择网卡，您就选择当前环境的网卡。

您好，我是用Windows10 64位的goby 1.6.104beta版，重装了npcap 0.9989版本，暂时没有发现这个问题了，谢谢。
