### ISSUE TITLE
linux客户端部署出错

### ISSUE THREAD

**Issue by Sshad0wsec** [gobysec/Goby#291]
安装好所有库后运行goby，弹出了goby的GUI，linux端提醒：
root@vps:~/goby# ./goby -apiauth user:pass -mode api -bind 0.0.0.0:8361
kill: (14890): No such process
windows客户端连接提示：service error
我的服务器是Debian 10

**Comment by gobysec** [comment]
linux客户端
有图形化界面：直接双击运行Goby
无图形化：运行golib目录下的goby-cmd-linux
远程连接教程：https://cn.gobies.org/features.html#CS%E6%9E%B6%E6%9E%84
可能是命令输入的不正确，可以看文档命令：https://cn.gobies.org/faq.html#%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%90%AF%E5%8A%A8Goby%E6%8A%A5%E9%94%99
如还不能解决，可以加微信：gobyteam

感谢您的反馈与支持~
