### ISSUE TITLE
goby

### ISSUE THREAD

**Issue by exam-jcfxu** [gobysec/Goby#294]

**Comment by gobysec** [comment]
Even if you no description provided,  goby also feels your full heart.

**Comment by exam-jcfxu** [comment]
How to use the red team version of goby and apply



| |
蒋朝帆
|
|
***@***.***
|
On 4/21/2022 ***@***.***> wrote：

Even if you no description provided, goby also feels your full heart.

**Comment by gobysec** [comment]
contact wechat: gobyteam
