### ISSUE TITLE
禁ping的公网无法扫描

### ISSUE THREAD

**Issue by BJlearn** [gobysec/Goby#298]
在扫描公网地址的时候，如果该公网地址屏蔽了imcp协议（即ping不通，但是80等端口是通的），则直接判断该地址不存在导致无法扫描。
建议增加“不进行存活探测”选项，即不进行ping扫描，直接进行端口扫描。

**Comment by gobysec** [comment]
Goby默认是不禁Ping 的，若开启可以在 设置→高级设置 开启，具体问题可以联系微信：gobyteam ，感谢您的反馈
