### ISSUE TITLE
 运行时错误无效内存地址或零指针取消引用  runtime error invalid memory address or nil pointer dereference  

### ISSUE THREAD

**Issue by admin-set** [gobysec/Goby#299]
![image](https://user-images.githubusercontent.com/63496176/171145580-8752a5dd-c28b-4603-b544-eea7f2d865fe.png)
 运行是出现
 运行时错误无效内存地址或零指针取消引用  runtime error invalid memory address or nil pointer dereference   
将程序删除后在下载安装依旧存储改问题 系统版本win11 
namp和npcap 也删除重装过依旧如此。

**Comment by gobysec** [comment]
您好，此问题为已知问题，已解决，下个版本更新，版本更新关注公众号：gobysec 
目前解决办法是需要选择正确网卡ip，重装Npcap的话是需要安装最新版，且安装时勾选管理员权限
如若还未解决，请联系微信：gobyteam
