### ISSUE TITLE
希望goby后续更新能支持资产扫描和漏洞扫描结果导出Excel或cvs表格的文件

### ISSUE THREAD

**Issue by l1TTss** [gobysec/Goby#30]
开发者你们好：
        看着goby一天天变好，越更新功能越实用，心里很高兴，也从心里感激你们对安全事业做出的贡献，你们辛苦了，希望goby后续更新能支持资产扫描和漏洞扫描结果导出Excel或cvs表格的文件，便于使用者统计整理扫描结果，谢谢。

**Comment by patxiey** [comment]
非常感谢开发者们的辛勤付出

**Comment by gobysec** [comment]
感谢您的反馈，后面我们将支持导出excel/cvs格式

**Comment by gobysec** [comment]
Goby最新版 Beta1.6.116已支持资产姐漏洞excel导出。扫描完成后点击报告，通过报告，导出报告PDF文件、资产excel文件、漏洞excel文件。
