### ISSUE TITLE
gobydata重新导入后协议变成unknow

### ISSUE THREAD

**Issue by Jack-ban** [gobysec/Goby#300]
## 目前使用版本
goby-win-x64-1.9.325

## 需求
导出的gobydata数据能够包含识别的协议信息。目前gobydata重新导入后，所有协议识别结果都是unknow。
## 目前
看了一下导出gobydata之后，还有asset资产和vul漏洞两个统计表。
不太明白为什么不把这些数据包含在gobydata里面。比如nessus的db数据就是包含了所有扫描结果数据的。

**Comment by gobysec** [comment]
您好，gobydata是包含所有扫描结果的，请问您导入的版本是哪个版本呢？可以添加下微信：gobyteam

**Comment by Jack-ban** [comment]
## goby使用模式
远程centos7上，goby以命令行模式启动服务，本地goby远程链接上服务。

## 本地goby版本
goby1.9.325

## 远程goby版本
goby1.8.279

## 远程goby服务启动命令
```bash
nohup ./goby-cmd-linux -apiauth test:test -mode api -bind 0.0.0.0:8635 > test.log 2>&1 &
```
## 操作

1. 本地客户端切换服务器，链接上远程服务端后配置任务等待完成，然后导出gobydata。
2. 本地客户端切换回内置的goby服务器`127.0.0.1`，导入gobydata。

## 结果
操作1，协议识别正常。
![image](https://user-images.githubusercontent.com/17838717/172751631-b77f22e2-5fc8-4a32-8f37-0bd4d3da469a.png)

操作2，协议变成unknown。
![image](https://user-images.githubusercontent.com/17838717/172751685-fb273299-4f1f-4727-aebe-ebc35c2c73b1.png)

其他指纹信息正常显示。

## 推测
1. 导出版本和导入版本不一致，两者数据结构有差别，所以出现协议丢失。
2. 因为是远程链接的方式导出的gobydata，所以协议数据丢失。

个人更倾向于第二种原因。远程模式下导出的数据中，确实没有看到协议信息。
![image](https://user-images.githubusercontent.com/17838717/172752178-7e08b8b9-333c-45c1-8e1a-0478f6af7c39.png)
本地模式下导出的协议信息正常
![image](https://user-images.githubusercontent.com/17838717/172752352-9f002a84-4c49-4b98-865d-90d0a504ba32.png)

以上截图是之前的任务。
按照之前的使用逻辑，我又临时下了任务。基本证实了这一点。
远程导出gobydata前
![image](https://user-images.githubusercontent.com/17838717/172753676-84e801b7-3975-4448-8331-6420a3a12f1f.png)

本地导入gobydata后
![image](https://user-images.githubusercontent.com/17838717/172753568-06051a76-2354-42cf-9e7f-ff43d0b21abb.png)


## 其他
我还想了解一下，这种命令行模式的下启动的goby，怎么升级？我执行help之后没有看到升级的命令？
如果无法升级，是否我只需要备份什么文件，通过覆盖替换就可以完成升级呢？


感谢辛苦地研发，期待你们的回复。

**Comment by gobysec** [comment]
您好，非常感谢您详细描述遇到的问题。目前来看主要是您的推测1导出版本和导入版本不一致，两者数据结构有差别，所以出现协议丢失。建议可以先使用同一版本再尝试下
goby-cmd暂时无法直接进行升级，可以通过下载新的版本，将新版本的goby-cmd替换旧版本的goby-cmd即可。新的goby-cmd可以直接传到服务端。
感谢您的支持与反馈~

**Comment by gobysec** [comment]
此问题已修复，已在最新版本中发布，若紧急情况可联系微信：gobyteam协助您解决！感谢您的反馈与支持～
