### ISSUE TITLE
启动扫描报错

### ISSUE THREAD

**Issue by CharliHui** [gobysec/Goby#309]
环境：macOs12.4
版本：Beta 2.0.1
启动扫描报错信息：

Error
2022/07/01 12:25:48 Successfully raised file descriptor limit to 10240
2022/07/01 12:25:48 Version: v2.0.312+alpha
2022/07/01 12:25:49 API Server listen at 127.0.0.1:8361
2022/07/01 12:25:50 127.0.0.1:57634 GET /api/v1/live
2022/07/01 12:25:57 127.0.0.1:57665 POST /api/v1/setEnvi
2022/07/01 12:25:57 127.0.0.1:57666 GET /api/v1/getEnvi?
2022/07/01 12:25:57 127.0.0.1:57667 POST /api/v1/getTasks
2022/07/01 12:25:57 [DEBUG] get adapter of device
2022/07/01 12:25:57 [DEBUG] devices: [{en0 30 [{fe80::1c09xxxxxxxxxxx ffffffffffffffff0000000000000000 <nil> <nil>} {172.200.1.1 fffffff0  <nil>}]} {awdl0 30 [{fe80::1c09xxxxxxxxxxx ffffffffffffffff0000000000000000 <nil> <nil>}]} {llw0 30 [{ ffffffffffffffff0000000000000000 <nil> <nil>}]} {utun0 54 [{ffffffffffffffff0000000000000000 <nil> <nil>}]} {utun1 54 [{fe80::ffffffffffffffff0000000000000000 <nil> <nil>}]} {utun2 54 [{fe80:::ffffffffffffffff0000000000000000 <nil> <nil>}]} {utun3 54 [{fe80::bab ffffffffffffffff0000000000000000 <nil> <nil>}]} {utun4 54 [{fe80::8ffffffffffffffff0000000000000000 <nil> <nil>}]} {lo0 55 [{127.0.0.1 ff000000 <nil> <nil>} {::1 ffffffffffffffffffffffffffffffff <nil> <nil>} {fe ffffffffffffffff0000000000000000 <nil> <nil>} {127.9 ff000000 <nil> <nil>}]} {anpi0 38 [{feff:fffffffffffffffff0000000000000000 <nil> <nil>}]} {bridge0 38 []} {anpi1 38 [{fe80::6ffffffffffffffff0000000000000000 <nil> <nil>}]} {en1 38 []} {anpi2 38 [{fe80:: ffffffffffffffff0000000000000000 <nil> <nil>}]} {en2 38 []} {en3 38 []} {en4 38 []} {en5 38 []} {en7 38 []} {gif0 48 []} {stf0 48 []} {ap1 40 []}]
2022/07/01 12:25:57 [DEBUG] getGatewayMac: en0 0.0.0.0
2022/07/01 12:25:58 find router mac is 
2022/07/01 12:25:58 [DEBUG] fetch mac address: en0 
2022/07/01 12:25:58 [DEBUG] close pcap handler for getGatewayMac
2022/07/01 12:26:02 127.0.0.1:57690 GET /api/v1/getEnvi?field=licenseInfo
2022/07/01 12:26:16 127.0.0.1:57755 POST /api/v1/getPOCList
2022/07/01 12:26:16 [WARNING] QueryUniqHostInfo failed: no such column: f.phash icon_hash="116323821" || body="Greetings from Spring Boot!" || body="Whitelabel Error Page"
2022/07/01 12:26:21 127.0.0.1:57776 POST /api/v1/startScan
2022/07/01 12:26:21 [WARNING] change user-agent feature is not included in your current license.
2022/07/01 12:26:21 [WARNING] change deep-analysis feature is not included in your current license.
2022/07/01 12:26:21 scan 21,22,23,25,53,U:53,U:69,80,81,U:88,110,111,U:111,123,U:123,135,U:137,139,U:161,U:177,389,U:427,443,445,465,500,515,U:520,U:523,548,623,U:626,636,873,902,1080,1099,1433,U:1434,1521,U:1604,U:1645,U:1701,1883,U:1900,2049,2181,2375,2379,U:2425,3128,3306,3389,4730,U:5060,5222,U:5351,U:5353,5432,5555,5601,5672,U:5683,5900,5938,5984,6000,6379,7001,7077,8080,8081,8443,8545,8686,9000,9001,9042,9092,9100,9200,9418,9999,11211,U:11211,27017,U:33848,37777,50000,50070,61616 1
2022/07/01 12:26:21 start port scanner: totalSize: 91, rate: 100, connectionSize: 100, connectTimeout: 6s, retryTimes: 0, Random: true, Seed: 1656649581694251000, ScanOffset: 0, ScanICMP: false, CheckAliveMode: 2
2022/07/01 12:26:21 pcap version: libpcap version 1.9.1
2022/07/01 12:26:21 found device from route table for 101.
2022/07/01 12:26:21 [DEBUG] get adapter of device
2022/07/01 12:26:21 [DEBUG] devices: [{en0 30 [{fe80::1c09:xxxxxxxxxxxx ffffffffffffffff0000000000000000 <nil> <nil>} {172.20.10.7 fffffff0 172.20.10.15 <nil>}]} {awdl0 30 [{fe80::49 ffffffffffffffff0000000000000000 <nil> <nil>}]} {llw0 30 [{fe80::4 ffffffffffffffff0000000000000000 <nil> <nil>}]} {utun0 54 [{fe80::428f: ffffffffffffffff0000000000000000 <nil> <nil>}]} {utun1 54 [{fe80::ffffffffffffffff0000000000000000 <nil> <nil>}]} {utun2 54 [{fe80::ce81:b1c:bd2c:69e ffffffffffffffff0000000000000000 <nil> <nil>}]} {utun3 54 [{fe80::b6 ffffffffffffffff0000000000000000 <nil> <nil>}]} {utun4 54 [{fe80:a ffffffffffffffff0000000000000000 <nil> <nil>}]} {lo0 55 [{127. ff000000 <nil> <nil>} {::1 ffffffffffffffffffffffffffffffff <nil> <nil>} {fe80::1 ffffffffffffffff0000000000000000 <nil> <nil>} {127.94.0.1 ff000000 <nil> <nil>}]} {anpi0 38 [{fe80:: ffffffffffffffff0000000000000000 <nil> <nil>}]} {bridge0 38 []} {anpi1 38 [{fe80::6c ffffffffffffffff0000000000000000 <nil> <nil>}]} {en1 38 []} {anpi2 38 [{feffffffffffffffff0000000000000000 <nil> <nil>}]} {en2 38 []} {en3 38 []} {en4 38 []} {en5 38 []} {en7 38 []} {gif0 48 []} {stf0 48 []} {ap1 40 []}]
2022/07/01 12:26:21 [DEBUG] getGatewayMac: en0 
2022/07/01 12:26:21 find router mac is 
2022/07/01 12:26:22 127.0.0.1:57779 POST /api/v1/getProgress
2022/07/01 12:26:22 127.0.0.1:57780 POST /api/v1/getStatisticsData
2022/07/01 12:26:23 [DEBUG] fetch mac address: en0 1e:3
2022/07/01 12:26:23 [DEBUG] close pcap handler for getGatewayMac
2022/07/01 12:26:23 select adapter of to send packets: &{en0 172.200.0.1 [fe80::1c09:xxxxxxxxxxxx] {172.200.0.1 fffffff0} fffffff0 f864}
2022/07/01 12:26:23 routine-recv start
2022/07/01 12:26:23 start first round ARP
2022/07/01 12:26:23 first round ARP done
2022/07/01 12:26:23 port scanner is ready
2022/07/01 12:26:23 routine-target run out ping target pool 2
2022/07/01 12:26:23 alive range after ping2 (1): 101
2022/07/01 12:26:24 start sending packets
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] WritePacketData failed: send: Bad file descriptor
2022/07/01 12:26:24 [WARNING] Error sending packet to network device.send: Bad file descriptor

**Comment by gobysec** [comment]
您好，若您还未解决此问题，需要您联系下微信：gobyteam 咨询详情。非常抱歉影响您的使用，添加微信我会尽快为您解决
