### ISSUE TITLE
Mac将程序解压到应用程序目录下打开一直卡在欢迎界面

### ISSUE THREAD

**Issue by SewellDinG** [gobysec/Goby#31]
开发者你好，goby🐂🍺！
我遇到了如下情况：
本地环境是MacOS Catalina 10.15.2，将程序解压缩到应用程序目录，打开会一直卡在“analyzing the current enviroment”界面，goby是最新的版本goby-darwin-x64-1.6.104。
很奇怪的是，将goby文件夹移动到其他目录下，如Download，就可以打开。
我怀疑这应该是Mac的原因，想问下大家碰到过了这种情况没？

**Comment by samshuai** [comment]
遇到了一样的问题。
但是你说的放在download下能运行，我等下试试去。
如果是这种情况，个人估计大概率是权限的问题

**Comment by gobysec** [comment]
MacOS的应用程序牡蛎只识别dmg安装程序，而goby现在暂时是绿色版，所以在应用程序目录不能运行，需要放在下载或文稿等目录。
