### ISSUE TITLE
An unknown error occurs, Goby will try to restart and solve it. If the error still exists after the restart, please feed it back to us.

### ISSUE THREAD

**Issue by q861865812** [gobysec/Goby#310]
An unknown error occurs, Goby will try to restart and solve it. If the error still exists after the restart, please feed it back to us.
您好，这个工具是不是不支持arm架构？

**Comment by CharliHui** [comment]
要不试试1.9.325版本

**Comment by q861865812** [comment]
<img width="504" alt="图片" src="https://user-images.githubusercontent.com/54823655/177090864-04cf015a-3430-4d14-9f16-31760b006fb1.png">
<img width="276" alt="图片" src="https://user-images.githubusercontent.com/54823655/177090928-99929a13-92fc-4b40-a83c-4786102fba03.png">

**Comment by q861865812** [comment]
<img width="586" alt="图片" src="https://user-images.githubusercontent.com/54823655/177091002-ec195887-02c9-46c0-bff4-27443d1f6dcf.png">

**Comment by q861865812** [comment]
<img width="523" alt="图片" src="https://user-images.githubusercontent.com/54823655/177091056-d696f17c-c448-4511-a7bb-3a478a65b6c5.png">

**Comment by CharliHui** [comment]
<img width="442" alt="image" src="https://user-images.githubusercontent.com/13757734/178179513-5b3705c3-c5bd-4a9d-8480-65eb751ee0db.png">
运行这两个命令之后重启也不行么？

**Comment by q861865812** [comment]
<img width="1218" alt="图片" src="https://user-images.githubusercontent.com/54823655/179000512-f9e3bbc7-ad26-41bd-a0bb-673f04597b63.png">
不行，我在mac里就行，虚拟机里面不行

**Comment by gobysec** [comment]
您好，此问题已在Goby2.0版本解决，若有其他问题，可联系微信：gobyteam。感谢您的支持与反馈~
