### ISSUE TITLE
未知的错误

### ISSUE THREAD

**Issue by Zanywrc** [gobysec/Goby#313]
2022/7/6 扫描开始就报错

**Comment by Zanywrc** [comment]
2022/07/06 17:22:48 127.0.0.1:17370 POST /api/v1/getProgress

2022/07/06 17:22:48 127.0.0.1:17371 POST /api/v1/getStatisticsData

2022/07/06 17:22:48 scan 21,22,23,25,53,U:53,U:69,80,81,U:88,110,111,U:111,123,U:123,135,U:137,139,U:161,U:177,389,U:427,443,445,465,500,515,U:520,U:523,548,623,U:626,636,873,902,1080,1099,1433,U:1434,1521,U:1604,U:1645,U:1701,1883,U:1900,2049,2181,2375,2379,U:2425,3128,3306,3389,4730,U:5060,5222,U:5351,U:5353,5432,5555,5601,5672,U:5683,5900,5938,5984,6000,6379,7001,7077,8080,8081,8443,8545,8686,9000,9001,9042,9092,9100,9200,9418,9999,11211,U:11211,27017,U:33848,37777,50000,50070,61616 www.baidu.com

2022/07/06 17:22:48 start port scanner: totalSize: 182, rate: 100, connectionSize: 100, connectTimeout: 6s, retryTimes: 0, Random: true, Seed: 1657099368482305300, ScanOffset: 0, ScanICMP: false, CheckAliveMode: 2

2022/07/06 17:22:48 pcap version: Npcap version 1.10, based on libpcap version 1.9.1

2022/07/06 17:22:49 found device from route table for 45.113.192.101:

2022/07/06 17:22:49 [DEBUG] get adapter of device

2022/07/06 17:22:49 [DEBUG] devices: []

2022/07/06 17:22:49 [ERROR] could not find any network interface.

panic: could not find any network interface.

goroutine 85 [running]:

git.gobies.org/goby/portscanner/pcapsend.getAdapter({0x0, 0x0}, 0x0, 0xc0?, 0x0)

git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/pcapsend/device.go:349 +0x205

git.gobies.org/goby/portscanner/pcapsend.NewPcapSender(0xc0000dc420, 0xc00501ea00, 0xc00501ea50)

git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/pcapsend/send.go:95 +0x23e

git.gobies.org/goby/portscanner.(*PortScanner).startPcapScan(0xc000bf0150, {0x1433db6e0?, 0xc00466d8c0}, 0xe44fabae00000000?, 0xc005b6e360, 0xc005b6e3c0)

git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/portscanner.go:183 +0x88

created by git.gobies.org/goby/portscanner.(*PortScanner).Start

git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/portscanner.go:232 +0x595

**Comment by gobysec** [comment]
您好，您需要选择下正确的网卡Ip，开启VPN选择VPN的网卡，未开启选择本机网卡。若无法识别到网卡，请重装Npcap1.6版本，安装时勾选管理员权限。若还是无法解决，请联系微信：gobyteam
