### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by carlsue** [gobysec/Goby#314]
![image](https://user-images.githubusercontent.com/17507066/177718004-764130bf-91a8-49ea-9cd6-97a546d37698.png)

2022/07/07 15:33:51 read user rule file ok: 0
2022/07/07 15:33:51 Version: v2.0.312+alpha
2022/07/07 15:33:54 API Server listen at  127.0.0.1:8361
2022/07/07 15:33:54 [ERROR] API Server exit: listen tcp 127.0.0.1:8361: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
2022/07/07 15:33:54 [StartService ERROR] {content："server bind failed", errCode: 0}
panic: listen tcp 127.0.0.1:8361: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

goroutine 10 [running]:
git.gobies.org/goby/goby/api.StartAPIServer.func1()
	git.gobies.org/goby/goby/api/api.go:322 +0x127
created by git.gobies.org/goby/goby/api.StartAPIServer
	git.gobies.org/goby/goby/api/api.go:308 +0x148

**Comment by 2522595153** [comment]
躺平我还以为把

**Comment by gobysec** [comment]
goby-cmd监听时报错：`panic: listen tcp 127.0.0.1:8361: bind: An attempt was made to access a socket in a way forbidden by its access permissions`。 以管理员权限运行Goby，8361端口也没被占用， 防火墙也关了，但还是报这个错。解决方法：

```
net stop winnat
netsh int ipv4 add excludedportrange protocol=tcp startport=8361 numberofports=1
net start winnat
```
出现这种情况，可能是开了hyper-v

非常抱歉没有及时解决您的问题，若后续再有其他问题，可直接联系微信：gobyteam

**Comment by carlsue** [comment]
> 

![image](https://user-images.githubusercontent.com/17507066/180915473-4c62315f-eecf-43b0-b6d4-719d4419352d.png)

**Comment by gobysec** [comment]
请问Goby版本号是多少，是否有升级到2.0.4，可能已解决此问题。

**Comment by msfisgood** [comment]
2.0.5还有相同问题

**Comment by laohuan12138** [comment]
> ![image](https://user-images.githubusercontent.com/17507066/177718004-764130bf-91a8-49ea-9cd6-97a546d37698.png)
> 
> 2022/07/07 15:33:51 read user rule file ok: 0 2022/07/07 15:33:51 Version: v2.0.312+alpha 2022/07/07 15:33:54 API Server listen at 127.0.0.1:8361 2022/07/07 15:33:54 [ERROR] API Server exit: listen tcp 127.0.0.1:8361: bind: An attempt was made to access a socket in a way forbidden by its access permissions. 2022/07/07 15:33:54 [StartService ERROR] {content："server bind failed", errCode: 0} panic: listen tcp 127.0.0.1:8361: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
> 
> goroutine 10 [running]: git.gobies.org/goby/goby/api.StartAPIServer.func1() git.gobies.org/goby/goby/api/api.go:322 +0x127 created by git.gobies.org/goby/goby/api.StartAPIServer git.gobies.org/goby/goby/api/api.go:308 +0x148

安装https://www.winpcap.org/install/bin/WinPcap_4_1_3.exe即可解决

**Comment by msfisgood** [comment]
> 2.0.5还有相同问题

我当时问题的原因windows环境变量中存在go的代理，删除相关go代理后可解决该问题
