### ISSUE TITLE
2.0.2版本无法连接服务器，服务端：auth Error，客户端： bind: The requested address is not valid in its context. 2022/07/08 16:53:36 [StartService ERROR] {content："server bind failed", errCode: 0}

### ISSUE THREAD

**Issue by githublihaha** [gobysec/Goby#315]
客户端日志：
2022/07/08 16:53:34 read user rule file ok: 0
2022/07/08 16:53:34 Version: v2.0.312+alpha
2022/07/08 16:53:36 API Server listen at XXX.XXX.XXX.XXX:XXXX
2022/07/08 16:53:36 [ERROR] API Server exit: listen tcp XXX.XXX.XXX.XXX:XXXX: bind: The requested address is not valid in its context.
2022/07/08 16:53:36 [StartService ERROR] {content："server bind failed", errCode: 0}
panic: listen tcp XXX.XXX.XXX.XXX:XXXX: bind: The requested address is not valid in its context.
goroutine 14 [running]:
git.gobies.org/goby/goby/api.StartAPIServer.func1()
git.gobies.org/goby/goby/api/api.go:322 +0x127
created by git.gobies.org/goby/goby/api.StartAPIServer
git.gobies.org/goby/goby/api/api.go:308 +0x148

服务器端日志：
2022/07/08 16:54:09 XXX.XXX.XXX.XXX:XXXX auth Error
2022/07/08 16:54:12 XXX.XXX.XXX.XXX:XXXX   GET   /api/v1/live
2022/07/08 16:54:12 XXX.XXX.XXX.XXX:XXXX auth Error
2022/07/08 16:54:14 XXX.XXX.XXX.XXX:XXXX   GET   /api/v1/live
2022/07/08 16:54:14 XXX.XXX.XXX.XXX:XXXX auth Error
2022/07/08 16:54:17 XXX.XXX.XXX.XXX:XXXX   GET   /api/v1/live
2022/07/08 16:54:17 XXX.XXX.XXX.XXX:XXXX auth Error

**Comment by gobysec** [comment]
您好，客户端报错内容为您请求的地址无效，请检查核对。
服务端关于auth error并非报错，您可正常使用。
若还未解决，请联系微信：gobyteam
