### ISSUE TITLE
使用时报错

### ISSUE THREAD

**Issue by WLStars** [gobysec/Goby#316]
警告

发生未知错误，Goby 将尝试重启解决。若重启后错误仍存在，请反馈给我们。 Github issue

错误详情: Error
2022/07/10 14:41:43 read user rule file ok: 0
2022/07/10 14:41:43 Version: v2.0.312+alpha
2022/07/10 14:41:45 API Server listen at 127.0.0.1:8361
2022/07/10 14:41:45 127.0.0.1:63421 GET /api/v1/live
2022/07/10 14:41:53 127.0.0.1:63424 POST /api/v1/setEnvi
2022/07/10 14:41:53 127.0.0.1:63426 POST /api/v1/getTasks

**Comment by gobysec** [comment]
您好，若您安装npcap1.7版本，请尝试重装Npcap1.6版本，安装时勾选管理员权限。若还未解决，请联系微信：gobyteam
