### ISSUE TITLE
重启没有用

### ISSUE THREAD

**Issue by lisi-777** [gobysec/Goby#318]
2022/07/13 11:12:55 read user rule file ok: 0
2022/07/13 11:12:55 Version: v2.0.312+alpha
2022/07/13 11:12:57 API Server listen at  124.222.118.80:8361
2022/07/13 11:12:57 [ERROR] API Server exit: listen tcp 124.222.118.80:8361: bind: The requested address is not valid in its context.
2022/07/13 11:12:57 [StartService ERROR] {content："server bind failed", errCode: 0}
panic: listen tcp 124.222.118.80:8361: bind: The requested address is not valid in its context.

goroutine 66 [running]:
git.gobies.org/goby/goby/api.StartAPIServer.func1()
	git.gobies.org/goby/goby/api/api.go:322 +0x127
created by git.gobies.org/goby/goby/api.StartAPIServer
	git.gobies.org/goby/goby/api/api.go:308 +0x148

**Comment by x-l-y** [comment]
2022/07/16 09:46:50 read user rule file ok: 0
2022/07/16 09:46:50 Version: v2.0.312+alpha
2022/07/16 09:46:52 API Server listen at 127.0.0.1:8361
2022/07/16 09:46:52 [ERROR] API Server exit: listen tcp 127.0.0.1:8361: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
2022/07/16 09:46:52 [StartService ERROR] {content："server bind failed", errCode: 0}
panic: listen tcp 127.0.0.1:8361: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
goroutine 14 [running]:
git.gobies.org/goby/goby/api.StartAPIServer.func1()
git.gobies.org/goby/goby/api/api.go:322 +0x127
created by git.gobies.org/goby/goby/api.StartAPIServer
git.gobies.org/goby/goby/api/api.go:308 +0x148

**Comment by gobysec** [comment]
> 2022/07/16 09:46:50 read user rule file ok: 0 2022/07/16 09:46:50 Version: v2.0.312+alpha 2022/07/16 09:46:52 API Server listen at 127.0.0.1:8361 2022/07/16 09:46:52 [ERROR] API Server exit: listen tcp 127.0.0.1:8361: bind: An attempt was made to access a socket in a way forbidden by its access permissions. 2022/07/16 09:46:52 [StartService ERROR] {content："server bind failed", errCode: 0} panic: listen tcp 127.0.0.1:8361: bind: An attempt was made to access a socket in a way forbidden by its access permissions. goroutine 14 [running]: git.gobies.org/goby/goby/api.StartAPIServer.func1() git.gobies.org/goby/goby/api/api.go:322 +0x127 created by git.gobies.org/goby/goby/api.StartAPIServer git.gobies.org/goby/goby/api/api.go:308 +0x148

goby-cmd监听时报错：`panic: listen tcp 127.0.0.1:8361: bind: An attempt was made to access a socket in a way forbidden by its access permissions`。 以管理员权限运行Goby，8361端口也没被占用， 防火墙也关了，但还是报这个错。解决方法：

```
net stop winnat
netsh int ipv4 add excludedportrange protocol=tcp startport=8361 numberofports=1
net start winnat
```
出现这种情况，可能是开了hyper-v
