### ISSUE TITLE
提示error query报错不知道什么问题

### ISSUE THREAD

**Issue by Kacker1992** [gobysec/Goby#32]
![123](https://user-images.githubusercontent.com/50517998/77076384-bb33de80-6a2e-11ea-9948-07439f042fb4.png)

**Comment by gobysec** [comment]
您的操作系统是wins还是linux？ 加群详聊？https://t.me/gobies

**Comment by huangsen0813** [comment]
windows的

**Comment by huangsen0813** [comment]
windows的

**Comment by huangsen0813** [comment]
windows

> 您的操作系统是wins还是Linux？加群详聊？[https:](https://t.me/gobies) //t.me/gobies[](https://t.me/gobies)

windows

**Comment by gobysec** [comment]
> windows
> 
> > 您的操作系统是wins还是Linux？加群详聊？[https:](https://t.me/gobies) //t.me/gobies
> 
> windows

我们已经定位出问题，将在下个版本解决它，再次感谢您的反馈。

**Comment by gobysec** [comment]
你好，您反馈的问题已在Goby最新版Beta1.6.114修改完成。请前往goby官网gobies.org下载适用版本。
