### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by GitHubY-Z** [gobysec/Goby#321]
发生未知错误，Goby 将尝试重启解决。若重启后错误仍存在，请反馈给我们。 Github issue

错误详情: Error
2022/07/15 10:03:33 read user rule file ok: 0
2022/07/15 10:03:33 Version: v2.0.312+alpha
2022/07/15 10:03:35 API Server listen at 127.0.0.1:8361
2022/07/15 10:03:35 127.0.0.1:17369 GET /api/v1/live
2022/07/15 10:03:43 127.0.0.1:17384 POST /api/v1/setEnvi
2022/07/15 10:03:44 127.0.0.1:17386 POST /api/v1/getTasks
2022/07/15 10:03:44 127.0.0.1:17385 GET /api/v1/getEnvi?
2022/07/15 10:03:45 [DEBUG] get adapter of device \Device\NPF_{EF66933A-AB6D-4D81-8525-03B787DE4DC8}
2022/07/15 10:03:45 [DEBUG] devices: [{\Device\NPF_{51C6FD86-6CCD-4958-B565-9FAA07ACD038} WAN Miniport (IPv6) 22 []} {\Device\NPF_{057DECC0-4C3A-4E75-98CE-5CB04F6F0643} WAN Miniport (IP) 22 []} {\Device\NPF_{48CE4169-74AA-41D8-B9D8-99DECE1270A0} WAN Miniport (Network Monitor) 22 []} {\Device\NPF_{EF66933A-AB6D-4D81-8525-03B787DE4DC8} Intel(R) Wireless-AC 9462 30 [{fe80::acb0:e79f:4aef:273b ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {192.168.0.157 ffffff00 192.168.0.255 <nil>}]} {\Device\NPF_{8F834E7D-3202-4941-900D-2CC2CE2FD2C4} VMware Virtual Ethernet Adapter for VMnet8 22 [{fe80::bd4d:710a:da1f:4189 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {192.168.133.1 ffffff00 192.168.133.255 <nil>}]} {\Device\NPF_{20DD1CC9-5D94-4F83-BF6D-8DEC63FF4959} VMware Virtual Ethernet Adapter for VMnet1 22 [{fe80::a0d6:163f:e8ad:eda7 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {192.168.42.1 ffffff00 192.168.42.255 <nil>}]} {\Device\NPF_{EBEDB224-349C-4D41-A23F-B59D669527D3} Microsoft Wi-Fi Direct Virtual Adapter #2 46 [{fe80::5cb6:67d3:a538:c357 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {169.254.195.87 ffff0000 169.254.255.255 <nil>}]} {\Device\NPF_{EB3E3113-B8A1-4D84-84DB-9EF5D188D46F} Microsoft Wi-Fi Direct Virtual Adapter 46 [{fe80::3ca1:776:6e09:ed8b ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {169.254.237.139 ffff0000 169.254.255.255 <nil>}]} {\Device\NPF_{ED14B410-7820-41E9-937A-313A6A8B5C5F} Hyper-V Virtual Ethernet Adapter 22 [{fe80::bdb2:f1ca:d76a:674d ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {172.18.208.1 fffff000 172.18.223.255 <nil>}]} {\Device\NPF_Loopback Adapter for loopback traffic capture 55 []} {\Device\NPF_{CC6C096A-A82F-4A90-B489-22E8B6D5545A} Realtek PCIe GBE Family Controller 38 [{fe80::7429:b738:9f8b:7ebf ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {169.254.126.191 ffff0000 169.254.255.255 <nil>}]}]
2022/07/15 10:03:45 [DEBUG] device name is not match: \Device\NPF_{51C6FD86-6CCD-4958-B565-9FAA07ACD038} != \Device\NPF_{EF66933A-AB6D-4D81-8525-03B787DE4DC8}
2022/07/15 10:03:45 [DEBUG] device name is not match: \Device\NPF_{057DECC0-4C3A-4E75-98CE-5CB04F6F0643} != \Device\NPF_{EF66933A-AB6D-4D81-8525-03B787DE4DC8}
2022/07/15 10:03:45 [DEBUG] device name is not match: \Device\NPF_{48CE4169-74AA-41D8-B9D8-99DECE1270A0} != \Device\NPF_{EF66933A-AB6D-4D81-8525-03B787DE4DC8}
2022/07/15 10:03:45 [DEBUG] getGatewayMac: \Device\NPF_{EF66933A-AB6D-4D81-8525-03B787DE4DC8} 0.0.0.0
2022/07/15 10:03:45 Error calling PacketGetTimestampModes: �и������ݿ��á� (234) goroutine 68 [running]:
runtime/debug.Stack()
runtime/debug/stack.go:24 +0x65
git.gobies.org/goby/goby/api.envField({0x0?, 0xc00511fda0?}, {0x1422f29d3?, 0x9?})
git.gobies.org/goby/goby/api/getEnvi.go:81 +0x39d
git.gobies.org/goby/goby/api.getEnviFields({0x0, 0x0}, {0xc0060df6f0, 0xf, 0x140100d85?})
git.gobies.org/goby/goby/api/getEnvi.go:146 +0xec
git.gobies.org/goby/goby/api.getEnviHandler({0x1433da2b8, 0xc002baf0a0}, 0xc000f9c600?)
git.gobies.org/goby/goby/api/getEnvi.go:181 +0x2fd
net/http.HandlerFunc.ServeHTTP(...)
net/http/server.go:2084
git.gobies.org/goby/goby/api.basicAuth.func1({0x1433da2b8?, 0xc002baf0a0?}, 0x88?)
git.gobies.org/goby/goby/api/api.go:121 +0x248
net/http.HandlerFunc.ServeHTTP(...)
net/http/server.go:2084
git.gobies.org/goby/goby/api.logHttpRequest.func1({0x1433da2b8, 0xc002baf0a0}, 0xc0024a6800)
git.gobies.org/goby/goby/api/api.go:104 +0x1f4
net/http.HandlerFunc.ServeHTTP(0xc0024a6700?, {0x1433da2b8?, 0xc002baf0a0?}, 0x0?)
net/http/server.go:2084 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0062203c0, {0x1433da2b8, 0xc002baf0a0}, 0xc0024a6600)
github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc00511fb00?}, {0x1433da2b8, 0xc002baf0a0}, 0xc0024a6600)
net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0051920a0, {0x1433db788, 0xc006360150})
net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
net/http/server.go:3071 +0x4db
2022/07/15 10:03:45 [DEBUG] get adapter of device \Device\NPF_{EF66933A-AB6D-4D81-8525-03B787DE4DC8}
2022/07/15 10:03:46 [DEBUG] devices: [{\Device\NPF_{51C6FD86-6CCD-4958-B565-9FAA07ACD038} WAN Miniport (IPv6) 22 []} {\Device\NPF_{057DECC0-4C3A-4E75-98CE-5CB04F6F0643} WAN Miniport (IP) 22 []} {\Device\NPF_{48CE4169-74AA-41D8-B9D8-99DECE1270A0} WAN Miniport (Network Monitor) 22 []} {\Device\NPF_{EF66933A-AB6D-4D81-8525-03B787DE4DC8} Intel(R) Wireless-AC 9462 30 [{fe80::acb0:e79f:4aef:273b ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {192.168.0.157 ffffff00 192.168.0.255 <nil>}]} {\Device\NPF_{8F834E7D-3202-4941-900D-2CC2CE2FD2C4} VMware Virtual Ethernet Adapter for VMnet8 22 [{fe80::bd4d:710a:da1f:4189 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {192.168.133.1 ffffff00 192.168.133.255 <nil>}]} {\Device\NPF_{20DD1CC9-5D94-4F83-BF6D-8DEC63FF4959} VMware Virtual Ethernet Adapter for VMnet1 22 [{fe80::a0d6:163f:e8ad:eda7 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {192.168.42.1 ffffff00 192.168.42.255 <nil>}]} {\Device\NPF_{EBEDB224-349C-4D41-A23F-B59D669527D3} Microsoft Wi-Fi Direct Virtual Adapter #2 46 [{fe80::5cb6:67d3:a538:c357 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {169.254.195.87 ffff0000 169.254.255.255 <nil>}]} {\Device\NPF_{EB3E3113-B8A1-4D84-84DB-9EF5D188D46F} Microsoft Wi-Fi Direct Virtual Adapter 46 [{fe80::3ca1:776:6e09:ed8b ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {169.254.237.139 ffff0000 169.254.255.255 <nil>}]} {\Device\NPF_{ED14B410-7820-41E9-937A-313A6A8B5C5F} Hyper-V Virtual Ethernet Adapter 22 [{fe80::bdb2:f1ca:d76a:674d ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {172.18.208.1 fffff000 172.18.223.255 <nil>}]} {\Device\NPF_Loopback Adapter for loopback traffic capture 55 []} {\Device\NPF_{CC6C096A-A82F-4A90-B489-22E8B6D5545A} Realtek PCIe GBE Family Controller 38 [{fe80::7429:b738:9f8b:7ebf ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {169.254.126.191 ffff0000 169.254.255.255 <nil>}]}]
2022/07/15 10:03:46 [DEBUG] device name is not match: \Device\NPF_{51C6FD86-6CCD-4958-B565-9FAA07ACD038} != \Device\NPF_{EF66933A-AB6D-4D81-8525-03B787DE4DC8}
2022/07/15 10:03:46 [DEBUG] device name is not match: \Device\NPF_{057DECC0-4C3A-4E75-98CE-5CB04F6F0643} != \Device\NPF_{EF66933A-AB6D-4D81-8525-03B787DE4DC8}
2022/07/15 10:03:46 [DEBUG] device name is not match: \Device\NPF_{48CE4169-74AA-41D8-B9D8-99DECE1270A0} != \Device\NPF_{EF66933A-AB6D-4D81-8525-03B787DE4DC8}
2022/07/15 10:03:46 [DEBUG] getGatewayMac: \Device\NPF_{EF66933A-AB6D-4D81-8525-03B787DE4DC8} 0.0.0.0
2022/07/15 10:03:46 Error calling PacketGetTimestampModes: �и������ݿ��á� (234) goroutine 68 [running]:
runtime/debug.Stack()
runtime/debug/stack.go:24 +0x65
git.gobies.org/goby/goby/api.envField({0x0?, 0xc00511fda0?}, {0x1422c5572?, 0x2?})
git.gobies.org/goby/goby/api/getEnvi.go:81 +0x39d
git.gobies.org/goby/goby/api.getEnviFields({0x0, 0x0}, {0xc0060df6f0, 0xf, 0x140100d85?})
git.gobies.org/goby/goby/api/getEnvi.go:146 +0xec
git.gobies.org/goby/goby/api.getEnviHandler({0x1433da2b8, 0xc002baf0a0}, 0xc000f9c600?)
git.gobies.org/goby/goby/api/getEnvi.go:181 +0x2fd
net/http.HandlerFunc.ServeHTTP(...)
net/http/server.go:2084
git.gobies.org/goby/goby/api.basicAuth.func1({0x1433da2b8?, 0xc002baf0a0?}, 0x88?)
git.gobies.org/goby/goby/api/api.go:121 +0x248
net/http.HandlerFunc.ServeHTTP(...)
net/http/server.go:2084
git.gobies.org/goby/goby/api.logHttpRequest.func1({0x1433da2b8, 0xc002baf0a0}, 0xc0024a6800)
git.gobies.org/goby/goby/api/api.go:104 +0x1f4
net/http.HandlerFunc.ServeHTTP(0xc0024a6700?, {0x1433da2b8?, 0xc002baf0a0?}, 0x0?)
net/http/server.go:2084 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0062203c0, {0x1433da2b8, 0xc002baf0a0}, 0xc0024a6600)
github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc00511fb00?}, {0x1433da2b8, 0xc002baf0a0}, 0xc0024a6600)
net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0051920a0, {0x1433db788, 0xc006360150})
net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
net/http/server.go:3071 +0x4db

**Comment by gobysec** [comment]
您好，请您将npcap1.7版本暂时先改为1.6版本，安装时勾选管理员权限即可。若还有问题，请联系微信：gobyteam。感谢您的反馈与支持
