### ISSUE TITLE
Win-2.0.2-Community启动页面卡死

### ISSUE THREAD

**Issue by pumpkinShare** [gobysec/Goby#322]
在Win10平台，不开启代理的默认网络情况下，使用管理员身份双击启动 2.0.2-Community 版本的 Goby.exe，一直停留在 Analyzing environment 的初始化启动页面并卡死。
![image](https://user-images.githubusercontent.com/67215099/179254833-58417888-aafe-4363-ab06-82d71f2e66fa.png)

在同样环境下测试 1.9.325 版本，可以正常启动并使用。但如果要更新到最新版本 2.0.2，则会出现更新卡死的情况。
![image](https://user-images.githubusercontent.com/67215099/179255212-63181d59-d566-441d-a6b4-a7cf5dd4f874.png)

**Comment by hafey-lx** [comment]
问题已解决，只要删除环境变量中的 http_proxy 变量即可，具体可参考：https://blog.csdn.net/phpwechat/article/details/113993824。
