### ISSUE TITLE
扫描报错

### ISSUE THREAD

**Issue by ziyun01** [gobysec/Goby#323]
发生未知错误，Goby 将尝试重启解决。若重启后错误仍存在，请反馈给我们。 Github issue

错误详情: Error
2022/07/20 09:16:27 read user rule file ok: 0
2022/07/20 09:16:27 Version: v2.0.312+alpha
2022/07/20 09:16:29 API Server listen at 127.0.0.1:8361
2022/07/20 09:16:29 127.0.0.1:53099 GET /api/v1/live
2022/07/20 09:16:37 127.0.0.1:53112 POST /api/v1/setEnvi
2022/07/20 09:16:38 127.0.0.1:53116 GET /api/v1/getEnvi?
2022/07/20 09:16:38 127.0.0.1:53117 POST /api/v1/getTasks
2022/07/20 09:16:38 [DEBUG] get adapter of device
2022/07/20 09:16:38 [DEBUG] devices: []
2022/07/20 09:16:38 [ERROR] could not find any network interface.
2022/07/20 09:16:38 interface conversion: string is not error: missing method Error
2022/07/20 09:16:38 interface conversion: string is not error: missing method Error goroutine 31 [running]:
runtime/debug.Stack()
runtime/debug/stack.go:24 +0x65
git.gobies.org/goby/goby/api.getEnviHandler.func1()
git.gobies.org/goby/goby/api/getEnvi.go:169 +0x14c
panic({0x141fd24e0, 0xc0063b6000})
runtime/panic.go:838 +0x207
git.gobies.org/goby/goby/api.pcapInfo.func1()
git.gobies.org/goby/goby/api/getEnvi.go:33 +0x45
panic({0x141ed4680, 0x1433c0480})
runtime/panic.go:838 +0x207
git.gobies.org/goby/portscanner/pcapsend.getAdapter({0x0, 0x0}, 0x0, 0xc0?, 0x0)
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/pcapsend/device.go:349 +0x205
git.gobies.org/goby/portscanner/pcapsend.GetAdpaterInfo({0x0?, 0x190108?})
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/pcapsend/device.go:355 +0x25
git.gobies.org/goby/goby/api.pcapInfo({0x0?, 0x36?})
git.gobies.org/goby/goby/api/getEnvi.go:42 +0x7c
git.gobies.org/goby/goby/api.envField({0x0?, 0xc005ee8000?}, {0x1422f29d3?, 0x9?})
git.gobies.org/goby/goby/api/getEnvi.go:73 +0x385
git.gobies.org/goby/goby/api.getEnviFields({0x0, 0x0}, {0xc0043056f0, 0xf, 0x140100d85?})
git.gobies.org/goby/goby/api/getEnvi.go:146 +0xec
git.gobies.org/goby/goby/api.getEnviHandler({0x1433da2b8, 0xc0001d90a0}, 0xc000b9ef40?)
git.gobies.org/goby/goby/api/getEnvi.go:181 +0x2fd
net/http.HandlerFunc.ServeHTTP(...)
net/http/server.go:2084
git.gobies.org/goby/goby/api.basicAuth.func1({0x1433da2b8?, 0xc0001d90a0?}, 0x88?)
git.gobies.org/goby/goby/api/api.go:121 +0x248
net/http.HandlerFunc.ServeHTTP(...)
net/http/server.go:2084
git.gobies.org/goby/goby/api.logHttpRequest.func1({0x1433da2b8, 0xc0001d90a0}, 0xc0024f7000)
git.gobies.org/goby/goby/api/api.go:104 +0x1f4
net/http.HandlerFunc.ServeHTTP(0xc0024f6f00?, {0x1433da2b8?, 0xc0001d90a0?}, 0x0?)
net/http/server.go:2084 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0041f63c0, {0x1433da2b8, 0xc0001d90a0}, 0xc0008ea400)
github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc004268810?}, {0x1433da2b8, 0xc0001d90a0}, 0xc0008ea400)
net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc00277a0a0, {0x1433db788, 0xc00662e150})
net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
net/http/server.go:3071 +0x4db
2022/07/20 09:16:49 127.0.0.1:53130 POST /api/v1/getStatisticsData
2022/07/20 09:16:50 127.0.0.1:53135 POST /api/v1/resumeScan
2022/07/20 09:16:50 scan 1-65535 172.67.179.169
2022/07/20 09:16:50 start port scanner: totalSize: 65535, rate: 100, connectionSize: 100, connectTimeout: 6s, retryTimes: 0, Random: true, Seed: 1658224835065765100, ScanOffset: 0, ScanICMP: false, CheckAliveMode: 0
2022/07/20 09:16:50 pcap version: Npcap version 0.9995, based on libpcap version 1.9.1
2022/07/20 09:16:50 127.0.0.1:53136 POST /api/v1/getProgress
2022/07/20 09:16:50 found device from route table for 172.67.179.169:
2022/07/20 09:16:50 [DEBUG] get adapter of device
2022/07/20 09:16:50 [DEBUG] devices: []
2022/07/20 09:16:50 [ERROR] could not find any network interface.
panic: could not find any network interface.
goroutine 62 [running]:
git.gobies.org/goby/portscanner/pcapsend.getAdapter({0x0, 0x0}, 0x0, 0xc0?, 0x0)
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/pcapsend/device.go:349 +0x205
git.gobies.org/goby/portscanner/pcapsend.NewPcapSender(0xc001b94c60, 0xc005f30a00, 0xc005f30a50)
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/pcapsend/send.go:95 +0x23e
git.gobies.org/goby/portscanner.(*PortScanner).startPcapScan(0xc000c15b20, {0x1433db6e0?, 0xc0042b4c80}, 0x1433c2180?, 0xc0027c2900, 0xc0027c2960)
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/portscanner.go:183 +0x88
created by git.gobies.org/goby/portscanner.(*PortScanner).Start
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/portscanner.go:232 +0x595

**Comment by gobysec** [comment]
您好，您需要选择下正确的网卡Ip，开启VPN选择VPN的网卡，未开启选择本机网卡。若无法识别到网卡，请重装Npcap1.6版本，安装时勾选管理员权限。若还是无法解决，请联系微信：gobyteam
