### ISSUE TITLE
goby-win-x64-2.0.4扫描结果较多会一直加载

### ISSUE THREAD

**Issue by alair074** [gobysec/Goby#325]
goby-win-x64-2.0.4扫描结果较多会一直加载，电脑配置是ok的
![image](https://user-images.githubusercontent.com/41234701/180639489-41a1c26d-234a-46ad-83b7-531bc6431dd9.png)

![image](https://user-images.githubusercontent.com/41234701/180639438-ca42789c-e680-4b53-8a77-3cdf3df7e952.png)

![image](https://user-images.githubusercontent.com/41234701/180639375-e9448c6f-783a-406a-8dd0-78e710cfd91f.png)

**Comment by gobysec** [comment]
已知问题，正在紧急优先解决，不定期更新进展，感谢您的反馈与支持~

**Comment by shad0w0sec** [comment]
> 已知问题，正在紧急优先解决，不定期更新进展，感谢您的反馈与支持~

快一年了，问题还是没有解决

**Comment by gobysec** [comment]
此问题已修复，已在最新版本中发布，若紧急情况可联系微信：gobyteam协助您解决！感谢您的反馈与支持～
