### ISSUE TITLE
Goby has an unknown error

### ISSUE THREAD

**Issue by u1s1nb** [gobysec/Goby#327]
2022/07/29 09:11:36 read user rule file ok: 0
2022/07/29 09:11:36 Version: v2.0.312+alpha
2022/07/29 09:11:37 API Server listen at  127.0.0.1:8361
2022/07/29 09:11:38 127.0.0.1:1626   GET   /api/v1/live  
2022/07/29 09:11:46 127.0.0.1:1628   POST   /api/v1/setEnvi  
2022/07/29 09:11:46 127.0.0.1:1630   POST   /api/v1/getTasks  
2022/07/29 09:11:46 127.0.0.1:1629   GET   /api/v1/getEnvi?  
2022/07/29 09:11:47 [DEBUG] get adapter of device 
2022/07/29 09:11:47 [DEBUG] devices:  [{\Device\NPF_Loopback Adapter for loopback traffic capture 55 [{::1 ffffffffffffffffffffffffffffffff <nil> <nil>} {127.0.0.1 ff000000 <nil> <nil>}]}]
2022/07/29 09:11:47 scan is local host, rmac is 0xffffffffffff
2022/07/29 09:11:47 127.0.0.1:1637   GET   /api/v1/getEnvi?field=licenseInfo  
2022/07/29 09:12:14 127.0.0.1:1656   POST   /api/v1/getTasks  
2022/07/29 09:12:17 127.0.0.1:1661   POST   /api/v1/getPOCList  
2022/07/29 09:12:17 [WARNING] QueryUniqHostInfo failed: no such column: f.phash icon_hash="116323821" || body="Greetings from Spring Boot!" || body="Whitelabel Error Page"
2022/07/29 09:12:19 127.0.0.1:1668   POST   /api/v1/startScan  
2022/07/29 09:12:19 [WARNING] change user-agent feature is not included in your current license.
2022/07/29 09:12:19 [WARNING] change deep-analysis feature is not included in your current license.
2022/07/29 09:12:19 scan  21,22,23,25,53,U:53,U:69,80,81,U:88,110,111,U:111,123,U:123,135,U:137,139,U:161,U:177,389,U:427,443,445,465,500,515,U:520,U:523,548,623,U:626,636,873,902,1080,1099,1433,U:1434,1521,U:1604,U:1645,U:1701,1883,U:1900,2049,2181,2375,2379,U:2425,3128,3306,3389,4730,U:5060,5222,U:5351,U:5353,5432,5555,5601,5672,U:5683,5900,5938,5984,6000,6379,7001,7077,8080,8081,8443,8545,8686,9000,9001,9042,9092,9100,9200,9418,9999,11211,U:11211,27017,U:33848,37777,50000,50070,61616 127.0.0.0/24
2022/07/29 09:12:19 start port scanner: totalSize: 23296, rate: 100, connectionSize: 100, connectTimeout: 6s, retryTimes: 0, Random: true, Seed: 1659057139367361800, ScanOffset: 0, ScanICMP: false, CheckAliveMode: 2
2022/07/29 09:12:19 pcap version: Npcap version 1.70, based on libpcap version 1.10.2-PRE-GIT
2022/07/29 09:12:19 127.0.0.1:1669   POST   /api/v1/getProgress  
2022/07/29 09:12:19 127.0.0.1:1670   POST   /api/v1/getStatisticsData  
2022/07/29 09:12:19 found device from route table for 127.0.0.0: \Device\NPF_Loopback
2022/07/29 09:12:19 [DEBUG] get adapter of device \Device\NPF_Loopback
2022/07/29 09:12:19 [DEBUG] devices:  [{\Device\NPF_Loopback Adapter for loopback traffic capture 55 [{::1 ffffffffffffffffffffffffffffffff <nil> <nil>} {127.0.0.1 ff000000 <nil> <nil>}]}]
2022/07/29 09:12:19 scan is local host, rmac is 0xffffffffffff
2022/07/29 09:12:19 select adapter of to send packets:  &{\Device\NPF_Loopback 127.0.0.1 [::1] {127.0.0.1 ff000000} ff000000 ff:ff:ff:ff:ff:ff Adapter for loopback traffic capture ff:ff:ff:ff:ff:ff}
2022/07/29 09:12:19 could not create: Error opening adapter: �����ɹ���ɡ�  (0)

**Comment by gobysec** [comment]
Do not use npcap1.7. Please download npcap1.6. Check administrator permission during installation
