### ISSUE TITLE
是否支持真正的全端口扫描

### ISSUE THREAD

**Issue by 0xa-saline** [gobysec/Goby#33]
我看了所谓的全端口是常见的端口多一些。

是否可以支持扫描范围，类似于7001-999这个的解析。方便解析1-65535

**Comment by gobysec** [comment]
支持自定义扫描端口组
![image](https://user-images.githubusercontent.com/50955360/77493357-e038af00-6e7d-11ea-9258-92885ffd35e9.png)
![image](https://user-images.githubusercontent.com/50955360/77493382-f47cac00-6e7d-11ea-9302-576a72d039e8.png)
