### ISSUE TITLE
Goby-darwin-x64-2.0.4版本 扫描整个C段时会有非常多的重复IP

### ISSUE THREAD

**Issue by dringer123** [gobysec/Goby#331]
当我扫描一个/24段时，很多重复的IP，导致这个C段的存活IP数量是双倍的，一个C段能有300多个存活IP你敢信

**Comment by gobysec** [comment]
请您添加微信：gobyteam，提供更多详细信息，感谢。

**Comment by gobysec** [comment]
此问题已修复，已在最新版本中发布，若紧急情况可联系微信：gobyteam协助您解决！感谢您的反馈与支持～
