### ISSUE TITLE
通过l2tp 拨号接入远程网络后无法扫描远程主机，扫描进度完成100%后，未扫描到任何资产与存活主机

### ISSUE THREAD

**Issue by pisces007** [gobysec/Goby#333]

**Comment by gobysec** [comment]
您好，开启vpn后，需要在设置页面选择vpn的网卡ip。暂不支持12tp，wireshark也无法抓取到。因此会导致未扫描到任何资产与存活主机。
您可切换socket代理扫描，此方式不走网卡。
