### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by doghuo** [gobysec/Goby#334]
发生未知错误，Goby 将尝试重启解决。若重启后错误仍存在，请反馈给我们。 Github issue

错误详情: Error
2022/08/11 10:11:26 read user rule file ok: 0
2022/08/11 10:11:26 Version: v2.0.312+alpha
2022/08/11 10:11:28 API Server listen at 127.0.0.1:8361
2022/08/11 10:11:29 127.0.0.1:50017 GET /api/v1/live

**Comment by gobysec** [comment]
您好，暂未发现有何错误，详情请添加微信：gobyteam

**Comment by LiangChen-Ye** [comment]
同款报错
error log:
2022/09/01 22:49:18 read user rule file ok: 0
2022/09/01 22:49:18 Version: v2.0.312+alpha
2022/09/01 22:49:19 API Server listen at  127.0.0.1:8361
2022/09/01 22:49:19 127.0.0.1:53846   GET   /api/v1/live
