### ISSUE TITLE
扫描报错自动退出

### ISSUE THREAD

**Issue by h34dw1nd** [gobysec/Goby#335]
环境：Windows 10 x64 18363
错误详情: Error
2022/08/15 15:08:28 read user rule file ok: 0
2022/08/15 15:08:28 Version: v2.0.312+alpha
2022/08/15 15:08:30 API Server listen at 127.0.0.1:8361
2022/08/15 15:08:30 127.0.0.1:35406 GET /api/v1/live
2022/08/15 15:08:38 127.0.0.1:35415 POST /api/v1/setEnvi
2022/08/15 15:08:39 127.0.0.1:35420 POST /api/v1/getTasks
2022/08/15 15:08:39 127.0.0.1:35419 GET /api/v1/getEnvi?
2022/08/15 15:08:39 [DEBUG] get adapter of device \Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03}
2022/08/15 15:08:39 [DEBUG] devices: [{\Device\NPF_{D046CEDC-A389-4576-B783-0727FFB0EAA2} WAN Miniport (Network Monitor) 22 []} {\Device\NPF_{168C07C0-10B7-4956-94E5-4831CC5B9AA4} WAN Miniport (IPv6) 22 []} {\Device\NPF_{3FA42FF8-ABD8-47C5-85B8-AD0002F1B84B} WAN Miniport (IP) 22 []} {\Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03} Intel(R) 82574L Gigabit Network Connection #2 22 [{fd00:6cb1:58dc:c8da::1007 ffffffffffffffffffffffffffffffff fd00:6cb1:58dc:c8da::1007 <nil>} {fd00:6cb1:58dc:c8da:6d1f:b936:9cbe:586f ffffffffffffffff0000000000000000 fd00:6cb1:58dc:c8da:ffff:ffff:ffff:ffff <nil>} {fd00:6cb1:58dc:c8da:4c08:b0dd:915f:cdcc ffffffffffffffffffffffffffffffff fd00:6cb1:58dc:c8da:4c08:b0dd:915f:cdcc <nil>} {fe80::6d1f:b936:9cbe:586f ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {192.168.88.120 ffffff00 192.168.88.255 <nil>}]} {\Device\NPF_Loopback Adapter for loopback traffic capture 55 []} {\Device\NPF_{05153752-F9C7-4845-917B-0F7B654B8446} TAP-Windows Adapter V9 38 [{fe80::a90d:8f4f:27a9:4f92 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {169.254.79.146 ffff0000 169.254.255.255 <nil>}]}]
2022/08/15 15:08:39 [DEBUG] device name is not match: \Device\NPF_{D046CEDC-A389-4576-B783-0727FFB0EAA2} != \Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03}
2022/08/15 15:08:39 [DEBUG] device name is not match: \Device\NPF_{168C07C0-10B7-4956-94E5-4831CC5B9AA4} != \Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03}
2022/08/15 15:08:39 [DEBUG] device name is not match: \Device\NPF_{3FA42FF8-ABD8-47C5-85B8-AD0002F1B84B} != \Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03}
2022/08/15 15:08:39 [DEBUG] getGatewayMac: \Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03} 0.0.0.0
2022/08/15 15:08:40 find router mac is 6c:b1:58:dc:c8:da
2022/08/15 15:08:40 [DEBUG] fetch mac address: \Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03} 6c:b1:58:dc:c8:da
2022/08/15 15:08:40 [DEBUG] close pcap handler for getGatewayMac
2022/08/15 15:08:42 127.0.0.1:35424 GET /api/v1/getEnvi?field=licenseInfo
2022/08/15 15:08:43 127.0.0.1:35425 POST /api/v1/getPOCList
2022/08/15 15:08:43 [WARNING] QueryUniqHostInfo failed: no such column: f.phash icon_hash="116323821" || body="Greetings from Spring Boot!" || body="Whitelabel Error Page"
2022/08/15 15:08:50 127.0.0.1:35426 POST /api/v1/startScan
2022/08/15 15:08:50 [WARNING] change user-agent feature is not included in your current license.
2022/08/15 15:08:50 [WARNING] change deep-analysis feature is not included in your current license.
2022/08/15 15:08:50 scan 21,22,80,U:137,U:161,443,445,U:1900,3306,3389,U:5353,8080 192.168.88.105
2022/08/15 15:08:50 start port scanner: totalSize: 12, rate: 100, connectionSize: 100, connectTimeout: 6s, retryTimes: 0, Random: true, Seed: 1660547330827557500, ScanOffset: 0, ScanICMP: false, CheckAliveMode: 2
2022/08/15 15:08:50 pcap version: Npcap version 1.55, based on libpcap version 1.10.2-PRE-GIT
2022/08/15 15:08:50 127.0.0.1:35428 POST /api/v1/getStatisticsData
2022/08/15 15:08:50 127.0.0.1:35427 POST /api/v1/getProgress
2022/08/15 15:08:50 found device from route table for 192.168.88.105: \Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03}
2022/08/15 15:08:50 [DEBUG] get adapter of device \Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03}
2022/08/15 15:08:51 [DEBUG] devices: [{\Device\NPF_{D046CEDC-A389-4576-B783-0727FFB0EAA2} WAN Miniport (Network Monitor) 22 []} {\Device\NPF_{168C07C0-10B7-4956-94E5-4831CC5B9AA4} WAN Miniport (IPv6) 22 []} {\Device\NPF_{3FA42FF8-ABD8-47C5-85B8-AD0002F1B84B} WAN Miniport (IP) 22 []} {\Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03} Intel(R) 82574L Gigabit Network Connection #2 22 [{fd00:6cb1:58dc:c8da::1007 ffffffffffffffffffffffffffffffff fd00:6cb1:58dc:c8da::1007 <nil>} {fd00:6cb1:58dc:c8da:6d1f:b936:9cbe:586f ffffffffffffffff0000000000000000 fd00:6cb1:58dc:c8da:ffff:ffff:ffff:ffff <nil>} {fd00:6cb1:58dc:c8da:4c08:b0dd:915f:cdcc ffffffffffffffffffffffffffffffff fd00:6cb1:58dc:c8da:4c08:b0dd:915f:cdcc <nil>} {fe80::6d1f:b936:9cbe:586f ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {192.168.88.120 ffffff00 192.168.88.255 <nil>}]} {\Device\NPF_Loopback Adapter for loopback traffic capture 55 []} {\Device\NPF_{05153752-F9C7-4845-917B-0F7B654B8446} TAP-Windows Adapter V9 38 [{fe80::a90d:8f4f:27a9:4f92 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {169.254.79.146 ffff0000 169.254.255.255 <nil>}]}]
2022/08/15 15:08:51 [DEBUG] device name is not match: \Device\NPF_{D046CEDC-A389-4576-B783-0727FFB0EAA2} != \Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03}
2022/08/15 15:08:51 [DEBUG] device name is not match: \Device\NPF_{168C07C0-10B7-4956-94E5-4831CC5B9AA4} != \Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03}
2022/08/15 15:08:51 [DEBUG] device name is not match: \Device\NPF_{3FA42FF8-ABD8-47C5-85B8-AD0002F1B84B} != \Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03}
2022/08/15 15:08:51 [DEBUG] getGatewayMac: \Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03} 192.168.88.105
2022/08/15 15:08:52 find router mac is 6c:b1:58:dc:c8:da
2022/08/15 15:08:53 [DEBUG] fetch mac address: \Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03} 6c:b1:58:dc:c8:da
2022/08/15 15:08:53 [DEBUG] close pcap handler for getGatewayMac
2022/08/15 15:08:53 select adapter of to send packets: &{\Device\NPF_{63650ED1-AD2D-4A82-A7A8-905BBB620D03} 192.168.88.120 [fd00:6cb1:58dc:c8da::1007 fd00:6cb1:58dc:c8da:6d1f:b936:9cbe:586f fd00:6cb1:58dc:c8da:4c08:b0dd:915f:cdcc fe80::6d1f:b936:9cbe:586f] {192.168.88.120 ffffff00} ffffff00 00:1c:42:b8:52:f2 Intel(R) 82574L Gigabit Network Connection #2 6c:b1:58:dc:c8:da}
2022/08/15 15:08:53 routine-recv start
2022/08/15 15:08:53 port scanner is ready
2022/08/15 15:08:53 routine-target run out ping target pool 2
2022/08/15 15:08:53 alive range after ping2 (1): 192.168.88.105
2022/08/15 15:08:53 routine-target is about to exit since target pool is running out
2022/08/15 15:08:53 routine-target is exit since target pool and retry pool is running out
2022/08/15 15:08:53 start first round ARP
2022/08/15 15:08:53 127.0.0.1:35431 POST /api/v1/getProgress
2022/08/15 15:08:53 127.0.0.1:35432 POST /api/v1/getStatisticsData
2022/08/15 15:08:54 3.255s 0/12 (0.00% N/A left); send: 24 7.37 pkt/s (7.37 pkt/s avg); recv: 0 0.00 pkt/s (0.00 pkt/s avg)
2022/08/15 15:08:54 routine-status is exit since status ctx is done
2022/08/15 15:08:54 found ip-mac: 192.168.88.105 - f8:ff:c2:3b:4e:fb
2022/08/15 15:08:54 found ip-mac: 192.168.88.1 - 6c:b1:58:dc:c8:da
2022/08/15 15:08:54 GrabScannerStatistics: {0 0 0 1}
2022/08/15 15:08:54 AppScannerStatistics: {0 0 0 1}
2022/08/15 15:08:55 found ip-mac: 192.168.88.105 - f8:ff:c2:3b:4e:fb
2022/08/15 15:08:55 Found port 192.168.88.105 59646 tcp
2022/08/15 15:08:55 [ERROR] got a invalid ip: [fe80::10f5:8d8c:9daf:63%以太网]
2022/08/15 15:08:56 GrabScannerStatistics: {0 1 1 1}
2022/08/15 15:08:56 AppScannerStatistics: {0 0 0 1}
2022/08/15 15:08:56 127.0.0.1:35434 POST /api/v1/getProgress
2022/08/15 15:08:56 127.0.0.1:35435 POST /api/v1/getStatisticsData
2022/08/15 15:08:57 found ip-mac: 192.168.88.109 - 22:b0:6d:ae:04:01
2022/08/15 15:08:57 found ip-mac: 192.168.88.120 - 00:1c:42:b8:52:f2
2022/08/15 15:08:57 found ip-mac: 192.168.88.100 - da:39:71:2e:bd:eb
2022/08/15 15:08:57 found ip-mac: 192.168.88.101 - ac:d6:18:19:9f:0b
2022/08/15 15:08:57 found ip-mac: 192.168.88.102 - f6:0b:4c:43:2e:2b
2022/08/15 15:08:57 found ip-mac: 192.168.88.104 - 28:7f:cf:a5:71:98
2022/08/15 15:08:57 found ip-mac: 192.168.88.109 - 22:b0:6d:ae:04:01
2022/08/15 15:08:57 found ip-mac: 192.168.88.106 - 28:7f:cf:b1:9c:bb
2022/08/15 15:08:57 found ip-mac: 192.168.88.107 - 62:4b:de:63:69:38
2022/08/15 15:08:57 found ip-mac: 192.168.88.113 - 28:7f:cf:b1:9c:bb
2022/08/15 15:08:57 found ip-mac: 192.168.88.114 - 28:7f:cf:b1:9c:bb
2022/08/15 15:08:57 found ip-mac: 192.168.88.119 - 22:b0:6d:ae:04:01
2022/08/15 15:08:57 found ip-mac: 192.168.88.125 - 28:7f:cf:a5:71:98
2022/08/15 15:08:58 found ip-mac: 192.168.88.1 - 6c:b1:58:dc:c8:da
2022/08/15 15:08:59 127.0.0.1:35436 POST /api/v1/getProgress
2022/08/15 15:08:59 127.0.0.1:35437 POST /api/v1/getStatisticsData
2022/08/15 15:09:00 BasicNetworkInfoScanner out...
2022/08/15 15:09:02 127.0.0.1:35440 POST /api/v1/getStatisticsData
2022/08/15 15:09:03 127.0.0.1:35439 POST /api/v1/getProgress
2022/08/15 15:09:03 first round ARP done
2022/08/15 15:09:04 start sending packets
2022/08/15 15:09:04 routine-send out
2022/08/15 15:09:04 Found port 192.168.88.105 5353 udp
2022/08/15 15:09:04 Found port 192.168.88.105 8080 tcp
2022/08/15 15:09:04 Found port 192.168.88.105 137 udp
2022/08/15 15:09:04 Found protocol 192.168.88.105 137 netbios
2022/08/15 15:09:04 Found protocol 192.168.88.105 5353 mdns
2022/08/15 15:09:04 Found protocol 192.168.88.105 8080 http
2022/08/15 15:09:04 Found app: 192.168.88.105 8080 JSP
2022/08/15 15:09:04 Found app: 192.168.88.105 8080 JAVA
2022/08/15 15:09:04 Found web 192.168.88.105 8080
2022/08/15 15:09:04 Found app: 192.168.88.105 8080 JSP
2022/08/15 15:09:04 Found app: 192.168.88.105 8080 JAVA
2022/08/15 15:09:04 GrabScannerStatistics: {3 4 1 1}
2022/08/15 15:09:04 AppScannerStatistics: {4 4 1 1}
2022/08/15 15:09:04 SendPacketCount: 12 12
2022/08/15 15:09:06 127.0.0.1:35448 POST /api/v1/getProgress
2022/08/15 15:09:06 127.0.0.1:35449 POST /api/v1/getStatisticsData
2022/08/15 15:09:08 found ip-mac: 192.168.88.120 - 00:1c:42:b8:52:f2
2022/08/15 15:09:09 127.0.0.1:35451 POST /api/v1/getProgress
2022/08/15 15:09:09 127.0.0.1:35452 POST /api/v1/getStatisticsData
2022/08/15 15:09:09 start another round ARP
2022/08/15 15:09:09 found ip-mac: 192.168.88.105 - f8:ff:c2:3b:4e:fb
2022/08/15 15:09:09 found ip-mac: 192.168.88.1 - 6c:b1:58:dc:c8:da
2022/08/15 15:09:12 127.0.0.1:35456 POST /api/v1/getProgress
2022/08/15 15:09:12 127.0.0.1:35457 POST /api/v1/getStatisticsData
2022/08/15 15:09:12 found ip-mac: 192.168.88.100 - da:39:71:2e:bd:eb
2022/08/15 15:09:12 found ip-mac: 192.168.88.101 - ac:d6:18:19:9f:0b
2022/08/15 15:09:12 found ip-mac: 192.168.88.104 - 28:7f:cf:a5:71:98
2022/08/15 15:09:14 close pcap sender
2022/08/15 15:09:14 routine-recv out
2022/08/15 15:09:15 127.0.0.1:35460 POST /api/v1/getStatisticsData
2022/08/15 15:09:15 127.0.0.1:35459 POST /api/v1/getProgress
2022/08/15 15:09:15 routine-pcap-sender is exit
panic: send error: PacketSendPacket failed: �����Ч�� (6)
goroutine 140 [running]:
git.gobies.org/goby/portscanner/pcapsend.(*PcapSender).SendARP(0xc005f5a630, {0xc003d69b10, 0x4, 0x4})
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/pcapsend/send.go:1391 +0x3f4
git.gobies.org/goby/portscanner/pcapsend.(*PcapSender).sendArpIfNeed(0xc005f5a630, {0x1433db6e0, 0xc000fea780}, 0xc002e34370)
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/pcapsend/send.go:1514 +0x485
git.gobies.org/goby/portscanner/pcapsend.(*PcapSender).SendPackets.func2()
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/pcapsend/send.go:1557 +0x105
created by git.gobies.org/goby/portscanner/pcapsend.(*PcapSender).SendPackets
git.gobies.org/goby/portscanner@v0.0.0-20201203091042-47e62b76135f/pcapsend/send.go:1548 +0x1aa

**Comment by gobysec** [comment]
请勿使用npcap1.7版本，请下载npcap1.6版本，安装时勾选管理员权限。
方便的话麻烦您添加下微信：gobyteam
