### ISSUE TITLE
mac m1 启动goby扫描报错

### ISSUE THREAD

**Issue by nice1er** [gobysec/Goby#338]
[scan_error.log](https://github.com/gobysec/Goby/files/9430518/scan_error.log)
<img width="922" alt="image" src="https://user-images.githubusercontent.com/48083265/186840552-27db2754-5db8-4b8d-96bb-da3d9a5d1681.png">

**Comment by gobysec** [comment]
是否有开启vpn，需要选择vpn的网卡ip
