### ISSUE TITLE
需求反馈

### ISSUE THREAD

**Issue by LivingXu** [gobysec/Goby#339]
请问是否可以考虑增加以下功能：
①通过API来建立扫描任务；
②为扫描设置定时任务；
③通过API或者Syslog来获取扫描结果。
十分感谢！

**Comment by gobysec** [comment]
1. 可命令行启动golib目录下的goby-cmd，查看-h获取帮助
2. 定时任务可在插件市场中下载task queue插件实现你所需的功能
3. 日志可在data/logs/scan_error查看扫描结果，或是goby-cmd也可获取日志。

**Comment by LivingXu** [comment]
> 1. 可命令行启动golib目录下的goby-cmd，查看-h获取帮助
> 
>     2. 定时任务可在插件市场中下载task queue插件实现你所需的功能
> 
>     3. 日志可在data/logs/scan_error查看扫描结果，或是goby-cmd也可获取日志。

十分感谢，但第三个功能中是否可以导出excel格式的资产结果呢？
