### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by lemonbensad** [gobysec/Goby#34]
你好，我在win ser 2008上运行，出现如下报错。
<img width="1156" alt="WX20200325-113457@2x" src="https://user-images.githubusercontent.com/54904232/77499576-73c5ac00-6e8d-11ea-8df3-4b60643ea80f.png">

**Comment by gobysec** [comment]
> 你好，我在win ser 2008上运行，出现如下报错。
> <img alt="WX20200325-113457@2x" width="1156" src="https://user-images.githubusercontent.com/54904232/77499576-73c5ac00-6e8d-11ea-8df3-4b60643ea80f.png">

你好，方便加群详聊吗？https://t.me/gobies

**Comment by gobysec** [comment]
该问题已经解决，win2008存在网卡问题。换win7或win10即可。
