### ISSUE TITLE
error

### ISSUE THREAD

**Issue by grayes** [gobysec/Goby#340]
2022/08/30 15:18:58 read user rule file ok: 0
2022/08/30 15:18:58 Version: v2.0.312+alpha
2022/08/30 15:19:00 API Server listen at 127.0.0.1:8361
2022/08/30 15:19:00 127.0.0.1:31765 GET /api/v1/live

**Comment by gobysec** [comment]
根据您提供的信息只能推断您是否有开启系统代理，需要删除环境变量。若无法解决，请联系微信：gobyteam
