### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 1158434020** [gobysec/Goby#341]
2022/09/02 14:43:45 read user rule file ok: 0
2022/09/02 14:43:45 Version: v2.0.312+alpha
2022/09/02 14:43:46 API Server listen at  127.0.0.1:8361
2022/09/02 14:43:46 127.0.0.1:12041   GET   /api/v1/live  
2022/09/02 14:43:54 127.0.0.1:12048   POST   /api/v1/setEnvi  
2022/09/02 14:43:54 127.0.0.1:12050   POST   /api/v1/getTasks  
2022/09/02 14:43:54 127.0.0.1:12049   GET   /api/v1/getEnvi?  
2022/09/02 14:43:56 [DEBUG] get adapter of device \Device\NPF_{DAC2A61A-15E5-42F1-854D-D492215C68B8}
2022/09/02 14:43:56 [DEBUG] devices:  [{\Device\NPF_{545145E6-36DB-4ABC-BB1B-D3F5BE70760A} VMware Virtual Ethernet Adapter 22 [{fe80::8104:67f3:1815:9d3d <nil> <nil> <nil>} {192.168.26.1 ffffff00 255.255.255.255 <nil>}]} {\Device\NPF_{959A95F6-804A-47F3-BD5B-BD7966134A0F} VMware Virtual Ethernet Adapter 22 [{fe80::357b:3a3b:680e:c500 <nil> <nil> <nil>} {192.168.88.1 ffffff00 255.255.255.255 <nil>}]} {\Device\NPF_{4445DCEB-579C-4FB4-B1DA-D3DFABAD183C} MS NDIS 6.0 LoopBack Driver 22 [{fe80::b82c:5399:1c45:2b29 <nil> <nil> <nil>} {0.0.0.0 ff000000 255.255.255.255 <nil>}]} {\Device\NPF_{B941B013-3C8E-46CB-A59C-B1CC0D85846F} NdisWan Adapter 22 []} {\Device\NPF_{F8782FA9-E806-4C4E-AA7B-0D5606BE6CCE} NdisWan Adapter 22 []} {\Device\NPF_{B204122A-CDC6-4F29-B4F5-4D360CD1741F} Microsoft 46 [{fe80::80cb:a85c:d93b:45a4 <nil> <nil> <nil>} {fe80::80cb:a85c:d93b:45a4 <nil> <nil> <nil>}]} {\Device\NPF_{7B44A613-2F5A-4A9B-A4E2-92637DBCBFDB} Oracle 22 [{fe80::7823:fa37:5fa3:412b <nil> <nil> <nil>} {192.168.56.1 ffffff00 255.255.255.255 <nil>}]} {\Device\NPF_{646ED9CF-0A71-44C9-A4EB-B667876CFBE7} Microsoft 46 [{fe80::d19a:d14a:8690:885e <nil> <nil> <nil>} {fe80::d19a:d14a:8690:885e <nil> <nil> <nil>}]} {\Device\NPF_{DAC2A61A-15E5-42F1-854D-D492215C68B8} Microsoft 30 [{fe80::a0e3:bca0:dc8a:e682 <nil> <nil> <nil>} {fd74:ae1:2802:e800:4429:6773:bdad:e80b <nil> <nil> <nil>} {240e:878:0:e7f5:4429:6773:bdad:e80b <nil> <nil> <nil>} {fd74:ae1:2802:e800:a0e3:bca0:dc8a:e682 <nil> <nil> <nil>} {240e:878:0:e7f5:a0e3:bca0:dc8a:e682 <nil> <nil> <nil>} {240e:878:0:e7f5:740a:e128:2e8:2 <nil> <nil> <nil>} {192.168.8.112 ffffff00 255.255.255.255 <nil>}]} {\Device\NPF_{493AE1A7-768C-483A-B442-43B5629EC080} NdisWan Adapter 22 []} {\Device\NPF_{0C4A597C-75FB-4B0E-AF78-DAE2C7AB0123} Microsoft 46 [{fe80::2c8b:7609:f0fa:bb15 <nil> <nil> <nil>} {fe80::2c8b:7609:f0fa:bb15 <nil> <nil> <nil>}]} {\Device\NPF_{55614033-9271-451D-BBC1-B6907D9A13B6} Realtek Gaming GbE Family Controller 38 [{fe80::24ed:3206:fc39:a72a <nil> <nil> <nil>} {fe80::24ed:3206:fc39:a72a <nil> <nil> <nil>}]}]
2022/09/02 14:43:56 [DEBUG] device name is not match: \Device\NPF_{545145E6-36DB-4ABC-BB1B-D3F5BE70760A} != \Device\NPF_{DAC2A61A-15E5-42F1-854D-D492215C68B8}
2022/09/02 14:43:56 [DEBUG] device name is not match: \Device\NPF_{959A95F6-804A-47F3-BD5B-BD7966134A0F} != \Device\NPF_{DAC2A61A-15E5-42F1-854D-D492215C68B8}
2022/09/02 14:43:56 [DEBUG] device name is not match: \Device\NPF_{4445DCEB-579C-4FB4-B1DA-D3DFABAD183C} != \Device\NPF_{DAC2A61A-15E5-42F1-854D-D492215C68B8}
2022/09/02 14:43:56 [DEBUG] device name is not match: \Device\NPF_{B941B013-3C8E-46CB-A59C-B1CC0D85846F} != \Device\NPF_{DAC2A61A-15E5-42F1-854D-D492215C68B8}
2022/09/02 14:43:56 [DEBUG] device name is not match: \Device\NPF_{F8782FA9-E806-4C4E-AA7B-0D5606BE6CCE} != \Device\NPF_{DAC2A61A-15E5-42F1-854D-D492215C68B8}
2022/09/02 14:43:56 [DEBUG] device name is not match: \Device\NPF_{B204122A-CDC6-4F29-B4F5-4D360CD1741F} != \Device\NPF_{DAC2A61A-15E5-42F1-854D-D492215C68B8}
2022/09/02 14:43:56 [DEBUG] device name is not match: \Device\NPF_{7B44A613-2F5A-4A9B-A4E2-92637DBCBFDB} != \Device\NPF_{DAC2A61A-15E5-42F1-854D-D492215C68B8}
2022/09/02 14:43:56 [DEBUG] device name is not match: \Device\NPF_{646ED9CF-0A71-44C9-A4EB-B667876CFBE7} != \Device\NPF_{DAC2A61A-15E5-42F1-854D-D492215C68B8}
2022/09/02 14:43:56 [DEBUG] getGatewayMac: \Device\NPF_{DAC2A61A-15E5-42F1-854D-D492215C68B8} 0.0.0.0
2022/09/02 14:43:58 find router mac is  74:0a:e1:28:02:e8
2022/09/02 14:43:58 [DEBUG] fetch mac address: \Device\NPF_{DAC2A61A-15E5-42F1-854D-D492215C68B8} 74:0a:e1:28:02:e8
2022/09/02 14:43:58 [DEBUG] close pcap handler for getGatewayMac

**Comment by gobysec** [comment]
此日志并未有报错内容，请添加微信：gobyteam
