### ISSUE TITLE
发生未知错误

### ISSUE THREAD

**Issue by Uconquer** [gobysec/Goby#347]
![image](https://user-images.githubusercontent.com/53113017/190844081-a2dd08cf-034b-4fb9-a112-e12e1973a9cb.png)

**Comment by gobysec** [comment]
服务中断/未知错误
可能存在以下原因：

1.速率过高导致丢包引起的服务中断。解决方法：关掉弹窗后自动重连，后续扫描请适当降低扫描速率。

2.后端崩溃引起的错误，请您联系官方微信号：gobyteam，我们会尽快为您解决
