### ISSUE TITLE
windows11专业版

### ISSUE THREAD

**Issue by 1fvyuio333** [gobysec/Goby#348]
突然无法使用，报错如下

Warning

An unknown error occurs, Goby will try to restart and solve it. If the error still exists after the restart, please feed it back to us. Github issue

Error details: Error
2022/09/19 15:25:46 Version: v2.0.312+alpha
2022/09/19 15:25:47 API Server listen at 127.0.0.1:8361
2022/09/19 15:25:47 [ERROR] API Server exit: listen tcp 127.0.0.1:8361: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by gobysec** [comment]
服务中断/未知错误
可能存在以下原因：

1.速率过高导致丢包引起的服务中断。解决方法：关掉弹窗后自动重连，后续扫描请适当降低扫描速率。

2.后端崩溃引起的错误，请您联系官方微信号：gobyteam，我们会尽快为您解决
