### ISSUE TITLE
goby当电脑有两个网卡工作时扫描出错

### ISSUE THREAD

**Issue by l1TTss** [gobysec/Goby#35]
goby开发人员你们好：
        我的笔记本电脑使用你们的goby做扫描时，发现一个问题。我的电脑有无线网卡和有线网卡，外网默认路由在无线网卡上的，内网接入有线网卡，内网业务系统能与有线网卡通。网络是没问题的。我在使用goby扫描内网业务系统时，扫描界面显示的是有线网卡的IP，但扫描内网业务网段出现了报错，扫描无法执行，通过goby配置选择了有线网卡依然无法解决该问题，以下我附上日志文件，还请帮忙分析，更新goby解决电脑两个网卡工作导致无法顺利扫描的问题，谢谢。日志文件如下：
2020/03/20 12:46:31 Grab version:  grab_version_1.5
2020/03/20 12:46:31 Support 237  protocols, 350  ports
2020/03/20 12:46:31 Version: v1.15.120+beta
2020/03/20 12:46:31 API Server listen at  127.0.0.1:8361
2020/03/20 12:46:34 127.0.0.1:12211   GET   /api/v1/live  
2020/03/20 12:46:35 127.0.0.1:12291   GET   /api/v1/tasks  
2020/03/20 12:46:35 127.0.0.1:12292   GET   /api/v1/listSupport  
2020/03/20 12:46:35 127.0.0.1:12293   GET   /api/v1/getEnvi  
2020/03/20 12:46:40 127.0.0.1:14925   GET   /api/v1/tasks  
2020/03/20 12:46:46 [DEBUG] close doneCh
2020/03/20 12:46:46 [DEBUG] getGatewayMac out
2020/03/20 12:46:50 127.0.0.1:22709   POST   /api/v1/deleteTask  
2020/03/20 12:46:50 127.0.0.1:22730   GET   /api/v1/tasks  
2020/03/20 12:46:59 127.0.0.1:30886   POST   /api/v1/deleteTask  
2020/03/20 12:46:59 127.0.0.1:30891   GET   /api/v1/tasks  
2020/03/20 12:47:03 127.0.0.1:34288   POST   /api/v1/deleteTask  
2020/03/20 12:47:03 127.0.0.1:34297   GET   /api/v1/tasks  
2020/03/20 12:47:06 127.0.0.1:38991   POST   /api/v1/deleteTask  
2020/03/20 12:47:06 127.0.0.1:39003   GET   /api/v1/tasks  
2020/03/20 12:47:13 127.0.0.1:51117   POST   /api/v1/getStatisticsData  
2020/03/20 12:47:15 127.0.0.1:55348   POST   /api/v1/vulnerabilityStatisticsData  
2020/03/20 12:47:15 127.0.0.1:55350   POST   /api/v1/vulnerabilitySearch  
2020/03/20 12:47:19 127.0.0.1:61093   POST   /api/v1/assetSearch  
2020/03/20 12:47:19 127.0.0.1:61094   POST   /api/v1/getValueCategory  
2020/03/20 12:47:20 127.0.0.1:62302   POST   /api/v1/getStatisticsData

**Comment by gobysec** [comment]
初步分析可能和网卡无关，多个网卡的问题我们之前已处理过。您使用的是goby1.6.104版本还是1.6.116版本? 1.6.116有解决掉因为某个漏洞导致扫描崩溃及大量IP扫描崩溃的问题。不知道您的扫描崩溃是否是以上两个问题，是否方便将脱敏后的完整日志发过来呢？

**Comment by l1TTss** [comment]
> 初步分析可能和网卡无关，多个网卡的问题我们之前已处理过。您使用的是goby1.6.104版本还是1.6.116版本? 1.6.116有解决掉因为某个漏洞导致扫描崩溃及大量IP扫描崩溃的问题。不知道您的扫描崩溃是否是以上两个问题，是否方便将脱敏后的完整日志发过来呢？

您好，我用的是goby1.6.104版本的，可能是由于某个漏洞导致扫描崩溃及大量IP扫描崩溃的问题，我暂时先更新用goby1.6.116的版本试用看，到时再反馈您相关情况，谢谢。
