### ISSUE TITLE
软件发生未知的错误

### ISSUE THREAD

**Issue by gitchisaka** [gobysec/Goby#350]
最近使用goby的时候打开，提示发生未知的错误。提示的日志。
```
2022/09/26 18:25:01 read user rule file ok: 0
2022/09/26 18:25:01 Version: v2.0.312+alpha
2022/09/26 18:25:06 API Server listen at  127.0.0.1:8361
```

![goby](https://user-images.githubusercontent.com/105700902/192255030-76418328-d09c-437a-9a8d-9f8c1df834ec.png)

**Comment by gitchisaka** [comment]
goby version 2.0.5

**Comment by 89BaJiu** [comment]
我也出现了这个错误

**Comment by gobysec** [comment]
服务中断/未知错误
可能存在以下原因：

1.速率过高导致丢包引起的服务中断。解决方法：关掉弹窗后自动重连，后续扫描请适当降低扫描速率。

2.后端崩溃引起的错误，请您联系官方微信号：gobyteam，我们会尽快为您解决

https://gobysec.net/faq#%E7%83%AD%E7%82%B9%E9%97%AE%E9%A2%98
