### ISSUE TITLE
goby启动报错

### ISSUE THREAD

**Issue by 0823-zxt** [gobysec/Goby#352]
\Device\NPF_{CCE450B0-DD71-4B5A-8746-1E2BE2BE07B8}: failed to set hardware filter to promiscuous mode: ����ϵͳ�ϵ��豸û�з������á� (31)

**Comment by gobysec** [comment]
您好，此问题是由于npcap1.7版本不兼容导致，请重装npcap1.6版本，安装时勾选管理员权限。感谢您的支持与反馈~

**Comment by 0823-zxt** [comment]
谢谢，已经解决了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月20日(星期四) 上午10:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gobysec/Goby] goby启动报错 (Issue #352)





 
您好，此问题是由于npcap1.7版本不兼容导致，请重装npcap1.6版本，安装时勾选管理员权限。感谢您的支持与反馈~

**Comment by liu790** [comment]
。。。为啥我一直能用，但是突然就不行了，报的也是这个错
