### ISSUE TITLE
Goby 插件上传失败：README file does not exist 或 err

### ISSUE THREAD

**Issue by 0xn0ne** [gobysec/Goby#353]
**问题报错**

选择压缩包上传插件后报：README file does not exist

![image](https://user-images.githubusercontent.com/16507416/195489258-2763238d-46ae-4f34-abe1-d1be3dfbf75b.png)

**排查过程**

刚开始我是这么打包的，整个插件文件夹打包进去，说找不到 README.md，报：README file does not exist

![image](https://user-images.githubusercontent.com/16507416/195489352-65375059-155f-4c18-ae8e-f083a1cd41be.png)

![image](https://user-images.githubusercontent.com/16507416/195489258-2763238d-46ae-4f34-abe1-d1be3dfbf75b.png)

我以为是 README_EN.md 的问题，删掉 README_EN.md  重新上传，报：README file does not exist

![image](https://user-images.githubusercontent.com/16507416/195489569-a6957609-9c90-4ee9-ab58-85a0395e8d3e.png)

我以为是不能打包整个插件根文件夹的问题，不打包根文件夹了，报：README file does not exist

![image](https://user-images.githubusercontent.com/16507416/195489841-6e1fc1d1-bb3e-44b7-93d7-fef2385580a1.png)

再试一下删掉 README_EN.md ，报：README file does not exist，卒

![image](https://user-images.githubusercontent.com/16507416/195490137-c06ac558-ab4f-4015-bc54-ef0ed50d96be.png)

上次给我发邮件的老哥加你的时候有手机号验证，换个号我们排查一下？或者用这个 https://github.com/0xn0ne/RelaxHelper 手动npm安装依赖后就是原插件

**Comment by clddup** [comment]
添加微信: gobyteam  联系gobybot

**Comment by clddup** [comment]
> **问题报错**
> 
> 选择压缩包上传插件后报：README file does not exist
> 
> ![image](https://user-images.githubusercontent.com/16507416/195489258-2763238d-46ae-4f34-abe1-d1be3dfbf75b.png)
> 
> **排查过程**
> 
> 刚开始我是这么打包的，整个插件文件夹打包进去，说找不到 README.md，报：README file does not exist
> 
> ![image](https://user-images.githubusercontent.com/16507416/195489352-65375059-155f-4c18-ae8e-f083a1cd41be.png)
> 
> ![image](https://user-images.githubusercontent.com/16507416/195489258-2763238d-46ae-4f34-abe1-d1be3dfbf75b.png)
> 
> 我以为是 README_EN.md 的问题，删掉 README_EN.md 重新上传，报：README file does not exist
> 
> ![image](https://user-images.githubusercontent.com/16507416/195489569-a6957609-9c90-4ee9-ab58-85a0395e8d3e.png)
> 
> 我以为是不能打包整个插件根文件夹的问题，不打包根文件夹了，报：README file does not exist
> 
> ![image](https://user-images.githubusercontent.com/16507416/195489841-6e1fc1d1-bb3e-44b7-93d7-fef2385580a1.png)
> 
> 再试一下删掉 README_EN.md ，报：README file does not exist，卒
> 
> ![image](https://user-images.githubusercontent.com/16507416/195490137-c06ac558-ab4f-4015-bc54-ef0ed50d96be.png)
> 
> 上次给我发邮件的老哥加你的时候有手机号验证，换个号我们排查一下？或者用这个 https://github.com/0xn0ne/RelaxHelper 手动npm安装依赖后就是原插件

压缩包名字和里面文件夹名字要一致

**Comment by 0xn0ne** [comment]
弄好了，要把目录结构和文件写好，部分地方用的是相对路径要注意一下这点
![image](https://user-images.githubusercontent.com/16507416/198962488-7d711e5f-6c24-4fc7-b494-3b2e6df38b4b.png)
