### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by Memorz** [gobysec/Goby#355]
win11启动goby时报错   重启好多次也不行
![image](https://user-images.githubusercontent.com/64755389/196994285-adac1b71-b31a-47cc-8ac0-85cb40893491.png)
错误日志：
2022/10/20 23:37:13 read user rule file ok: 0
2022/10/20 23:37:13 Version: v2.0.312+alpha
2022/10/20 23:37:14 API Server listen at  127.0.0.1:8361
2022/10/20 23:37:15 127.0.0.1:5556   GET   /api/v1/live

**Comment by gobysec** [comment]
请检查您是否开启了代理环境，若没有解决，请添加微信：gobyteam，感谢您的支持与反馈~

**Comment by gobysec** [comment]
未看到完整错误，请详细描述您的问题，报错截图、使用版本、系统号、报错日志。
请联系微信号：gobyteam，为您解决~
