### ISSUE TITLE
发生未知错误，Goby 将尝试重启解决。若重启后错误仍存在，请反馈给我们

### ISSUE THREAD

**Issue by history1512** [gobysec/Goby#356]
Error
2022/10/25 10:30:01 read user rule file ok: 0
2022/10/25 10:30:01 Version: v2.0.312+alpha
2022/10/25 10:30:02 API Server listen at 127.0.0.1:8361
2022/10/25 10:30:02 [ERROR] API Server exit: listen tcp 127.0.0.1:8361: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
2022/10/25 10:30:02 [StartService ERROR] {content："server bind failed", errCode: 0}
panic: listen tcp 127.0.0.1:8361: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
goroutine 8 [running]:
git.gobies.org/goby/goby/api.StartAPIServer.func1()
git.gobies.org/goby/goby/api/api.go:322 +0x127
created by git.gobies.org/goby/goby/api.StartAPIServer
git.gobies.org/goby/goby/api/api.go:308 +0x148

**Comment by gobysec** [comment]
goby-cmd监听时报错：`panic: listen tcp 127.0.0.1:8361: bind: An attempt was made to access a socket in a way forbidden by its access permissions`。 以管理员权限运行Goby，8361端口也没被占用， 防火墙也关了，但还是报这个错。解决方法：

```
net stop winnat
netsh int ipv4 add excludedportrange protocol=tcp startport=8361 numberofports=1
net start winnat
```
出现这种情况，可能是开了hyper-v

**Comment by sonumb-z** [comment]
2023/11/27 21:14:55 goby.Start.LoadCustomRules() err: open D:\xxx\goby-win-x64-2.7.9-Community\goby-win-x64-2.7.9\golib\rules\user\cdn-header-rule.json: The system cannot find the file specified.

**Comment by gobysec** [comment]
您可以添加微信:gobyteam，为您远程定位问题，感谢您的支持与反馈~

sonumb-z ***@***.***> 于2023年11月27日周一 21:16写道：

**Comment by varzhang** [comment]
Error
2024/03/20 14:54:25 read user rule file ok: 0
2024/03/20 14:54:25 Version: v2.0.321 beta
2024/03/20 14:54:26 API Server listen at 127.0.0.1:8361
2024/03/20 14:54:26 127.0.0.1:62519 GET /api/v1/live
2024/03/20 14:54:36 127.0.0.1:62540 POST /api/v1/setEnvi
2024/03/20 14:54:36 127.0.0.1:62544 GET /api/v1/getEnvi?
2024/03/20 14:54:36 127.0.0.1:62545 POST /api/v1/getTasks
2024/03/20 14:54:36 [DEBUG] get adapter of device \Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4}
2024/03/20 14:54:36 [DEBUG] devices: [{\Device\NPF_{CDF41D2F-16B5-431F-9BFB-E07A67953D58} WAN Miniport (Network Monitor) 22 []} {\Device\NPF_{D3CE0D76-3E52-4FBF-88B8-FF4575D1FB34} WAN Miniport (IPv6) 22 []} {\Device\NPF_{BDE1772D-3F1B-4CF9-A6A6-2FF8F7E0C1A9} WAN Miniport (IP) 22 []} {\Device\NPF_{9E4C0B3A-AEBF-49A1-890C-871E3534DC2F} VMware Virtual Ethernet Adapter for VMnet8 22 [{192.168.217.1 ffffff00 192.168.217.255 <nil>} {fe80::e468:1abc:e4a8:79e6 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{65F1FCD8-C67F-44D2-B35B-7378F01060E0} VMware Virtual Ethernet Adapter for VMnet1 22 [{192.168.52.1 ffffff00 192.168.52.255 <nil>} {fe80::b918:e879:4f45:b91a ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{C57839E1-4008-4FE3-B100-C255F3764718} Intel(R) Wi-Fi 6 AX203 30 [{10.10.20.185 ffffff00 10.10.20.255 <nil>} {fe80::daa5:9829:6a44:403f ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{DB9949E5-E9F6-420D-9548-10D7DE1EF697} Microsoft Wi-Fi Direct Virtual Adapter #2 46 [{169.254.87.100 ffff0000 169.254.255.255 <nil>} {fe80::7e0c:e4a3:687a:13f6 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{3BF452B6-0581-49DF-8AD7-0A504C50FE7B} Microsoft Wi-Fi Direct Virtual Adapter 46 [{169.254.37.41 ffff0000 169.254.255.255 <nil>} {fe80::a5a9:30d9:f13d:df8c ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{78597159-5EBC-46AA-9119-87CB605492F3} VirtualBox Host-Only Ethernet Adapter #2 22 [{192.168.56.2 ffffff00 192.168.56.255 <nil>} {fe80::a863:24cd:614a:c3e3 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{256936B9-89F3-4C25-B95D-74F4C5BB778A} VirtualBox Host-Only Ethernet Adapter 22 [{192.168.56.1 ffffff00 192.168.56.255 <nil>} {fe80::2536:74f0:271e:c7d2 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{44393EFC-29C4-25E4-B684-F168B398A2B4} Clash Tunnel 22 [{198.18.0.1 ffff0000 198.18.255.255 <nil>}]} {\Device\NPF_Loopback Adapter for loopback traffic capture 55 [{::1 ffffffffffffffffffffffffffffffff <nil> <nil>} {127.0.0.1 ff000000 <nil> <nil>}]}]

**Comment by L5X5I** [comment]
服务中断。

发生错误。程序遇到了意外的错误终止了，请重启程序。我们深表歉意给您带来的不便。如果您有任何疑问，请联系我们。

panic: close of closed channel

goroutine 2419 [running]:
github.com/chromedp/chromedp.(*ExecAllocator).Allocate.func2()
	github.com/chromedp/chromedp@v0.8.2/allocate.go:224 +0xc5
created by github.com/chromedp/chromedp.(*ExecAllocator).Allocate in goroutine 143
	github.com/chromedp/chromedp@v0.8.2/allocate.go:210 +0xbe9
