### ISSUE TITLE
Goby报错

### ISSUE THREAD

**Issue by sqws651515** [gobysec/Goby#357]
MACOS 添加远端 goby-cmd服务器后，扫描一次任务后便无限报错。。。

发生未知错误，Goby 将尝试重启解决。若重启后错误仍存在，请反馈给我们。 Github issue

错误详情: Error
-

<img width="543" alt="image" src="https://user-images.githubusercontent.com/101343301/198236784-9d03a13e-f4b6-45b5-80bd-4d17e3fabb7a.png">

**Comment by gobysec** [comment]
您可以添加微信：gobyteam，详情阐述您的问题，我们会尽快为您解决，感谢您的支持与反馈~
