### ISSUE TITLE
ip 和 域名为啥不能同时导出，导出后还要手动处理，鸡肋。

### ISSUE THREAD

**Issue by cahris** [gobysec/Goby#362]

**Comment by cahris** [comment]
图形界面，一言难尽，返回页面能不能，不每次跳转到第一页。数据选择优化一下容易多选数据，稍微不慎还会跳转到详情页面，返回加载数据太慢了，用户体验不合格。

**Comment by gobysec** [comment]
您可以添加微信：gobyteam，详情阐述您的问题，我们会尽快为您解决，感谢您的支持与反馈~
