### ISSUE TITLE
goby远程服务器问题

### ISSUE THREAD

**Issue by ccc-f** [gobysec/Goby#372]
如果指定goby服务器为远程服务器，一旦本地 goby 无法连接设置在 vps 上的 goby Linux 服务器，打开本地 goby 就会无限报错，无法从新设置 goby 服务器，重启也没有用，必须恢复与远程 goby 服务器的连接或者重新安装 goby 或者本地goby删除配置文件才能正常打开。

**Comment by gobysec** [comment]
此问题正在解决中，若有进展，会通知您并关闭此issue

**Comment by gobysec** [comment]
问题已于Goby2.4.9解决
