### ISSUE TITLE
这是什么问题，重启不管用

### ISSUE THREAD

**Issue by rechallage** [gobysec/Goby#373]
![图片](https://user-images.githubusercontent.com/85208463/206976504-0bf0470c-a8f2-4a93-b3f2-263644e84774.png)

**Comment by lxghost** [comment]
同样的问题

**Comment by gobysec** [comment]
这个时统一的后端崩溃的错误，需要查看错误字段panic，上文提供信息不全无法判断问题，可添加温馨：gobyteam
