### ISSUE TITLE
这是怎么回事啊大哥们

### ISSUE THREAD

**Issue by 15034048812** [gobysec/Goby#376]
求解决方法 ！！！求解决方法 ！！！求解决方法 ！！！求解决方法 ！！！求解决方法 ！！！求解决方法 ！！！求解决方法 ！！！求解决方法 ！！！求解决方法 ！！！

![image](https://user-images.githubusercontent.com/50392739/208437725-e19589d7-b712-428c-b8f9-b0fdc0b03bc3.png)
![image](https://user-images.githubusercontent.com/50392739/208437815-28e6455b-cd23-4dce-aa64-0a5c59c79919.png)
![image](https://user-images.githubusercontent.com/50392739/208437830-135f24ea-4e71-4a9d-a5f1-a56f0b0a33bb.png)

**Comment by gobysec** [comment]
重装npcap1.6版本 安装时勾选管理员权限。1.7版本不兼容，有重复问题啦
