### ISSUE TITLE
建议将Windows版本中的goby-cmd.exe改为64位程序

### ISSUE THREAD

**Issue by dongpohezui** [gobysec/Goby#377]
goby-win-x64-2.1.3-Community版本及其他Windows版本中，goby-cmd.exe为32位程序。
但是，goby-linux-x64-2.1.3-Community版本及其他Linux版本中，goby-cmd-linux为64位程序。
建议将Windows版本中的goby-cmd.exe改为64位程序。

![2022-12-20_174110](https://user-images.githubusercontent.com/40270581/208637154-9f0f08b2-562e-4415-8c19-d5541a1e7e6f.png)

![2022-12-20_174007](https://user-images.githubusercontent.com/40270581/208637214-09f67a1e-c481-411e-be8f-63a3c6dad9b2.png)

**Comment by gobysec** [comment]
非常感谢您的反馈，已定位到原因，正在修改~
