### ISSUE TITLE
警告

### ISSUE THREAD

**Issue by Wang-yueling** [gobysec/Goby#386]
发生未知错误，Goby 将尝试重启解决。若重启后错误仍存在，请反馈给我们。 Github issue
错误详情: Error
2023/01/05 16:16:01 read user rule file ok: 0
2023/01/05 16:16:01 Version: v2.0.317 beta
2023/01/05 16:16:02 API Server listen at 127.0.0.1:8361
2023/01/05 16:16:02 127.0.0.1:3236 GET /api/v1/live
2023/01/05 16:16:03 127.0.0.1:3237 POST /api/v1/setEnvi
2023/01/05 16:16:03 127.0.0.1:3240 GET /api/v1/getEnvi?field=gid,key,godserver
2023/01/05 16:16:03 127.0.0.1:3239 GET /api/v1/getEnvi?field=ip
2023/01/05 16:16:03 127.0.0.1:3238 GET /api/v1/getEnvi?field=chromePath,dataIntegrity,datadir,dir,midKey,proxyServer,userRuleSize,vulVersion

**Comment by Wang-yueling** [comment]
版本:2.1.3
![图片](https://user-images.githubusercontent.com/117903472/210744610-be99b11f-4682-497a-bc86-cb77c5c8e630.png)

**Comment by gobysec** [comment]
暂未遇到过此问题，请添加微信：gobyteam，详聊。感谢您的反馈与支持~
