### ISSUE TITLE
警告：网络是否有问题？

### ISSUE THREAD

**Issue by Lambda223** [gobysec/Goby#387]
![图片](https://user-images.githubusercontent.com/63716791/211232121-b2cc7140-1d98-4490-9a6f-82b8f9c8ed1f.png)
![图片](https://user-images.githubusercontent.com/63716791/211232132-2cfff7f5-9798-46fc-877c-f70e1ce05826.png)

**Comment by gobysec** [comment]
请添加微信：gobyteam，为您解决
