### ISSUE TITLE
win10下最新版本error query

### ISSUE THREAD

**Issue by ximiluliyi** [gobysec/Goby#39]
之前的版本没问题，提示我更新后，下载最新版本1.6.116下载完成后运行一直提示error quert 网卡也调试过了，还是报错：
![image](https://user-images.githubusercontent.com/40221289/79684812-d92b7380-8266-11ea-81bb-974bfa253c41.png)
报错：
![image](https://user-images.githubusercontent.com/40221289/79684828-ea748000-8266-11ea-99ef-8c927f15392e.png)
这是网卡后也一样报错...

**Comment by ximiluliyi** [comment]
已解决~

**Comment by blockchainguard** [comment]
@ximiluliyi   您好是怎么解决的呢？
