### ISSUE TITLE
goby提示网络故障，请稍后重试

### ISSUE THREAD

**Issue by 4319083** [gobysec/Goby#391]
早上还可以用,下午就一直提示网络故障,网卡重新装了,npcap也重新装了 就是没有网络
![image](https://user-images.githubusercontent.com/100462029/216652093-04896459-c0c7-4ccb-9ac0-846f8d7c9a54.png)

**Comment by gobysec** [comment]
网络故障，不影响扫描，请检查是否可以访问Goby官网。
https://gobysec.net
https://gobies.org

请联系微信号：gobyteam，我们会尽快为您解决~

**Comment by Acesc** [comment]
hosts文件goby的全干掉
