### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by wkend** [gobysec/Goby#394]
2023/02/08 21:06:42 [DEBUG] devices:  [{\Device\NPF_{CC88C1C1-F5A4-4EC6-BBD2-7DC60302CC00} WAN Miniport (Network Monitor) 22 []} {\Device\NPF_{463F11A8-ABB9-4E54-8B29-B238E2391D25} WAN Miniport (IPv6) 22 []} {\Device\NPF_{5DFC134F-A948-4AB9-9B9A-C04DE0146F86} WAN Miniport (IP) 22 []} {\Device\NPF_{697F83D1-45C6-40FB-83B7-C1666F1CFF55} Intel(R) Wi-Fi 6E AX211 160MHz 46 [{192.168.1.6 ffffff00 192.168.1.255 <nil>} {fe80::3736:9e2e:e51d:6294 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {2409:8a00:1928:e0b0:eb92:efef:1e40:28ed ffffffffffffffff0000000000000000 2409:8a00:1928:e0b0:ffff:ffff:ffff:ffff <nil>} {2409:8a00:1928:e0b0:35b9:e2de:d267:b182 ffffffffffffffffffffffffffffffff 2409:8a00:1928:e0b0:35b9:e2de:d267:b182 <nil>}]} {\Device\NPF_{76B82B64-FCCD-41D6-B83B-1F4CA5290666} VMware Virtual Ethernet Adapter for VMnet8 22 [{192.168.141.1 ffffff00 192.168.141.255 <nil>} {fe80::936:6c0b:45bc:9a3e ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{48030189-B2C8-448D-8605-4E31E13200BA} VMware Virtual Ethernet Adapter for VMnet1 22 [{192.168.118.1 ffffff00 192.168.118.255 <nil>} {fe80::57ce:b46f:83ab:ec40 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{D5E6E788-B07A-42BD-A430-6B0353A6733D} Microsoft Wi-Fi Direct Virtual Adapter #2 46 [{169.254.62.65 ffff0000 169.254.255.255 <nil>} {fe80::8807:457e:8dd6:6307 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{60A4B46F-44DA-4DFD-B326-B05AF2FFEAAF} Microsoft Wi-Fi Direct Virtual Adapter 46 [{169.254.221.118 ffff0000 169.254.255.255 <nil>} {fe80::1287:3805:3a9c:1a99 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{6E97D03A-C200-4D9C-A5D0-26B639378B49} Realtek PCIe GbE Family Controller 22 [{192.168.1.7 ffffff00 192.168.1.255 <nil>} {fe80::cfa2:8c93:f751:7ce8 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {2409:8a00:1928:e0b0:dcff:c1e7:ddab:4460 ffffffffffffffffffffffffffffffff 2409:8a00:1928:e0b0:dcff:c1e7:ddab:4460 <nil>} {2409:8a00:1928:e0b0:20:ffd5:c720:fc6c ffffffffffffffff0000000000000000 2409:8a00:1928:e0b0:ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_Loopback Adapter for loopback traffic capture 55 [{::1 ffffffffffffffffffffffffffffffff <nil> <nil>} {127.0.0.1 ff000000 <nil> <nil>}]} {\Device\NPF_{FE743143-0162-4046-BD3D-138EBF6385A5} Sangfor SSL VPN CS Support System VNIC 38 [{169.254.120.117 ffff0000 169.254.255.255 <nil>} {fe80::1582:dd38:b20f:e045 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{9D33DA39-15EE-4C7F-AF21-3604F0ECE501} TAP-Windows Adapter V9 38 [{169.254.11.67 ffff0000 169.254.255.255 <nil>} {fe80::9484:9170:e8cc:cfc9 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{2C6B0E77-A8A0-473F-9D7F-5BF413990E87} TrustAgent VNIC 38 [{169.254.190.80 ffff0000 169.254.255.255 <nil>} {fe80::924:960b:ba17:c307 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]}]

**Comment by gobysec** [comment]
未看到您的报错内容，请联系微信：gobyteam
