### ISSUE TITLE
Arm_linux_goby

### ISSUE THREAD

**Issue by HKTangyuan** [gobysec/Goby#396]
希望能够提供arm_linux架构的goby执行文件用于使用在树莓派及更多其它设备上

**Comment by gobysec** [comment]
支持arm_linux架构，需要我单独向您发送包，请联系微信gobyteam

**Comment by HKTangyuan** [comment]
向微信gobyteam询问后无答复

**Comment by gobysec** [comment]
您好，近期有一个向我咨询arm架构的goby，我回复了很多，但貌似那边看不到我发的消息？我不是很理解，不知道和您是一个人吗，您可以重新向我发送消息。

**Comment by HKTangyuan** [comment]
好像是的，但我在这边确实没有收到任何的回复
请问您能否把文件上传到云盘上呢
