### ISSUE TITLE
发生未知错误，Goby 重启后错误仍存在

### ISSUE THREAD

**Issue by heihei559** [gobysec/Goby#402]
read user rule file ok: 0
  Version: v2.0.319 beta
 API Server listen at  127.0.0.1:8361
  127.0.0.1:23499   GET   /api/v1/live  
  127.0.0.1:23500   POST   /api/v1/setEnvi  
  127.0.0.1:23503   GET   /api/v1/getEnvi?field=gid,key,godserver  
  127.0.0.1:23501   GET   /api/v1/getEnvi?field=chromePath,dataIntegrity,datadir,dir,midKey,proxyServer,userRuleSize,vulVersion  
  127.0.0.1:23502   GET   /api/v1/getEnvi?field=ip  
  127.0.0.1:23504   POST   /api/v1/getTasks  
  127.0.0.1:23506   GET   /api/v1/getEnvi?field=licenseInfo,midKey  
  [DEBUG] get adapter of device 
  [DEBUG] devices:  []
  [ERROR] could not find any network interface.  
  interface conversion: string is not error: missing method Error
  interface conversion: string is not error: missing method Error goroutine 48 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
git.gobies.org/goby/goby/api.getEnviHandler.func1()
	git.gobies.org/goby/goby/api/getEnvi.go:203 +0x14c
panic({0x23c2d00, 0xc00329d020})
	runtime/panic.go:838 +0x207
git.gobies.org/goby/goby/api.pcapInfo.func1()
	git.gobies.org/goby/goby/api/getEnvi.go:33 +0x45
panic({0x23093c0, 0x3293780})
	runtime/panic.go:838 +0x207
git.gobies.org/goby/portscanner/pcapsend.getAdapter({0x0, 0x0}, 0x0, 0xc0?, 0x0)
	git.gobies.org/goby/portscanner@v0.0.0-20230109071226-a0527f010913/pcapsend/device.go:349 +0x205
git.gobies.org/goby/portscanner/pcapsend.GetAdpaterInfo({0x0?, 0xc0056ba061?})
	git.gobies.org/goby/portscanner@v0.0.0-20230109071226-a0527f010913/pcapsend/device.go:355 +0x25
git.gobies.org/goby/goby/api.pcapInfo({0x0?, 0x0?})
	git.gobies.org/goby/goby/api/getEnvi.go:42 +0x7c
git.gobies.org/goby/goby/api.envField({0x0?, 0x2000000?}, {0xc00045715a?, 0x2?})
	git.gobies.org/goby/goby/api/getEnvi.go:107 +0x325
git.gobies.org/goby/goby/api.getEnviFields({0x0, 0x0}, {0xc0059ae140, 0x1, 0x0?})
	git.gobies.org/goby/goby/api/getEnvi.go:180 +0xec
git.gobies.org/goby/goby/api.getEnviHandler({0x32a7ed8, 0xc00217a0e0}, 0xc004ac0100?)
	git.gobies.org/goby/goby/api/getEnvi.go:213 +0x125
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2084
git.gobies.org/goby/goby/api.basicAuth.func1({0x32a7ed8?, 0xc00217a0e0?}, 0x88?)
	git.gobies.org/goby/goby/api/api.go:115 +0x248
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2084
git.gobies.org/goby/goby/api.logHttpRequest.func1({0x32a7ed8, 0xc00217a0e0}, 0xc0029e6800)
	git.gobies.org/goby/goby/api/api.go:98 +0x1f4
net/http.HandlerFunc.ServeHTTP(0xc0029e6700?, {0x32a7ed8?, 0xc00217a0e0?}, 0x0?)
	net/http/server.go:2084 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00326e240, {0x32a7ed8, 0xc00217a0e0}, 0xc0008bc200)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc00328f860?}, {0x32a7ed8, 0xc00217a0e0}, 0xc0008bc200)
	net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc002237900, {0x32a8db8, 0xc005fab260})
	net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	net/http/server.go:3071 +0x4db

  127.0.0.1:5998   POST   /api/v1/getPOCList  
  127.0.0.1:6008   POST   /api/v1/startScan  
  [WARNING] change user-agent feature is not included in your current license.
  [WARNING] change deep-analysis feature is not included in your current license.
  scan  0-65535 112.35.144.131
  start port scanner: totalSize: 65536, rate: 100, connectionSize: 100, connectTimeout: 6s, retryTimes: 0, Random: true, Seed: 1677911916807280800, ScanOffset: 0, ScanICMP: false, CheckAliveMode: 2
  pcap version: Npcap version 0.9995, based on libpcap version 1.9.1
  127.0.0.1:6009   POST   /api/v1/getProgress  
  found device from route table for 112.35.144.131: 
  [DEBUG] get adapter of device 
  [DEBUG] devices:  []
  [ERROR] could not find any network interface.  
panic: could not find any network interface. 

goroutine 115 [running]:
git.gobies.org/goby/portscanner/pcapsend.getAdapter({0x0, 0x0}, 0x0, 0xc0?, 0x0)
	git.gobies.org/goby/portscanner@v0.0.0-20230109071226-a0527f010913/pcapsend/device.go:349 +0x205
git.gobies.org/goby/portscanner/pcapsend.NewPcapSender(0xc000140630, 0xc00479e5a0, 0xc00479e5f0)
	git.gobies.org/goby/portscanner@v0.0.0-20230109071226-a0527f010913/pcapsend/send.go:104 +0x3e5
git.gobies.org/goby/portscanner.(*PortScanner).startPcapScan(0xc000eb5180, {0x32a8d10?, 0xc0045e26c0}, 0x0?, 0xc000b1f260, 0xc000b1f2c0)
	git.gobies.org/goby/portscanner@v0.0.0-20230109071226-a0527f010913/portscanner.go:194 +0x88
created by git.gobies.org/goby/portscanner.(*PortScanner).Start
	git.gobies.org/goby/portscanner@v0.0.0-20230109071226-a0527f010913/portscanner.go:243 +0x595

**Comment by gobysec** [comment]
1.开启VPN下，请选择VPN的网卡ip；未开启VPN，请选择本机网卡ip

2.更改sokcet代理扫描

3.重装npcap1.6版本 安装时勾选管理员权限https://npcap.com/dist/npcap-1.60.exe

4.可能ip被ban
