### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by charis3306** [gobysec/Goby#412]
2023/04/13 12:25:30 10m24.36s 92975/132748 (70.04% 4m24s left); send: 186582 301.90 pkt/s (298.84 pkt/s avg); recv: 2395 3.99 pkt/s (3.84 pkt/s avg)
panic: runtime error: slice bounds out of range [4294967288:4]

goroutine 1223090 [running]:
git.gobies.org/goby/goscanner/jsonvul/protocols/grdp/protocol/nla.(*ChallengeMessage).getTargetName(...)
	git.gobies.org/goby/goscanner@v0.0.0-20230118014749-763ed77e198f/jsonvul/protocols/grdp/protocol/nla/ntlm.go:175
git.gobies.org/goby/goscanner/jsonvul/protocols/grdp/protocol/nla.(*NTLMv2).GetAuthenticateMessage(0xc000d46e00, {0xc009d20a20, 0x8c, 0x8c})
	git.gobies.org/goby/goscanner@v0.0.0-20230118014749-763ed77e198f/jsonvul/protocols/grdp/protocol/nla/ntlm.go:386 +0x1258
git.gobies.org/goby/goscanner/jsonvul/protocols/grdp/protocol/tpkt.(*TPKT).recvChallenge(0xc0066d0360, {0xc0033ba400, 0xa3, 0x400})
	git.gobies.org/goby/goscanner@v0.0.0-20230118014749-763ed77e198f/jsonvul/protocols/grdp/protocol/tpkt/tpkt.go:89 +0x2c6
git.gobies.org/goby/goscanner/jsonvul/protocols/grdp/protocol/tpkt.(*TPKT).StartNLA(0xc0066d0360)
	git.gobies.org/goby/goscanner@v0.0.0-20230118014749-763ed77e198f/jsonvul/protocols/grdp/protocol/tpkt/tpkt.go:74 +0x30a
git.gobies.org/goby/goscanner/jsonvul/protocols/grdp/protocol/x224.(*X224).recvConnectionConfirm(0xc005102640, {0xc008709740, 0xf, 0xf})
	git.gobies.org/goby/goscanner@v0.0.0-20230118014749-763ed77e198f/jsonvul/protocols/grdp/protocol/x224/x224.go:275 +0x436
reflect.Value.call({0x1db3a80?, 0xc001e33d50?, 0x18?}, {0x20d2e6a, 0x4}, {0xc0064c9470, 0x1, 0x0?})
	reflect/value.go:556 +0x845
reflect.Value.Call({0x1db3a80?, 0xc001e33d50?, 0x10?}, {0xc0064c9470, 0x1, 0x1})
	reflect/value.go:339 +0xbf
git.gobies.org/goby/goscanner/jsonvul/protocols/grdp/emission.(*Emitter).callListeners.func1({0x1db3a80?, 0xc001e33d50?, 0xc008709726?})
	git.gobies.org/goby/goscanner@v0.0.0-20230118014749-763ed77e198f/jsonvul/protocols/grdp/emission/emitter.go:226 +0x430
created by git.gobies.org/goby/goscanner/jsonvul/protocols/grdp/emission.(*Emitter).callListeners
	git.gobies.org/goby/goscanner@v0.0.0-20230118014749-763ed77e198f/jsonvul/protocols/grdp/emission/emitter.go:201 +0x20f

**Comment by gobysec** [comment]
此问题已修复，已在最新版本中发布，若紧急情况可联系微信：gobyteam协助您解决！感谢您的反馈与支持～
