### ISSUE TITLE
i keep getting this error

### ISSUE THREAD

**Issue by AnubisTwine** [gobysec/Goby#414]
An unknown error occurs, Goby will try to restart and solve it. If the error still exists after the restart, please feed it back to us. Github issue

Error details: Error
2023/04/18 12:08:11 Successfully raised file descriptor limit to 32000
2023/04/18 12:08:11 read user rule file ok:  etc etc etc. tried emailing you and messaging on telegram but get no response

**Comment by gobysec** [comment]
No error message seen. Please add Telegram https://t.me/GobySec and send me more information
