### ISSUE TITLE
出现报错，重启也不管用

### ISSUE THREAD

**Issue by stonewl1** [gobysec/Goby#427]
2023/06/07 17:08:05 read user rule file ok: 0
2023/06/07 17:08:06 Version: v2.0.323 beta
2023/06/07 17:08:07 API Server listen at 127.0.0.1:8361
2023/06/07 17:08:07 127.0.0.1:17206 POST /api/v1/setEnvi
2023/06/07 17:08:07 127.0.0.1:17207 GET /api/v1/getEnvi?field=chromePath,dataIntegrity,datadir,dir,midKey,proxyServer,userRuleSize,vulVersion
2023/06/07 17:08:07 127.0.0.1:17208 GET /api/v1/getEnvi?field=ip
2023/06/07 17:08:07 127.0.0.1:17210 POST /api/v1/getPOCList
2023/06/07 17:08:07 127.0.0.1:17209 GET /api/v1/getEnvi?field=gid,key,godserver
2023/06/07 17:08:07 127.0.0.1:17212 POST /api/v1/getTasks
2023/06/07 17:08:07 127.0.0.1:17211 GET /api/v1/live
2023/06/07 17:08:08 [DEBUG] get adapter of device
2023/06/07 17:08:08 [DEBUG] devices: [{\Device\NPF_Loopback Adapter for loopback traffic capture 55 [{::1 ffffffffffffffffffffffffffffffff <nil> <nil>} {127.0.0.1 ff000000 <nil> <nil>}]}]
2023/06/07 17:08:08 127.0.0.1:17214 GET /api/v1/getEnvi?field=licenseInfo,midKey
2023/06/07 17:08:08 scan is local host, rmac is 0xffffffffffff
2023/06/07 17:08:40 127.0.0.1:17269 POST /api/v1/getTasks
2023/06/07 17:08:51 127.0.0.1:17272 POST /api/v1/getPOCList
2023/06/07 17:09:23 127.0.0.1:17285 POST /api/v1/startScan
2023/06/07 17:09:23 [WARNING] change deep-analysis feature is not included in your current license.
2023/06/07 17:09:23 scan 21,22,23,25,53,U:53,U:69,80,81,U:88,110,111,U:111,123,U:123,135,U:137,139,U:161,U:177,389,U:427,443,445,465,500,515,U:520,U:523,548,623,U:626,636,873,902,1080,1099,1433,U:1434,1521,U:1604,U:1645,U:1701,1883,U:1900,2049,2181,2375,2379,U:2425,3128,3306,3389,4730,U:5060,5222,U:5351,U:5353,5432,5555,5601,5672,U:5683,5900,5938,5984,6000,6379,7001,7077,8080,8081,8443,8545,8686,9000,9001,9042,9092,9100,9200,9418,9999,11211,U:11211,27017,U:33848,37777,50000,50070,61616 127.0.0.1
2023/06/07 17:09:23 start port scanner: totalSize: 91, rate: 100, connectionSize: 100, connectTimeout: 6s, retryTimes: 0, Random: true, Seed: 1686128963756918700, ScanOffset: 0, ScanICMP: false, CheckAliveMode: 2
2023/06/07 17:09:23 pcap version: Npcap version 1.71, based on libpcap version 1.10.2-PRE-GIT
2023/06/07 17:09:23 test localhost
2023/06/07 17:09:23 [DEBUG] get adapter of device
2023/06/07 17:09:23 [DEBUG] devices: [{\Device\NPF_Loopback Adapter for loopback traffic capture 55 [{::1 ffffffffffffffffffffffffffffffff <nil> <nil>} {127.0.0.1 ff000000 <nil> <nil>}]}]
2023/06/07 17:09:23 127.0.0.1:17286 POST /api/v1/getProgress
2023/06/07 17:09:23 scan is local host, rmac is 0xffffffffffff
2023/06/07 17:09:23 testLocalhost: {\Device\NPF_Loopback Adapter for loopback traffic capture 55 [{::1 ffffffffffffffffffffffffffffffff <nil> <nil>} {127.0.0.1 ff000000 <nil> <nil>}]} &{127.0.0.1 [::1] {127.0.0.1 ff000000} ff000000}
2023/06/07 17:09:23 select adapter of to send packets: &{\Device\NPF_Loopback 127.0.0.1 [::1] {127.0.0.1 ff000000} ff000000 ff:ff:ff:ff:ff:ff Adapter for loopback traffic capture ff:ff:ff:ff:ff:ff}
2023/06/07 17:09:23 could not create: Error opening adapter: ϵͳ�Ҳ���ָ����·���� (3)

**Comment by gobysec** [comment]
此问题需要重装npcap1.6版本 https://npcap.com/dist/npcap-1.60.exe，安装时勾选管理员权限。
