### ISSUE TITLE
gobyV2.5.3 BUG 在扫描大量资产后无法导出资产

### ISSUE THREAD

**Issue by tcwy2016** [gobysec/Goby#433]
<img width="1134" alt="image" src="https://github.com/gobysec/Goby/assets/21166708/5a8fceb5-fce5-4c41-bbd2-a233b418fdee">
<img width="631" alt="image" src="https://github.com/gobysec/Goby/assets/21166708/8a9ba30d-418e-4c4d-ac98-68f15b1fe4f6">

扫了一个B段，结果无法导出资产，IP、端口全无！！

**Comment by gobysec** [comment]
此问题已修复，将在2.5.5版本中发布，若紧急情况可联系微信：gobyteam协助您解决！感谢您的反馈与支持～
