### ISSUE TITLE
you dont have permissions to capture

### ISSUE THREAD

**Issue by Ant1M4ttER** [gobysec/Goby#437]
so when i launch goby i get the popup to set the permissions. run the command sudo usermod -g root $USER as instructed in the popup, and get result: usermod: no changes

restart goby and error and close when start8ng scan. logs show:

[DEBUG] getGatewayMac: wlp1s0 192.168.1.255
panic: wlp1s0: You don't have permission to capture on that device (socket: Operation not permitted)

any help would be greatly appriciated

**Comment by gobysec** [comment]
To provide better assistance, please provide the usage system, Goby version, and key screenshots. Thank you!
