### ISSUE TITLE
错误详情: Error 2023/07/24 15:05:27 [DEBUG] runtime.NumCPU():12, runtime.GOMAXPROCS():10

### ISSUE THREAD

**Issue by dreammyf** [gobysec/Goby#445]
发生未知错误，Goby 将尝试重启解决。若重启后错误仍存在，请反馈给我们。 Github issue

错误详情: Error
2023/07/24 15:05:27 [DEBUG] runtime.NumCPU():12, runtime.GOMAXPROCS():10
2023/07/24 15:05:27 Successfully raised file descriptor limit to 10240
2023/07/24 15:05:27 read user rule file ok: 0
2023/07/24 15:05:27 common config info honeypot: 0 rabbish: 0 rabbish-md5: 0
2023/07/24 15:05:27 init repleace log regex len: 3
2023/07/24 15:05:27 Grab version: grab_version_1.9.1.0
2023/07/24 15:05:27 Support 343 protocols, 803 ports
2023/07/24 15:05:27 Version: v2.6.0
2023/07/24 15:05:28 pcap version: libpcap version 1.10.1
2023/07/24 15:05:28 found device from route table for 8.8.8.8:
2023/07/24 15:05:28 [DEBUG] get adapter of device
2023/07/24 15:05:28 [DEBUG] devices: [{en0 30 [{fe80::1c95:3bc1:4638:8d2a ffffffffffffffff0000000000000000 <nil> <nil>}

**Comment by gobysec** [comment]
未看到完整错误，请联系微信：gobyteam。为您尽快解决，感谢您的反馈与支持。

**Comment by laohuan12138** [comment]
我也是老是报这个错误
