### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by K8723** [gobysec/Goby#446]
发生未知错误，Goby 将尝试重启解决。若重启后错误仍存在，请反馈给我们。 Github issue

错误详情: Error
2023/07/24 22:00:41 [DEBUG] runtime.NumCPU():20, runtime.GOMAXPROCS():18
2023/07/24 22:00:41 read user rule file ok: 0
2023/07/24 22:00:41 common config info honeypot: 0 rabbish: 0 rabbish-md5: 0
2023/07/24 22:00:41 init repleace log regex len: 3
2023/07/24 22:00:41 Grab version: grab_version_1.9.1.0
2023/07/24 22:00:41 Support 343 protocols, 803 ports
2023/07/24 22:00:41 Version: v2.6.0
2023/07/24 22:00:42 pcap version: Npcap version 1.71, based on libpcap version 1.10.2-PRE-GIT
2023/07/24 22:00:42 found device from route table for 8.8.8.8:
2023/07/24 22:00:42 [DEBUG] get adapter of device
2023/07/24 22:00:42 [DEBUG] devices: [{\Device\NPF_Loopback Adapter for loopback traffic capture 55 [{::1 ffffffffffffffffffffffffffffffff <nil> <nil>} {127.0.0.1 ff000000 <nil> <nil>}]}]
2023/07/24 22:00:42 scan is local host, rmac is 0xffffffffffff
2023/07/24 22:00:42 select adapter of to send packets: &{\Device\NPF_Loopback 127.0.0.1 [::1] {127.0.0.1 ff000000} ff000000 ff:ff:ff:ff:ff:ff Adapter for loopback traffic capture ff:ff:ff:ff:ff:ff}
2023/07/24 22:00:42 could not create: Error opening adapter: ϵͳ�Ҳ���ָ����·���� (3)

**Comment by gobysec** [comment]
重装npcap，安装时勾选管理员权限。
