### ISSUE TITLE
反复重启

### ISSUE THREAD

**Issue by 0x6lack** [gobysec/Goby#447]
发生未知错误，Goby 将尝试重启解决。若重启后错误仍存在，请反馈给我们。 Github issue

错误详情: Error
2023/07/25 13:34:43 [DEBUG] runtime.NumCPU():20, runtime.GOMAXPROCS():18
2023/07/25 13:34:43 read user rule file ok: 0
2023/07/25 13:34:43 common config info honeypot: 0 rabbish: 0 rabbish-md5: 0
2023/07/25 13:34:43 init repleace log regex len: 3
2023/07/25 13:34:43 Grab version: grab_version_1.9.1.0
2023/07/25 13:34:43 Support 343 protocols, 803 ports
2023/07/25 13:34:43 Version: v2.6.0
2023/07/25 13:34:43 LicenseName: redteam
2023/07/25 13:34:46 pcap version: Npcap version 0.9982, based on libpcap version 1.9.1-PRE-GIT
2023/07/25 13:34:47 found device from route table for 8.8.8.8: \Device\NPF_{B37CDBCF-2C49-4DC9-9D3F-649872809E22}
2023/07/25 13:34:47 [DEBUG] get adapter of device \Device\NPF_{B37CDBCF-2C49-4DC9-9D3F-649872809E22}
2023/07/25 13:34:48 [DEBUG] devices: [{\Device\NPF_{113E17E6-68B5-4CB4-A59E-348EB690634B} Microsoft 46 []} {\Device\NPF_{F050876B-FAE2-4D6B-B322-09DE2C5BD7CD} NdisWan Adapter 22 []} {\Device\NPF_{30F1D972-110B-4190-A1D7-DB528143986B} NdisWan Adapter 22 []} {\Device\NPF_{FE90176F-7DA5-4A87-9337-D9165F05AA2F} Microsoft 46 []} {\Device\NPF_{CFB88720-25B1-4582-A5CB-82877A68A93F} Microsoft 46 []} {\Device\NPF_{16A5BCE3-6054-43F8-9E38-50A435BC7A4E} VMware Virtual Ethernet Adapter 22 [{fe80::7e7b:6811:bf38:dbae <nil> <nil> <nil>} {192.168.211.1 ffffff00 255.255.255.255 <nil>}]} {\Device\NPF_{ED83D360-8E41-4CB4-A8EA-FD273D17D2D2} NdisWan Adapter 22 []} {\Device\NPF_{D029858D-5A3D-4006-83B3-CE73376FBA05} VMware Virtual Ethernet Adapter 22 [{fe80::daed:a41a:1c7e:d6a4 <nil> <nil> <nil>} {192.168.92.1 ffffff00 255.255.255.255 <nil>}]} {\Device\NPF_{B37CDBCF-2C49-4DC9-9D3F-649872809E22} Microsoft 30 [{172.20.10.6 fffffff0 255.255.255.255 <nil>}]} {\Device\NPF_{BE32085C-4418-4C7A-8F05-3AE47DC8E257} MS NDIS 6.0 LoopBack Driver 22 [{fe80::a723:d899:948a:8b4e <nil> <nil> <nil>} {0.0.0.0 ff000000 255.255.255.255 <nil>}]} {\Device\NPF_{01C9DCD1-A89F-4526-9A44-56B6775FA7BF} Intel(R) Ethernet Connection (16) I219-V 38 [{192.168.192.212 fffffe00 255.255.255.255 <nil>}]}]
2023/07/25 13:34:48 [DEBUG] device name is not match: \Device\NPF_{113E17E6-68B5-4CB4-A59E-348EB690634B} != \Device\NPF_{B37CDBCF-2C49-4DC9-9D3F-649872809E22}
2023/07/25 13:34:48 [DEBUG] device name is not match: \Device\NPF_{F050876B-FAE2-4D6B-B322-09DE2C5BD7CD} != \Device\NPF_{B37CDBCF-2C49-4DC9-9D3F-649872809E22}
2023/07/25 13:34:48 [DEBUG] device name is not match: \Device\NPF_{30F1D972-110B-4190-A1D7-DB528143986B} != \Device\NPF_{B37CDBCF-2C49-4DC9-9D3F-649872809E22}
2023/07/25 13:34:48 [DEBUG] device name is not match: \Device\NPF_{FE90176F-7DA5-4A87-9337-D9165F05AA2F} != \Device\NPF_{B37CDBCF-2C49-4DC9-9D3F-649872809E22}
2023/07/25 13:34:48 [DEBUG] device name is not match: \Device\NPF_{CFB88720-25B1-4582-A5CB-82877A68A93F} != \Device\NPF_{B37CDBCF-2C49-4DC9-9D3F-649872809E22}
2023/07/25 13:34:48 [DEBUG] device name is not match: \Device\NPF_{16A5BCE3-6054-43F8-9E38-50A435BC7A4E} != \Device\NPF_{B37CDBCF-2C49-4DC9-9D3F-649872809E22}
2023/07/25 13:34:48 [DEBUG] device name is not match: \Device\NPF_{ED83D360-8E41-4CB4-A8EA-FD273D17D2D2} != \Device\NPF_{B37CDBCF-2C49-4DC9-9D3F-649872809E22}
2023/07/25 13:34:48 [DEBUG] device name is not match: \Device\NPF_{D029858D-5A3D-4006-83B3-CE73376FBA05} != \Device\NPF_{B37CDBCF-2C49-4DC9-9D3F-649872809E22}
2023/07/25 13:34:48 [DEBUG] getGatewayMac: \Device\NPF_{B37CDBCF-2C49-4DC9-9D3F-649872809E22} 8.8.8.8
2023/07/25 13:34:49 find router mac is 56:09:10:f7:ea:64
2023/07/25 13:34:50 [DEBUG] fetch mac address: \Device\NPF_{B37CDBCF-2C49-4DC9-9D3F-649872809E22} 56:09:10:f7:ea:64
2023/07/25 13:34:50 [DEBUG] close pcap handler for getGatewayMac
2023/07/25 13:34:50 select adapter of to send packets: &{\Device\NPF_{B37CDBCF-2C49-4DC9-9D3F-649872809E22} 172.20.10.6 [] {172.20.10.6 fffffff0} fffffff0 20:c1:9b:6c:96:a2 Microsoft 56:09:10:f7:ea:64}
2023/07/25 13:34:50 API Server listen at 127.0.0.1:8361
2023/07/25 13:34:50 127.0.0.1:38235 POST /api/v1/setEnvi

**Comment by gobysec** [comment]
未看到完整错误，请联系微信：gobyteam。为您尽快解决，感谢您的反馈与支持。
