### ISSUE TITLE
warning:invaild memory address

### ISSUE THREAD

**Issue by 132231g** [gobysec/Goby#464]
![image](https://github.com/gobysec/Goby/assets/49609245/90335ba7-38b3-4ff4-913c-c4b9b7ca9cdf)
是否需要重新建立扫描任务，因为可以访问目标主机

**Comment by 132231g** [comment]
而且漏洞好像未扫出

**Comment by gobysec** [comment]
您可以联系微信号：gobyteam发送一下您详细日志，为您定位问题
