### ISSUE TITLE
发生未知错误，Goby 将尝试重启解决。

### ISSUE THREAD

**Issue by JTxx24** [gobysec/Goby#466]
****2023/09/22 17:04:09 [DEBUG] runtime.NumCPU():4, runtime.GOMAXPROCS():2
2023/09/22 17:04:09 read user rule file ok: 0
2023/09/22 17:04:09 common config info  honeypot: 0 rabbish: 0 rabbish-md5: 0
2023/09/22 17:04:09 init repleace log regex  len: 3
2023/09/22 17:04:09 Grab version:  grab_version_1.9.1.0
2023/09/22 17:04:09 Support 343  protocols, 803  ports
2023/09/22 17:04:09 Version: v2.6.1
2023/09/22 17:04:11 API Server listen at  127.0.0.1:8361
2023/09/22 17:04:11 pcap version: Npcap version 1.75, based on libpcap version 1.10.4
2023/09/22 17:04:11 127.0.0.1:50285   GET   /api/v1/live  
2023/09/22 17:04:12 127.0.0.1:50292   POST   /api/v1/setEnvi  
2023/09/22 17:04:12 127.0.0.1:50305   GET   /api/v1/getEnvi?field=chromePath,dataIntegrity,datadir,dir,midKey,proxyServer,userRuleSize,vulVersion  
2023/09/22 17:04:12 127.0.0.1:50306   GET   /api/v1/getEnvi?field=ip  
2023/09/22 17:04:12 127.0.0.1:50308   POST   /api/v1/getPOCList  
2023/09/22 17:04:12 127.0.0.1:50307   GET   /api/v1/getEnvi?field=gid,key,godserver  
2023/09/22 17:04:12 127.0.0.1:50309   POST   /api/v1/getTasks  
2023/09/22 17:04:12 found device from route table for 8.8.8.8: \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:12 [DEBUG] get adapter of device \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:12 [DEBUG] devices:  [{\Device\NPF_{5A7050DA-33FF-42F2-8A01-E9A5C5114D0F} WAN Miniport (IPv6) 22 []} {\Device\NPF_{A7817ED0-59BA-4720-B42F-38D02A73A7C1} WAN Miniport (IP) 22 []} {\Device\NPF_{8F973C10-269E-4BF6-B350-E99549CAFD8E} WAN Miniport (Network Monitor) 22 []} {\Device\NPF_{8F3F7603-2ECF-4EF5-BFC5-FE89C7B71A9B} Intel(R) Dual Band Wireless-AC 3165 46 [{169.254.160.244 ffff0000 169.254.255.255 <nil>} {fe80::f69c:55bc:e5fd:2d54 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{8F3B3FF7-72E2-4446-BB21-E25FCABD310F} VMware Virtual Ethernet Adapter for VMnet4 22 [{192.168.52.1 ffffff00 192.168.52.255 <nil>} {fe80::ab6b:b994:e3aa:c8b5 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{3A50C722-25CF-46D0-9C90-51A32BC666CF} VMware Virtual Ethernet Adapter for VMnet2 22 [{192.168.93.1 ffffff00 192.168.93.255 <nil>} {fe80::6d09:28dc:dc6d:20b8 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{23AB7B78-BA23-4AFC-87F3-B3154258C903} Apple Mobile Device Ethernet 22 [{172.20.10.7 fffffff0 172.20.10.15 <nil>} {fe80::3238:e95:f686:f8b2 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {240e:456:a00:44bf:c06c:7078:d377:f4a4 ffffffffffffffffffffffffffffffff 240e:456:a00:44bf:c06c:7078:d377:f4a4 <nil>} {240e:456:a00:44bf:f4bd:8fb0:1a8a:cc84 ffffffffffffffff0000000000000000 240e:456:a00:44bf:ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{5A86764A-7AF7-4932-A98C-F50C69F44A89} VMware Virtual Ethernet Adapter for VMnet8 22 [{192.168.184.1 ffffff00 192.168.184.255 <nil>} {fe80::a1aa:363a:c65e:50 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{DEA72233-DCDA-41CD-852D-1AD633139C00} VMware Virtual Ethernet Adapter for VMnet1 22 [{192.168.140.1 ffffff00 192.168.140.255 <nil>} {fe80::68e4:54e3:ae98:61bf ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{FC59895B-E466-4664-B620-2D6F367236E0} Microsoft Wi-Fi Direct Virtual Adapter #2 46 [{169.254.124.134 ffff0000 169.254.255.255 <nil>} {fe80::80c9:358e:59b6:c23b ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{9BF1BF5C-0754-464D-8B89-767DF2A55D39} Microsoft Wi-Fi Direct Virtual Adapter 46 [{169.254.166.137 ffff0000 169.254.255.255 <nil>} {fe80::60d8:cb7e:d1e2:b36 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{2ACFCAD0-958C-48E0-B4F9-71943256FE76} Hyper-V Virtual Ethernet Adapter 22 [{172.18.16.1 fffff000 172.18.31.255 <nil>} {fe80::b745:66ed:b2ac:9e74 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB} Clash Tunnel 22 [{198.18.0.1 ffff0000 198.18.255.255 <nil>}]} {\Device\NPF_Loopback Adapter for loopback traffic capture 55 [{::1 ffffffffffffffffffffffffffffffff <nil> <nil>} {127.0.0.1 ff000000 <nil> <nil>}]} {\Device\NPF_{F42DB922-FE6F-4368-9CB8-EA7361F98E0C} Realtek PCIe GbE Family Controller 38 [{169.254.61.35 ffff0000 169.254.255.255 <nil>} {fe80::245c:ed9a:7a64:be7c ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]}]
2023/09/22 17:04:12 [DEBUG] device name is not match: \Device\NPF_{5A7050DA-33FF-42F2-8A01-E9A5C5114D0F} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:12 [DEBUG] device name is not match: \Device\NPF_{A7817ED0-59BA-4720-B42F-38D02A73A7C1} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:12 [DEBUG] device name is not match: \Device\NPF_{8F973C10-269E-4BF6-B350-E99549CAFD8E} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:12 [DEBUG] device name is not match: \Device\NPF_{8F3F7603-2ECF-4EF5-BFC5-FE89C7B71A9B} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:12 [DEBUG] device name is not match: \Device\NPF_{8F3B3FF7-72E2-4446-BB21-E25FCABD310F} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:12 [DEBUG] device name is not match: \Device\NPF_{3A50C722-25CF-46D0-9C90-51A32BC666CF} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:12 [DEBUG] device name is not match: \Device\NPF_{23AB7B78-BA23-4AFC-87F3-B3154258C903} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:12 [DEBUG] device name is not match: \Device\NPF_{5A86764A-7AF7-4932-A98C-F50C69F44A89} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:12 [DEBUG] device name is not match: \Device\NPF_{DEA72233-DCDA-41CD-852D-1AD633139C00} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:12 [DEBUG] device name is not match: \Device\NPF_{FC59895B-E466-4664-B620-2D6F367236E0} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:12 [DEBUG] device name is not match: \Device\NPF_{9BF1BF5C-0754-464D-8B89-767DF2A55D39} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:12 [DEBUG] device name is not match: \Device\NPF_{2ACFCAD0-958C-48E0-B4F9-71943256FE76} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:12 [DEBUG] getGatewayMac: \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB} 8.8.8.8
2023/09/22 17:04:13 127.0.0.1:50321   GET   /api/v1/getEnvi?field=licenseInfo,midKey  
2023/09/22 17:04:13 [DEBUG] get adapter of device \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:13 [DEBUG] devices:  [{\Device\NPF_{5A7050DA-33FF-42F2-8A01-E9A5C5114D0F} WAN Miniport (IPv6) 22 []} {\Device\NPF_{A7817ED0-59BA-4720-B42F-38D02A73A7C1} WAN Miniport (IP) 22 []} {\Device\NPF_{8F973C10-269E-4BF6-B350-E99549CAFD8E} WAN Miniport (Network Monitor) 22 []} {\Device\NPF_{8F3F7603-2ECF-4EF5-BFC5-FE89C7B71A9B} Intel(R) Dual Band Wireless-AC 3165 46 [{169.254.160.244 ffff0000 169.254.255.255 <nil>} {fe80::f69c:55bc:e5fd:2d54 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{8F3B3FF7-72E2-4446-BB21-E25FCABD310F} VMware Virtual Ethernet Adapter for VMnet4 22 [{192.168.52.1 ffffff00 192.168.52.255 <nil>} {fe80::ab6b:b994:e3aa:c8b5 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{3A50C722-25CF-46D0-9C90-51A32BC666CF} VMware Virtual Ethernet Adapter for VMnet2 22 [{192.168.93.1 ffffff00 192.168.93.255 <nil>} {fe80::6d09:28dc:dc6d:20b8 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{23AB7B78-BA23-4AFC-87F3-B3154258C903} Apple Mobile Device Ethernet 22 [{172.20.10.7 fffffff0 172.20.10.15 <nil>} {fe80::3238:e95:f686:f8b2 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {240e:456:a00:44bf:c06c:7078:d377:f4a4 ffffffffffffffffffffffffffffffff 240e:456:a00:44bf:c06c:7078:d377:f4a4 <nil>} {240e:456:a00:44bf:f4bd:8fb0:1a8a:cc84 ffffffffffffffff0000000000000000 240e:456:a00:44bf:ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{5A86764A-7AF7-4932-A98C-F50C69F44A89} VMware Virtual Ethernet Adapter for VMnet8 22 [{192.168.184.1 ffffff00 192.168.184.255 <nil>} {fe80::a1aa:363a:c65e:50 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{DEA72233-DCDA-41CD-852D-1AD633139C00} VMware Virtual Ethernet Adapter for VMnet1 22 [{192.168.140.1 ffffff00 192.168.140.255 <nil>} {fe80::68e4:54e3:ae98:61bf ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{FC59895B-E466-4664-B620-2D6F367236E0} Microsoft Wi-Fi Direct Virtual Adapter #2 46 [{169.254.124.134 ffff0000 169.254.255.255 <nil>} {fe80::80c9:358e:59b6:c23b ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{9BF1BF5C-0754-464D-8B89-767DF2A55D39} Microsoft Wi-Fi Direct Virtual Adapter 46 [{169.254.166.137 ffff0000 169.254.255.255 <nil>} {fe80::60d8:cb7e:d1e2:b36 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{2ACFCAD0-958C-48E0-B4F9-71943256FE76} Hyper-V Virtual Ethernet Adapter 22 [{172.18.16.1 fffff000 172.18.31.255 <nil>} {fe80::b745:66ed:b2ac:9e74 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB} Clash Tunnel 22 [{198.18.0.1 ffff0000 198.18.255.255 <nil>}]} {\Device\NPF_Loopback Adapter for loopback traffic capture 55 [{::1 ffffffffffffffffffffffffffffffff <nil> <nil>} {127.0.0.1 ff000000 <nil> <nil>}]} {\Device\NPF_{F42DB922-FE6F-4368-9CB8-EA7361F98E0C} Realtek PCIe GbE Family Controller 38 [{169.254.61.35 ffff0000 169.254.255.255 <nil>} {fe80::245c:ed9a:7a64:be7c ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]}]
2023/09/22 17:04:13 [DEBUG] device name is not match: \Device\NPF_{5A7050DA-33FF-42F2-8A01-E9A5C5114D0F} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:13 [DEBUG] device name is not match: \Device\NPF_{A7817ED0-59BA-4720-B42F-38D02A73A7C1} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:13 [DEBUG] device name is not match: \Device\NPF_{8F973C10-269E-4BF6-B350-E99549CAFD8E} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:13 [DEBUG] device name is not match: \Device\NPF_{8F3F7603-2ECF-4EF5-BFC5-FE89C7B71A9B} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:13 [DEBUG] device name is not match: \Device\NPF_{8F3B3FF7-72E2-4446-BB21-E25FCABD310F} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:13 [DEBUG] device name is not match: \Device\NPF_{3A50C722-25CF-46D0-9C90-51A32BC666CF} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:13 [DEBUG] device name is not match: \Device\NPF_{23AB7B78-BA23-4AFC-87F3-B3154258C903} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:13 [DEBUG] device name is not match: \Device\NPF_{5A86764A-7AF7-4932-A98C-F50C69F44A89} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:13 [DEBUG] device name is not match: \Device\NPF_{DEA72233-DCDA-41CD-852D-1AD633139C00} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:13 [DEBUG] device name is not match: \Device\NPF_{FC59895B-E466-4664-B620-2D6F367236E0} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:13 [DEBUG] device name is not match: \Device\NPF_{9BF1BF5C-0754-464D-8B89-767DF2A55D39} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:13 [DEBUG] device name is not match: \Device\NPF_{2ACFCAD0-958C-48E0-B4F9-71943256FE76} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:13 [DEBUG] getGatewayMac: \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB} 0.0.0.0
2023/09/22 17:04:13 find router mac is  45:00:00:1f:6b:6e
2023/09/22 17:04:14 127.0.0.1:50391   POST   /api/v1/getPOCList  
2023/09/22 17:04:14 find router mac is  45:00:00:1f:6b:70
2023/09/22 17:04:14 [DEBUG] fetch mac address: \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB} 45:00:00:1f:6b:70
2023/09/22 17:04:14 [DEBUG] close pcap handler for getGatewayMac
2023/09/22 17:04:15 [DEBUG] fetch mac address: \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB} 45:00:00:1f:6b:6e
2023/09/22 17:04:15 [DEBUG] close pcap handler for getGatewayMac
2023/09/22 17:04:15 select adapter of to send packets:  &{\Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB} 198.18.0.1 [] {198.18.0.1 ffff0000} ffff0000  Clash Tunnel 45:00:00:1f:6b:6e}
2023/09/22 17:04:18 127.0.0.1:50552   POST   /api/v1/startScan  
2023/09/22 17:04:18 [WARNING] change deep-analysis feature is not included in your current license.
2023/09/22 17:04:18 goby.Start.LoadCustomRules() err: open F:\Goby\goby-win-x64-2.6.0\golib\rules\user\cdn-header-rule.json: The system cannot find the file specified.
2023/09/22 17:04:18 127.0.0.1:50558   POST   /api/v1/getProgress  
2023/09/22 17:04:18 127.0.0.1:50579   POST   /api/v1/getStatisticsData  
2023/09/22 17:04:18 goby_config BlackTargets: 
2023/09/22 17:04:18 scan  21,22,23,25,53,U:53,U:69,80,81,U:88,110,111,U:111,123,U:123,135,U:137,139,U:161,U:177,389,U:427,443,445,465,500,515,U:520,U:523,548,623,U:626,636,873,902,1080,1099,1433,U:1434,1521,U:1604,U:1645,U:1701,1883,U:1900,2049,2181,2375,2379,U:2425,3128,3306,3389,4730,U:5060,5222,U:5351,U:5353,5432,5555,5601,5672,U:5683,5900,5938,5984,6000,6379,7001,7077,8080,8081,8443,8545,8686,9000,9001,9042,9092,9100,9200,9418,9999,11211,U:11211,27017,U:33848,37777,50000,50070,61616 www.szrtxx.com
2023/09/22 17:04:18 start port scanner: totalSize: 91, rate: 100, connectionSize: 100, connectTimeout: 6s, retryTimes: 0, Random: true, Seed: 1695373458810558900, ScanOffset: 0, ScanICMP: false, CheckAliveMode: 2
2023/09/22 17:04:18 pcap version: Npcap version 1.75, based on libpcap version 1.10.4
2023/09/22 17:04:20 found device from route table for 120.79.79.7: \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:20 [DEBUG] get adapter of device \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:20 [DEBUG] devices:  [{\Device\NPF_{5A7050DA-33FF-42F2-8A01-E9A5C5114D0F} WAN Miniport (IPv6) 22 []} {\Device\NPF_{A7817ED0-59BA-4720-B42F-38D02A73A7C1} WAN Miniport (IP) 22 []} {\Device\NPF_{8F973C10-269E-4BF6-B350-E99549CAFD8E} WAN Miniport (Network Monitor) 22 []} {\Device\NPF_{8F3F7603-2ECF-4EF5-BFC5-FE89C7B71A9B} Intel(R) Dual Band Wireless-AC 3165 46 [{169.254.160.244 ffff0000 169.254.255.255 <nil>} {fe80::f69c:55bc:e5fd:2d54 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{8F3B3FF7-72E2-4446-BB21-E25FCABD310F} VMware Virtual Ethernet Adapter for VMnet4 22 [{192.168.52.1 ffffff00 192.168.52.255 <nil>} {fe80::ab6b:b994:e3aa:c8b5 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{3A50C722-25CF-46D0-9C90-51A32BC666CF} VMware Virtual Ethernet Adapter for VMnet2 22 [{192.168.93.1 ffffff00 192.168.93.255 <nil>} {fe80::6d09:28dc:dc6d:20b8 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{23AB7B78-BA23-4AFC-87F3-B3154258C903} Apple Mobile Device Ethernet 22 [{172.20.10.7 fffffff0 172.20.10.15 <nil>} {fe80::3238:e95:f686:f8b2 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>} {240e:456:a00:44bf:c06c:7078:d377:f4a4 ffffffffffffffffffffffffffffffff 240e:456:a00:44bf:c06c:7078:d377:f4a4 <nil>} {240e:456:a00:44bf:f4bd:8fb0:1a8a:cc84 ffffffffffffffff0000000000000000 240e:456:a00:44bf:ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{5A86764A-7AF7-4932-A98C-F50C69F44A89} VMware Virtual Ethernet Adapter for VMnet8 22 [{192.168.184.1 ffffff00 192.168.184.255 <nil>} {fe80::a1aa:363a:c65e:50 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{DEA72233-DCDA-41CD-852D-1AD633139C00} VMware Virtual Ethernet Adapter for VMnet1 22 [{192.168.140.1 ffffff00 192.168.140.255 <nil>} {fe80::68e4:54e3:ae98:61bf ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{FC59895B-E466-4664-B620-2D6F367236E0} Microsoft Wi-Fi Direct Virtual Adapter #2 46 [{169.254.124.134 ffff0000 169.254.255.255 <nil>} {fe80::80c9:358e:59b6:c23b ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{9BF1BF5C-0754-464D-8B89-767DF2A55D39} Microsoft Wi-Fi Direct Virtual Adapter 46 [{169.254.166.137 ffff0000 169.254.255.255 <nil>} {fe80::60d8:cb7e:d1e2:b36 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{2ACFCAD0-958C-48E0-B4F9-71943256FE76} Hyper-V Virtual Ethernet Adapter 22 [{172.18.16.1 fffff000 172.18.31.255 <nil>} {fe80::b745:66ed:b2ac:9e74 ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]} {\Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB} Clash Tunnel 22 [{198.18.0.1 ffff0000 198.18.255.255 <nil>}]} {\Device\NPF_Loopback Adapter for loopback traffic capture 55 [{::1 ffffffffffffffffffffffffffffffff <nil> <nil>} {127.0.0.1 ff000000 <nil> <nil>}]} {\Device\NPF_{F42DB922-FE6F-4368-9CB8-EA7361F98E0C} Realtek PCIe GbE Family Controller 38 [{169.254.61.35 ffff0000 169.254.255.255 <nil>} {fe80::245c:ed9a:7a64:be7c ffffffffffffffff0000000000000000 fe80::ffff:ffff:ffff:ffff <nil>}]}]
2023/09/22 17:04:20 [DEBUG] device name is not match: \Device\NPF_{5A7050DA-33FF-42F2-8A01-E9A5C5114D0F} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:20 [DEBUG] device name is not match: \Device\NPF_{A7817ED0-59BA-4720-B42F-38D02A73A7C1} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:20 [DEBUG] device name is not match: \Device\NPF_{8F973C10-269E-4BF6-B350-E99549CAFD8E} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:20 [DEBUG] device name is not match: \Device\NPF_{8F3F7603-2ECF-4EF5-BFC5-FE89C7B71A9B} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:20 [DEBUG] device name is not match: \Device\NPF_{8F3B3FF7-72E2-4446-BB21-E25FCABD310F} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:20 [DEBUG] device name is not match: \Device\NPF_{3A50C722-25CF-46D0-9C90-51A32BC666CF} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:20 [DEBUG] device name is not match: \Device\NPF_{23AB7B78-BA23-4AFC-87F3-B3154258C903} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:20 [DEBUG] device name is not match: \Device\NPF_{5A86764A-7AF7-4932-A98C-F50C69F44A89} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:20 [DEBUG] device name is not match: \Device\NPF_{DEA72233-DCDA-41CD-852D-1AD633139C00} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:20 [DEBUG] device name is not match: \Device\NPF_{FC59895B-E466-4664-B620-2D6F367236E0} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:20 [DEBUG] device name is not match: \Device\NPF_{9BF1BF5C-0754-464D-8B89-767DF2A55D39} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:20 [DEBUG] device name is not match: \Device\NPF_{2ACFCAD0-958C-48E0-B4F9-71943256FE76} != \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
2023/09/22 17:04:20 [DEBUG] getGatewayMac: \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB} 120.79.79.7
2023/09/22 17:04:21 127.0.0.1:50695   POST   /api/v1/getProgress  
2023/09/22 17:04:21 127.0.0.1:50696   POST   /api/v1/getStatisticsData  
2023/09/22 17:04:21 find router mac is  45:00:00:1f:6b:74
2023/09/22 17:04:22 [DEBUG] fetch mac address: \Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB} 45:00:00:1f:6b:74
2023/09/22 17:04:22 [DEBUG] close pcap handler for getGatewayMac
2023/09/22 17:04:22 select adapter of to send packets:  &{\Device\NPF_{330EAEF8-7578-5DF2-D97B-8DADC0EA85CB} 198.18.0.1 [] {198.18.0.1 ffff0000} ffff0000  Clash Tunnel 45:00:00:1f:6b:74}
2023/09/22 17:04:22 routine-recv start
2023/09/22 17:04:22 port scanner is ready
2023/09/22 17:04:22 routine-target run out ping target pool 2
2023/09/22 17:04:22 alive range after ping2 (1): 120.79.79.7
2023/09/22 17:04:22 start first round ARP
2023/09/22 17:04:22 first round ARP done
2023/09/22 17:04:23 4.696s 0/91 (0.00% N/A left); send: 0 0.00 pkt/s (0.00 pkt/s avg); recv: 0 0.00 pkt/s (0.00 pkt/s avg)
2023/09/22 17:04:23 start sending packets
2023/09/22 17:04:23 [WARNING] Serialize failed: invalid src MAC: 
2023/09/22 17:04:23 routine-send out
panic: runtime error: index out of range [0] with length 0

goroutine 1143 [running]:
github.com/google/gopacket/pcap.(*Handle).pcapSendpacket(0xc00694a1e0?, {0x0?, 0x1f?, 0x0?})
	github.com/google/gopacket@v1.1.20-0.20210429153827-3eaba0894325/pcap/pcap_windows.go:658 +0x76
github.com/google/gopacket/pcap.(*Handle).WritePacketData(...)
	github.com/google/gopacket@v1.1.20-0.20210429153827-3eaba0894325/pcap/pcap.go:696
git.gobies.org/goby/portscanner/pcapsend.(*PcapSender).sendSYN(0xc0061fa630, 0x784f4f07, 0x15)
	git.gobies.org/goby/portscanner@v0.0.5/pcapsend/send.go:382 +0x193
git.gobies.org/goby/portscanner/pcapsend.(*PcapSender).SendPackets(0xc0061fa630, {0x3efcd90, 0xc006ec7380}, 0x0?, 0x0?, 0xc009a71f40?)
	git.gobies.org/goby/portscanner@v0.0.5/pcapsend/send.go:1642 +0x5f3
created by git.gobies.org/goby/portscanner.(*PortScanner).startPcapScan
	git.gobies.org/goby/portscanner@v0.0.5/portscanner.go:219 **+0x28a**

**Comment by gobysec** [comment]
已收到您的反馈，我们尽快优化，优化后会向您致谢，若无回复，您可以联系微信号：gobyteam，感谢您对Goby喜爱与支持~

**Comment by gobysec** [comment]
重装pcap，如还有报错请携带操作系统架构添加微信号gobyteam，为您解决~
