### ISSUE TITLE
1.6.44 扫描崩溃

### ISSUE THREAD

**Issue by v1ncilazy** [gobysec/Goby#48]
系统: win10 2004
win_x64 1.6.144 
npcap 0.9900
错误日志:
goroutine 137 [running]:
encoding/binary.bigEndian.Uint32(...)
	/usr/local/Cellar/go/1.14/libexec/src/encoding/binary/binary.go:112
git.baimaohui.net/goby/portscanner.ip2int(0x0, 0x0, 0x0, 0x0)
	/Users/zwell/go/src/git.baimaohui.net/goby/portscanner/portscanner_base.go:49 +0x58
git.baimaohui.net/goby/portscanner.IP2Int(0xc0005980c8, 0x5, 0x1b16ea9)
	/Users/zwell/go/src/git.baimaohui.net/goby/portscanner/portscanner_base.go:53 +0x80
git.baimaohui.net/goby/portscanner.(*PortScanner).IsValidHost(0xc000d3c340, 0xc0005980c8, 0x5, 0xc0033e0700)
	/Users/zwell/go/src/git.baimaohui.net/goby/portscanner/portscanner_base.go:71 +0xf0
git.baimaohui.net/goby/goby.(*GobyScanner).StartBasicNetworkInfoScanner(0xc001b0d7c0, 0xc002b06c70)
	/Users/zwell/go/src/git.baimaohui.net/goby/goby/goby_basic_network_scanner.go:42 +0x228
created by git.baimaohui.net/goby/goby.(*GobyScanner).Start
	/Users/zwell/go/src/git.baimaohui.net/goby/goby/goby.go:216 +0x2d5

扫描参数 :192.168.0.0/24 全端口 全漏洞 资产优先
设置 网卡自动 扫描速率 1000  开启网站截图 MDNS协议识别 UPnP协议识别 自动爬取子域名 随机扫描IP 深度测试

**Comment by gobysec** [comment]
已修复。
