### ISSUE TITLE
请问，能告知或者开源windows rdp相关开源库或者代码？

### ISSUE THREAD

**Issue by lcl101** [gobysec/Goby#487]
请问，能告知或者开源windows rdp相关开源库或者代码？

**Comment by gobysec** [comment]
你好，感兴趣可以浏览我们官方公众号发布的关于RDP的文章：https://mp.weixin.qq.com/s/Iv87dwn_VTruYExet8AnlA

**Comment by xirotech** [comment]
感覺截圖功能還是不穩定，手動關閉NLA後有時都無.
