### ISSUE TITLE
win版无法扫描端口，kali版本进度一直为0

### ISSUE THREAD

**Issue by laowang1026** [gobysec/Goby#5]
win版无法扫描端口，kali版本进度一直为0

**Comment by gobysec** [comment]
你好，当前使用的Goby的版本号及下载日期是？

**Comment by gobysec** [comment]
> win版无法扫描端口，kali版本进度一直为0

1.3.35版本存在不能启动的BUG，我们后来修复了它。表哥到GOBY官网重新下载1.3.35版本即可。
