### ISSUE TITLE
资产扫描不够准确部分资产扫描不出

### ISSUE THREAD

**Issue by ev1lfy** [gobysec/Goby#57]
使用Goby扫描多个IP资产时，由于网络环境问题会出现部分资产扫描不到而实际输入的这些IP都存活，使用Nmap就可以扫描到，对应的参数`nmap -sP -iL`,实际工作场景遇到的问题。希望能增加给使用者灵活配置扫描探活的参数。

**Comment by gobysec** [comment]
直接输入1-65535端口扫描试试。
