### ISSUE TITLE
Terminal模式导出扫描报告内容为空

### ISSUE THREAD

**Issue by hackerso007** [gobysec/Goby#58]
在命令模式下导出扫描报告内容为空，建议完善命终端模式各种参数功能

**Comment by hackerso007** [comment]
导出命令如下
./goby-cmd-linux  -debuglevel 0  -mode  export    -exportMode 20200527151119 -exportFile ./20200527151119

**Comment by gobysec** [comment]
> 在命令模式下导出扫描报告内容为空，建议完善命终端模式各种参数功能

Goby非开源，所以不会发布官方API等参数文档。
