### ISSUE TITLE
界面字体能否增大一点

### ISSUE THREAD

**Issue by FanqXu** [gobysec/Goby#59]
Linux版本的字体好小，有望 **增大**。

**Comment by gobysec** [comment]
> Linux版本的字体好小，有望 **增大**。

方便截图看下吗？

**Comment by FanqXu** [comment]
> OS: Kali Linux 
> 看着字体着实有点小，希望你们能考虑将字体增大点。

![goby0](https://user-images.githubusercontent.com/40891670/83374675-e65b8680-a3fe-11ea-9c20-b072b6f88b6d.jpg)
![goby1](https://user-images.githubusercontent.com/40891670/83374681-e9ef0d80-a3fe-11ea-8ddf-4e4c27e11696.jpg)
