### ISSUE TITLE
扫描bug

### ISSUE THREAD

**Issue by Hetuipei** [gobysec/Goby#61]
如果同样个IP存在两个同样的服务  但只能扫出来一个   nmap可以全扫出来。

**Comment by gobysec** [comment]
> 如果同样个IP存在两个同样的服务 但只能扫出来一个 nmap可以全扫出来。

可否提供未识别的服务协议？

**Comment by Hetuipei** [comment]
> > 如果同样个IP存在两个同样的服务但只能扫出来一个nmap可以全扫出来。
> 
> 可否提供未识别的服务协议？

找到原因了 因为不支持全端口扫描 所以就没有识别出服务。

**Comment by gobysec** [comment]
> > > 如果同样个IP存在两个同样的服务但只能扫出来一个nmap可以全扫出来。
> > 
> > 
> > 可否提供未识别的服务协议？
> 
> 找到原因了 因为不支持全端口扫描 所以就没有识别出服务。

支持全端口扫描的，端口框直接输1-65535
