### ISSUE TITLE
VPN扫描问题

### ISSUE THREAD

**Issue by Bigbang1001** [gobysec/Goby#63]
挂上vpn以后，单个IP扫描无问题，但是多个IP扫描会出现扫描不出东西的情况  1.6.154版本

**Comment by gobysec** [comment]
> 挂上vpn以后，单个IP扫描无问题，但是多个IP扫描会出现扫描不出东西的情况 1.6.154版本

VPN类型及操作系统是？

**Comment by Kuibagit** [comment]
> > 挂上vpn之后，个别IP扫描无问题，但是多个IP扫描会出现扫描不出东西的情况1.6.154版本
> 
> VPN类型及操作系统是？

在windows系统，企业专用vpn软件下扫描多个IP扫描不出东西的

**Comment by gobysec** [comment]
> > > 挂上vpn之后，个别IP扫描无问题，但是多个IP扫描会出现扫描不出东西的情况1.6.154版本
> > 
> > 
> > VPN类型及操作系统是？
> 
> 在windows系统，企业专用vpn软件下扫描多个IP扫描不出东西的

升级npcap到 0.9995以上版本试试。若goby还是无法识别网卡，wireshark抓包看下能否识别ipv4地址。若wireshark也无法识别，需要等npcap自身升级修复了。
