### ISSUE TITLE
程序包从一台电脑复制到另一台电脑运行会出找不到指定网卡的错误

### ISSUE THREAD

**Issue by zhoucj93** [gobysec/Goby#64]
![微信截图_20200603170148](https://user-images.githubusercontent.com/14963821/83617642-f2407780-a5bb-11ea-8051-b95a99614e03.png)
RT

**Comment by gobysec** [comment]
> ![微信截图_20200603170148](https://user-images.githubusercontent.com/14963821/83617642-f2407780-a5bb-11ea-8051-b95a99614e03.png)
> RT

这种方式移动导致了环境变化。若您是wins系统，请检查新的电脑是否安装了npcap。若已安装npcap，请尝试管理员权限运行。
