### ISSUE TITLE
win 版本 1.3.44 beta版本，发现不了虚拟机资产

### ISSUE THREAD

**Issue by sectestt** [gobysec/Goby#7]
虚拟机启动了一个Linux系统，从宿主机可以ping通，访问22和7001端口。
使用宿主机上的goby 1.3.44 扫描，指定虚拟机IP，扫描完成，未发现资产

**Comment by gobysec** [comment]
> 虚拟机启动了一个Linux系统，从宿主机可以ping通，访问22和7001端口。
> 使用宿主机上的goby 1.3.44 扫描，指定虚拟机IP，扫描完成，未发现资产

应该是网卡问题。关于网卡问题后续我们经过系列版本已经解决，你可以下载最新版本进行测试。如若复现，请重新提issue给我。
