### ISSUE TITLE
使用建议

### ISSUE THREAD

**Issue by 0lh** [gobysec/Goby#70]
1、新建扫描任务时，指定任务名，方便在扫描任务历史里面区分
2、扫描任务历史如果选中某一个任务，导出、报告、删除等按钮不能点击
3、全部资产导出表格，添加content-length字段，方便后面通过content-length排序

**Comment by gobysec** [comment]
> 1、新建扫描任务时，指定任务名，方便在扫描任务历史里面区分
> 2、扫描任务历史如果选中某一个任务，导出、报告、删除等按钮不能点击
> 3、全部资产导出表格，添加content-length字段，方便后面通过content-length排序

A1：已实现，下个版本发布
A2：的确不支持删除当前任务。但可以支持导出资产数据和报告，后面我们安排上。
