### ISSUE TITLE
error query问题

### ISSUE THREAD

**Issue by wuguan8888** [gobysec/Goby#76]
服务端版本1.7.186beta，客户端版本1.7.186beta
加载扫描结果就会报错error query， 导致无法通过gui查看数据库已录入的资产
![image](https://user-images.githubusercontent.com/11627654/87137312-43d0d600-c2cf-11ea-9715-0c48213cbfed.png)
![image](https://user-images.githubusercontent.com/11627654/87137241-2d2a7f00-c2cf-11ea-9ef2-727b1793f3ba.png)

**Comment by gobysec** [comment]
问题已解决，请更新最新版。
