### ISSUE TITLE
功能建议  本地server卡死

### ISSUE THREAD

**Issue by Akityo** [gobysec/Goby#86]
goby在启动本地server失败后，会持续重连本地server，导致无法进行配置远程server。

建议增加选择功能，重连本地server或者连接远程server。

![image](https://user-images.githubusercontent.com/16974004/89264605-c9913880-d665-11ea-82fb-32a3a264a739.png)

**Comment by gobysec** [comment]
很棒的建议，我们后续加上。感谢反馈。

**Comment by gobysec** [comment]
> goby在启动本地server失败后，会持续重连本地server，导致无法进行配置远程server。
> 
> 建议增加选择功能，重连本地server或者连接远程server。
> 
> ![image](https://user-images.githubusercontent.com/16974004/89264605-c9913880-d665-11ea-82fb-32a3a264a739.png)

194版本已实现
