### ISSUE TITLE
VPN环境无法通过网卡进行扫描。

### ISSUE THREAD

**Issue by Huninglong** [gobysec/Goby#90]
但虚拟机可以通过NAT模式进行下去，转移到物理机，Goby却无法与对应的IP进行通信。

**Comment by gobysec** [comment]
> 但虚拟机可以通过NAT模式进行下去，转移到物理机，Goby却无法与对应的IP进行通信。

哪家VPN呢？wireshark抓包是否可以识别到ipv4网卡？

**Comment by Huninglong** [comment]
深信服（EasyConnect）      通过nessus可以实现扫描。



hnl12580@163.com
 
发件人： Goby
发送时间： 2020-08-17 15:31
收件人： gobysec/Goby
抄送： hnl; Author
主题： Re: [gobysec/Goby] VPN环境无法通过网卡进行扫描。 (#90)
但虚拟机可以通过NAT模式进行下去，转移到物理机，Goby却无法与对应的IP进行通信。
哪家VPN呢？wireshark抓包是否可以识别到ipv4网卡？
―

**Comment by gobysec** [comment]
Goby最新版1.8.221  npcap升级到0.9995以上版本，可解决深信服VPN识别网卡问题。
