### ISSUE TITLE
1.7.192beta版本扫描约3000个IP的时候进度卡死在89%

### ISSUE THREAD

**Issue by newIDforLOL** [gobysec/Goby#91]
1.7.192beta版本，扫描约3000个IP，扫描进度增加至89%后始终不再动，界面可以正常点击切换，但进度不会再继续。

手动点击暂停，确认，再继续，则自动从69%或70%的位置重新开始扫描直至结束。

89%似乎是个神奇的数字...

**Comment by gobysec** [comment]
> 1.7.192beta版本，扫描约3000个IP，扫描进度增加至89%后始终不再动，界面可以正常点击切换，但进度不会再继续。
> 
> 手动点击暂停，确认，再继续，则自动从69%或70%的位置重新开始扫描直至结束。
> 
> 89%似乎是个神奇的数字...

已知经常会84%卡死。扫描序列改为“同时扫描”试试
