### ISSUE TITLE
Win7下面对VM网卡扫描失败

### ISSUE THREAD

**Issue by tysmlq** [gobysec/Goby#92]
Win7下用实际网卡ip可扫描，但扫描本机上的虚机ip则报错，提示npcap问题，虚机的ip是nat方式，
已重装npcap，仍然报错。无论设置网卡为“Auto、物理网卡IP、虚机IP”，对虚机扫描均报错

虚机是VM12，不知是不是与虚机网卡有关

**Comment by tysmlq** [comment]
以管理员身份运行了Goby也是同样问题，也看了其他评论，感觉很多报错问题都与网卡有关，估计与npcap有一定关系，这个问题可能对使用的影响比较广泛。

**Comment by gobysec** [comment]
> 以管理员身份运行了Goby也是同样问题，也看了其他评论，感觉很多报错问题都与网卡有关，估计与npcap有一定关系，这个问题可能对使用的影响比较广泛。

npcap升级到0.9995试试呢

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by tysmlq** [comment]
升级过了，无效。
近期试了很久，发现只要本机的VM虚机网卡采用NAT方式，无论对虚机ip还是物理机的VNet8网卡（它俩是一个IP段）扫描，都会报错。如果采用桥接方式，与物理网卡一个IP段，扫描正常。
感觉应该是Goby对VM虚机的网卡NAT模式识别问题。

**Comment by aguai778** [comment]
这个问题怎么解决  我在云服务器使用也是这个问题 应该是goby识别虚拟网卡的问题
