### ISSUE TITLE
配置fofa API提示未授权

### ISSUE THREAD

**Issue by anquanceshi** [gobysec/Goby#95]
![图片](https://user-images.githubusercontent.com/46336081/90952047-e4034880-e492-11ea-8e61-89232d1edbd7.png)
请问怎么处理

**Comment by gobysec** [comment]
> ![图片](https://user-images.githubusercontent.com/46336081/90952047-e4034880-e492-11ea-8e61-89232d1edbd7.png)
> 请问怎么处理

使用FOFA查询必须是FOFA会员。
